### ISSUE TITLE
Command-line Maven build fails due to test failures

### ISSUE THREAD

**Issue by Greg4cr** [EvoSuite/evosuite#10]
Trying to build EvoSuite from source in Ubuntu 15.04 using the latest version of Maven from the command line, and my build (specifically "mvn package") fails because two of the auto-executed tests fail. I have not changed any of the code yet - just trying to build for now. Any clues on why these two tests fail? I've attached the surefire reports.

Thanks!

[TEST-org.evosuite.runtime.sandbox.MSecurityManagerTest.txt](https://github.com/EvoSuite/evosuite/files/64570/TEST-org.evosuite.runtime.sandbox.MSecurityManagerTest.txt)
[TEST-org.evosuite.runtime.mock.javax.swing.MockJFileChooserTest.txt](https://github.com/EvoSuite/evosuite/files/64571/TEST-org.evosuite.runtime.mock.javax.swing.MockJFileChooserTest.txt)

**Comment by arcuri82** [comment]
weird... we run those tests (plus more) on both Mac/Linux with no problem... which version of Java are you using?

btw, one of the two test logs pointed to a library issue. I made a fix for it. Can you please re-run the tests and check if they still fail? (I cannot on my machine as i could not reproduce your problem)

thanks

**Comment by Greg4cr** [comment]
One of the tests no longer fails (with your library fix). 

org.evosuite.runtime.mock.javax.swing.MockJFileChooserTest still fails. I'll look into it when I get a chance and see if anything pops out, but I thought I'd see if there was something obvious first.

**Comment by Greg4cr** [comment]
Took a look at the failing test. 

Specifically, what fails is:
@Test
	public void testGetCurrentDirectory(){
		
		JFileChooser chooser = new MockJFileChooser();
		File dir = chooser.getCurrentDirectory();
		
(X)		Assert.assertTrue(dir.exists());
		Assert.assertTrue(dir instanceof MockFile);
	}

with a null pointer exception. This, I suppose, makes sense - the default constructor for MockJFileChooser just sets the current directory to null. The command chooser.getCurrentDirectory() returns a null object, and so, dir.exists() throws a null pointer exception.

This prevents mvn package from executing for me. For now, I'm just commenting out this test so I can see if the rest of the build will progress without hitches.

**Comment by Greg4cr** [comment]
I also have two tests failing for evosuite-master:

<testcase name="testShouldNotWorkOnEvoSuitePackage" classname="org.evosuite.basic.TestShouldNotWork" time="0.166">
    <failure message="Expected exception: java.lang.IllegalArgumentException" type="java.lang.AssertionError">java.lang.AssertionError: Expected exception: java.lang.IllegalArgumentException
</failure>
    <system-out><![CDATA[14:43:15,335 |-INFO in ch.qos.logback.classic.LoggerContext[ContextForTests] - Could NOT find resource [logback.groovy]
14:43:15,335 |-INFO in ch.qos.logback.classic.LoggerContext[ContextForTests] - Could NOT find resource [logback-test.xml]
14:43:15,335 |-INFO in ch.qos.logback.classic.LoggerContext[ContextForTests] - Found resource [logback.xml] at [file:/home/greg/svn/evosuite/master/target/test-classes/logback.xml]
14:43:15,335 |-WARN in ch.qos.logback.classic.LoggerContext[ContextForTests] - Resource [logback.xml] occurs multiple times on the classpath.
14:43:15,335 |-WARN in ch.qos.logback.classic.LoggerContext[ContextForTests] - Resource [logback.xml] occurs at [file:/home/greg/svn/evosuite/master/target/test-classes/logback.xml]
14:43:15,335 |-WARN in ch.qos.logback.classic.LoggerContext[ContextForTests] - Resource [logback.xml] occurs at [jar:file:/home/greg/svn/evosuite/client/target/evosuite-client-1.0.3-SNAPSHOT-tests.jar!/logback.xml]
14:43:15,370 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:43:15,375 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - Setting logger context name as [ContextForTests]
14:43:15,375 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
14:43:15,393 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:43:15,413 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:43:15,414 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6fc6f14e - Registering current configuration as safe fallback point

ERROR evo_logger - No defined classpath for the target project. From command line you can set it with the -projectCP option
]]></system-out>
  </testcase>

  <testcase name="testJavaPackageNotOnProjectCP" classname="org.evosuite.basic.TestShouldNotWork" time="0.001">
    <failure message="expected:&lt;1&gt; but was:&lt;0&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<0>
	at org.evosuite.basic.TestShouldNotWork.testJavaPackageNotOnProjectCP(TestShouldNotWork.java:74)
]]></failure>
    <system-out><![CDATA[ERROR evo_logger - No defined classpath for the target project. From command line you can set it with the -projectCP option
]]></system-out>
  </testcase>

Any ideas? I'm wondering if there is something very simple at the root of these test failures, but I'm not sure what it is that I'm doing on my end that is different from yours.

FYI - My Java version is:
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by arcuri82** [comment]
Hi Greg,
  we have been making some changes. Those 2 tests should not be failing now. However, regarding

```
@Test
public void testGetCurrentDirectory(){

    JFileChooser chooser = new MockJFileChooser();
    File dir = chooser.getCurrentDirectory();

    Assert.assertTrue(dir.exists()); //Line that throws the exception
    Assert.assertTrue(dir instanceof MockFile);
}
```

the point is that the dir is not set to null, because:

```
@Override
	public void setCurrentDirectory(File dir) {
		
		if(!finishedInitializingSuperclass){
			return;
		}
		
		File oldValue = currentDirectory;

		if (dir != null && !dir.exists()) {
			dir = currentDirectory;
		}
		if (dir == null) {
			dir = getFileSystemView().getDefaultDirectory();
		}
		if (currentDirectory != null) {
			/* Verify the toString of object */
			if (this.currentDirectory.equals(dir)) {
				return;
			}
		}

		File prev = null;
		while (!isTraversable(dir) && prev != dir) {
			prev = dir;
			dir = getFileSystemView().getParentDirectory(dir);
		}
		currentDirectory = dir;

		firePropertyChange(DIRECTORY_CHANGED_PROPERTY, oldValue, currentDirectory);
	}
```

can you use a debugger and check what ``getFileSystemView().getDefaultDirectory()`` returns on your machine?

cheers

Andrea

**Comment by Greg4cr** [comment]
Ah - I tracked down the source of the problem. I'm running mvn package in sudo, and the default directory that is returned (/root) does not exist. This manifests in a null pointer exception when that test is run.

**Comment by Greg4cr** [comment]
This can be closed - the issue was due to permissions problems on my local machine, and is not an EvoSuite problem. Everything is working for me after I resolved the local issue.
