### ISSUE TITLE
Fix Maven plugin documentation

### ISSUE THREAD

**Issue by jonfreedman** [EvoSuite/evosuite#103]
http://www.evosuite.org/documentation/maven-plugin/ states 

> by default, EvoSuite creates the tests in the “.evosuite/evosuite-tests” folder.

which appears to be outdated: https://github.com/EvoSuite/evosuite/blob/master/plugins/maven/src/main/java/org/evosuite/maven/ExportMojo.java#L51

and

> Note: currently EvoSuite is not hosted yet on Maven Central

which also appears to be outdated:
https://mvnrepository.com/artifact/org.evosuite.plugins/evosuite-maven-plugin/1.0.4

Given tests are written to `src/main/test` by default I am not sure that the prepare step is still needed - tests are still run fine without .scaffolding_list.tmp - it would be good to clarify whether that is needed too.

**Comment by vinuthakr20** [comment]
Hello,
I am vinutha a graduate student from UNT, I have taken my term project as "extending the Evosuite Tool", I have installed Eclipse Luna as IDE and I am unable to proceed the moment I started working with maven plugin, i have downloaded it, added it to the IDE, but unable to compile it, I am following the website http://www.evosuite.org/documentation/tutorial-part-4/ as my reference, I need some information from people who have already worked on the tool, I am new to GitHub too, Please do help me.

Thank you,
Best
Vinutha

**Comment by jonfreedman** [comment]
Try and build using maven on the command line, according to Travis it should build [fine](https://travis-ci.org/EvoSuite/evosuite)

**Comment by gofraser** [comment]
vinuthark20, if you have problems building, I suggest you try the developer's mailing list (https://groups.google.com/forum/#!forum/evosuite)

The export mojo copies tests to src/test/java by default, but it needs to be called explicitly. If you just call generate, tests will still end up in .evosuite (until you call export to have them copied)

Will update the docs.

**Comment by vinuthakr20** [comment]
Hello Gordon Fraser,
Thank you so much for the information, this will be really helpful for my
project.

Best
Vinutha

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by gofraser** [comment]
The webpage should be up to date again now.
