### ISSUE TITLE
Support multi-os development environments

### ISSUE THREAD

**Issue by jonfreedman** [EvoSuite/evosuite#104]
### Context
I am experimenting with EvoSuite - we have developers working on Windows and Linux - if I generate tests on Windows they don't run on Linux and vice-versa.  I believe this is due to `#setSystemProperties` generated in each saffolding class setting various fragile properties.  If I change this method in the first generated class as follows the tests run on both OS.

```
    public static void setSystemProperties() {
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }
```

### EvoSuite Arguments
`mvn -DmemoryInMB=6000 -Dcores=12 evosuite:generate evosuite:export`

### Current Result
Running tests generated on Linux on Windows
```
java.lang.NoClassDefFoundError: Could not initialize class org.evosuite.runtime.mock.java.util.prefs.MockPreferences

	at org.evosuite.runtime.Runtime.resetRuntime(Runtime.java:86)
	at org.evosuite.runtime.classhandling.ClassStateSupport.loadClasses(ClassStateSupport.java:124)
	at org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ClassStateSupport.java:62)
```
Running tests generated on Windows on Linux
```
java.lang.NoClassDefFoundError: Could not initialize class org.evosuite.runtime.mock.java.util.prefs.MockPreferences
```
 
### Expected result
Either tests run on any OS or can be generated multiple times incorporating the OS into the filename and making use of [org.junit.Assume](http://junit.org/junit4/javadoc/4.12/org/junit/Assume.html) to validate the `os.name` system property.

**Comment by gofraser** [comment]
Thanks. We could exclude some of the properties from being set by EvoSuite to OS-specific values, but I am not sure which ones are problematic. Instead of removing all the calls to setProperty, would you be able to try out which of the properties are causing compatibility problems? We could then exclude these.

Btw, the error message you are showing is related to the initialisation of the Preferences, but your suggestion is about Properties. Is there some influence between the two? I.e., if you do not set the Properties, then there is no error about initialising the MockPreferences?

**Comment by jonfreedman** [comment]
I can try and dig into this further however I would like to state my preference for use of evosuite as I am trying to bake in API behaviour rather than work with a legacy system... Ideally I would run the test generator with a stable seed so it deterministically produced the same output given unchanged input on any OS, whether that is a pre or post condition for ignoring the environment I do not have a strong opinion. It would be great to have an example documented showing that! 

---- On Mon, 17 Apr 2017 15:04:09 +0000 notifications@github.com wrote ----

Thanks. We could exclude some of the properties from being set by EvoSuite to OS-specific values, but I am not sure which ones are problematic. Instead of removing all the calls to setProperty, would you be able to try out which of the properties are causing compatibility problems? We could then exclude these.

Btw, the error message you are showing is related to the initialisation of the Preferences, but your suggestion is about Properties. Is there some influence between the two? I.e., if you do not set the Properties, then there is no error about initialising the MockPreferences?

**Comment by gofraser** [comment]
I've made a change so that EvoSuite excludes a number of properties that seem system-specific. Could you please try if the version in the repository leads to deterministic results for you?

**Comment by gofraser** [comment]
The latest version (1.0.5) includes changes to avoid setting some platform-specific properties, so I'm closing this. Let me know if the problem persists. (This will only apply to newly generated tests, of course).
