### ISSUE TITLE
Mutation test 

### ISSUE THREAD

**Issue by georgiaxron** [EvoSuite/evosuite#107]
i am using evosuite with Eclipse neon and cmd and as a project at mutation for my university i want to find out if it is possible to isolate or even add a group of operators for testing when the mutants are created. For example i would like create mutants with only arithmetic operators. Is it possible?

**Comment by gofraser** [comment]
The mutation operators that are applied are currently hard-coded in org.evosuite.instrumentation.coverage.MutationInstrumentation. It would be quite straight forward to make this a property - would that help?

Are you planning to study the influence of mutation operators on test generation, or on assertion minimisation?

Implementing new mutation operators would be a matter of implementing the org.evosuite.instrumentation.mutation.MutationOperator interface.

**Comment by georgiaxron** [comment]
i am planning to study the influence of mutation operators on test generation. Thank you your respond was very helpfull...

**Comment by Alimpertis39** [comment]
Generally , can we use evosuite for mutation testing? And how can we use it for this purpose?

**Comment by gofraser** [comment]
To use mutation testing for test generation, you just need to specify either "weakmutation" or "strongmutation" as one of the target criteria. "Weakmutation" is included by default.

(Since strongmutation is not on by default, there might be bugs I am not aware of. Please report any issues you encounter.)
