### ISSUE TITLE
Coverage of criterion 

### ISSUE THREAD

**Issue by Alimpertis39** [EvoSuite/evosuite#111]
In the java file which is created by Evosuite run, which is called .....CSTest.java , we can see all goals of Weak Mutation testing that are covered. And after running of Evosuite we can see the percentage of coverage of criterion WEAK MUTATION. How can we see the goals that are not covered by JUnit test?
Generally how can I see what is not covered either in criterion of weak mutation or in criterion of branch coverage?

Thank you very much for your help!

**Comment by gofraser** [comment]
Actually, this is already supported using `-Dprint_missed_goals=true`.
