### ISSUE TITLE
is there an option to remove the Evosuite specific runners (@RunWith(EvoRunner.class) @EvoRunnerParameters)?

### ISSUE THREAD

**Issue by monperrus** [EvoSuite/evosuite#112]
In some cases, there is a need for simple traditional Junit tests.

is there an option to remove the usage of the Evosuite specific runners (@RunWith(EvoRunner.class) @EvoRunnerParameters)?

**Comment by gofraser** [comment]
Yes, try generating tests with -Dno_runtime_dependency=true

**Comment by monperrus** [comment]
thanks!

**Comment by gofraser** [comment]
Just to have this documented here: Note that you might get failing/flaky tests by deactivating the runner and dependencies.

**Comment by monperrus** [comment]
Also for the record: it seems that the command-line option is not taken into account.

We use "-Dno_runtime_dependency=true". Correct?

(We're also investigating the problem.)

Are all options passed between the master and the client?

--Martin

**Comment by gofraser** [comment]
It works fine for me. Which version are you using, and are you using any other options at the same time?

**Comment by monperrus** [comment]
OK the reason is that is we used a version before the corresponding fix https://github.com/EvoSuite/evosuite/commit/ff8fd762d678100fd17f6a7bdf153d91823a90d7
