### ISSUE TITLE
not found evosuite

### ISSUE THREAD

**Issue by ershallu** [EvoSuite/evosuite#118]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

![image](https://user-images.githubusercontent.com/27766724/27235319-f5fa6860-52dd-11e7-8655-25c3d4507912.png)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.
2.
3.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by gofraser** [comment]
This doesn't look like an EvoSuite problem, you are specifying an incomplete class path when compiling. Your call to java should include (1) the evosuite-tests directory, not evosuite-tests/tutorial/*.java, (2) a JUnit jar, and (3) the evosuite-standalone-runtime.jar

**Comment by ershallu** [comment]
i set the classpath as Set classpath=target/classes:evosuite-runtime-1.0.5.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar
I am confused where is evosuite-runtime-1.0.5.jar as i have downloaded only  evosuite-standalone-runtime-1.0.5.jar
@gofraser

**Comment by gofraser** [comment]
You need to have the classpath point to evosuite-standalone-runtime-1.0.5.jar not evosuite-runtime-1.0.5.jar (and it needs to be in the path you're pointing to)

**Comment by ershallu** [comment]
ok

**Comment by ershallu** [comment]
![image](https://user-images.githubusercontent.com/27766724/27235912-64faec88-52e0-11e7-8e17-05186d367e60.png)
@gofraser

**Comment by gofraser** [comment]
Thanks. Clearly, your class path is incorrect. You are getting error messages that JUnit is not on the classpath (e.g. org.junit.BeforeClass). Try using semicolons to separate paths instead of colons. I don't know if using an environment variable "classpath" works on Windows? Also, if you do set CLASSPATH on a unix system, then don't specify -classpath as a parameter to javac

**Comment by ershallu** [comment]
thanks a lot.it works for me. @gofraser
