### ISSUE TITLE
Test Class Compilation Error related to generics

### ISSUE THREAD

**Issue by JavaJimFl** [EvoSuite/evosuite#119]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

I generated a test class for a Hibenate repository class using the Maven plugin, but the result will not compile.  

Given the method signature:

```
getFoos(FooFilter filter, Class<Foo> clazz)
```
the generated code is:

```
FooFiilter fooFilter0 = new FooFilter();
Class<Foo> class0 = Class.class:
fooRepository.getFoos(fooFilter0 , class0);
```

which results in the following compiliation error:

```
error: incompatible types: Class<Class> cannot be converted to Class<Foo>
```

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.  Create a method in a class that takes a class as a parameter.
2.  Generate a test class for that class.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
```
mvn evosuite:generate evosuite:export -Dcuts=com.foo.FooRepository
```

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

```
error: incompatible types: Class<Class> cannot be converted to Class<Foo>
``` 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

No compilation errors:

```
FooFiilter fooFilter0 = new FooFilter();
Class<Foo> class0 = Foo.class:
fooRepository.getFoos(fooFilter0 , class0);
```

### Additional info
*Please add any information of interest here below*

**Comment by gofraser** [comment]
EvoSuite is generally a bit confused about Class<?> but should now no longer try to instantiate the type parameter of Classes at all. Does this avoid the problem?
