### ISSUE TITLE
how to generate html report

### ISSUE THREAD

**Issue by ZhiqunZeng** [EvoSuite/evosuite#12]
in command line,I use -Dhtml=true，however,only csv file was created and  not  a html file

**Comment by jose** [comment]
by default, EvoSuite generates a CVS file. to get a HTML report you've to change the value of STATISTICS_BACKEND, i.e.,

`-Dstatistics_backend=HTML`

**Comment by arcuri82** [comment]
@jose, @gofraser : looking at the code. as ``-Dhtml`` is only used inside  ``HTMLStatisticsBackend``, shouldn't we just get rid of it? I mean, what sense there is in having ``-Dhtml=true`` while the backend is not html? what sense there is in having ``-Dhtml=false`` while backend is html?

**Comment by jose** [comment]
yep, that makes no sense. I think `-Dhtml` property can be removed.

**Comment by arcuri82** [comment]
ok, i removed it ;)

**Comment by ZhiqunZeng** [comment]
thank you very much

2016-02-08 8:09 GMT+08:00 José Campos <notifications@github.com>:
