### ISSUE TITLE
Test using org.evosuite.runtime.mock.java.util.MockGregorianCalendar fails

### ISSUE THREAD

**Issue by JavaJimFl** [EvoSuite/evosuite#123]
### Context
EvoSuite successfully generated tests for a Java class, but one of them fails because of an unexpected date assertion.   

The expectation for this test is set to just past the epoch time, "Thu Jan 01 00:00:00 GMT 1970."  However, when the test runs, it fails with the following error:

```
[ERROR]   BarEsTest.testGetDay:200 expected:<[Fri Feb 14 20:21:21 GMT 2014]> but was:<[Thu Jan 01 00:00:00 GMT 1970]>
```
This is the test code generated by EvoSuite:
```Java
@Test(timeout = 4000)
public void testGetDay()  throws Throwable  {
Timestamp timestamp0 = new Timestamp(1L);
    Foo foo0 = new Foo(")", timestamp0);
    Bar bar0 = new Bar(foo0);
    Date date0 = bar0.getDay();
    assertEquals("Fri Feb 14 20:21:21 GMT 2014", date0.toString());
}
```
The ```Bar``` calls a locally developed date utility method that basically truncates the date at the day field:

```Java
public static final Date newDate( int year, int month, int day ) {
  Calendar c = Calendar.getInstance();
  c.clear();
  c.set(year, month, day);
  return c.getTime();
}
```
However, the Calendar returned by the call to ```Calendar.getInstance()``` is an instance of ```org.evosuite.runtime.mock.java.util.MockGregorianCalendar``` whose internal state is set to a seemingly arbitrary value of 'Fri Feb 14 20:21:21 GMT 2014."  Since no behavior has been defined for it, the ```c.set(year, month, day);``` call does nothing.  Instead, the immutable date is returned and the test ultimately fails.

### Expected result
I would expect either the generated test expectation match the actual value returned by the mock Calendar instance or the call to ```Calendar.getInstance()``` return the Calendar implementation EvoSuite used to generate the tests.  The latter may be hard, as Mockito can't mock a static method.

**Comment by gofraser** [comment]
The mocked date is set to a fixed time to avoid flaky tests. If Calendar.getInstance() would return the current date, then any generated tests using dates would fail when executed on a different day/time than they were generated.

MockGregorianCalendar extends the regular GregorianCalendar and is *not* a Mockito mock. Thus it provides the full behaviour of GregorianCalendar, including set(year, month, day).

Does the test actually *fail*? Or is it just that you are expecting to see a different time?

**Comment by JavaJimFl** [comment]
It actually failed.  I understand the need for consistency, but if the MockGregorianCalendar will always return the same date, then the generated test expectations should match.  For example, in my test:

```Java
Timestamp timestamp0 = new Timestamp(1L)
```
should become
```Java
Timestamp timestamp0 = new Timestamp(1392409281000L);
```
1392409281000 is the long equivalent of "Fri Feb 14 20:21:21 GMT 2014" (At least according to the online converter I used ;) )

Does that make sense?

**Comment by gofraser** [comment]
The reason the set method doesn't work is this part in MockGregorianCalendar:

```
	// TODO: This code in Calendar seems to cause access to time
	//       but I don't understand how.
	//    public long getTimeInMillis() {
	//        if (!isTimeSet) {
	//            updateTime();
	//        }
	//        return time;
	//    }
    public long getTimeInMillis() {
        return time;
    }
```

If you can figure out what exactly in GregorianCalendar.computeTime() causes the time to be influenced by the system clock, it would be possible to fix this. Otherwise, there's either fixed time or flaky tests...

That being said, even with a fixed time the test should not fail (and using your example snippet I get a test that passes fine, with a fixed time).

**Comment by gofraser** [comment]
Independently of whether the time reported makes sense, the tests I can produce here are not flaky, so I'll close this issue. If there is still some flakiness, please re-open.
