### ISSUE TITLE
The instruction ist not up to date

### ISSUE THREAD

**Issue by adler4566** [EvoSuite/evosuite#124]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. followTutorial Part 1: EvoSuite on the Command Line
2. if you try to compile your tests, a lot of Exceptions will be thrown

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
`javac evosuite-tests/tutorial/*.java`

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
before you compile the generated tests you need to set the CLASSPATH environment variable.
The given path for the CLASSPATH environment variable in the tutorial is wrong. The right path is:

`export CLASSPATH=target/classes:evosuite-standalone-runtime-1.0.3.jar:eosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar`

So the name of the evosuite jar is wrong

**Comment by sinaa** [comment]
Thank you for reporting this.

The tutorial on the website needs to be updated. 

In the meantime, the latest version can be found on our wiki: https://github.com/EvoSuite/evosuite/wiki/Tutorial:-Part-1--Evosuite-on-the-Command-Line

**Comment by yixuanhuangyx** [comment]
![image](https://user-images.githubusercontent.com/26773855/49126645-b615c200-f307-11e8-9f31-20b0b440a0c3.png)

has a typo on Windows command, should be
 set CLASSPATH=target/classes;evosuite-standalone-runtime-1.0.6.jar;evosuite-tests;target/dependency/junit-4.12.jar;target/dependency/hamcrest-core-1.3.jar
