### ISSUE TITLE
Evosuite generates tests that incorrectly reference static member variables (v1.0.5)

### ISSUE THREAD

**Issue by JavaJimFl** [EvoSuite/evosuite#126]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

I was reviewing a test generated by EvoSuite and noticed a static variable referenced via an instance of a class, not the class itself:

```Java
  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Foo foo0 = new Foo();
      Bar bar0 = new Bar(0);
      
      // I would expect this to be Bar.DEFAULT_ERROR_CAPACITY
      foo0.setCycleID((Integer) bar0.DEFAULT_ERROR_CAPACITY);
      Integer integer0 = foo0.getSomething();
      assertEquals(100, (int)integer0);
  }
```
Note: Despite the uppercased name of the variable, it's actually defined as just ```public static```, not ```public static final```.

There are other tests that reference the same static member correctly, but only when an instance of the class isn't part of the test.

### Current Result
The test on which the above example is based fails when run using Maven and passes when run in the IDE.  I don't know how or if this issue is related those symptoms.
 
### Expected result
I would expect a static member variable to be referenced by its class name regardless of the context in which it's generated.

**Comment by prathmesh-halgekar** [comment]
It would be great if you could also provide the Classes under Test. Thanks.

**Comment by gofraser** [comment]
We've been testing this and haven't been able to reproduce it - whatever we do, it seems to work correctly. If you can provide a class/example to reproduce the problem we can re-open this issue.
