### ISSUE TITLE
How to use search_budget property

### ISSUE THREAD

**Issue by beatngu13** [EvoSuite/evosuite#132]
According to [`org.evosuite.Properties`](https://github.com/EvoSuite/evosuite/blob/master/client/src/main/java/org/evosuite/Properties.java), the `search_budget` property represents the "Maximum search duration". What confuses me is that the property is used within the following stopping conditions:

* [`MaxFitnessEvaluationsStoppingCondition`](https://github.com/EvoSuite/evosuite/blob/master/client/src/main/java/org/evosuite/ga/stoppingconditions/MaxFitnessEvaluationsStoppingCondition.java)
* [`MaxGenerationStoppingCondition`](https://github.com/EvoSuite/evosuite/blob/master/client/src/main/java/org/evosuite/ga/stoppingconditions/MaxGenerationStoppingCondition.java)
* [`MaxTimeStoppingCondition`](https://github.com/EvoSuite/evosuite/blob/master/client/src/main/java/org/evosuite/ga/stoppingconditions/MaxTimeStoppingCondition.java)
* [`MaxStatementsStoppingCondition`](https://github.com/EvoSuite/evosuite/blob/master/client/src/main/java/org/evosuite/ga/stoppingconditions/MaxStatementsStoppingCondition.java)
* [`MaxTestsStoppingCondition`](https://github.com/EvoSuite/evosuite/blob/master/client/src/main/java/org/evosuite/ga/stoppingconditions/MaxTestsStoppingCondition.java)

Doesn't this mix different units? If, for instance, I would like to limit the maximum number of generations and use the `search_budget` property for this, doesn't this interfere with the other stopping conditions? How can I properly do this?

**Comment by sinaa** [comment]
The search budget property is shared between different stopping conditions. The unit of the search budget is according to the corresponding stopping condition.

For example, if `stopping_condition` is set to `MAXTIME`, then a `search_budget` of 60 means 60 seconds.

If the stopping condition is set to `MAXGENERATIONS`, then a `search_budget` of 1000, would mean to stop the search after 1000 generations.

As far as I'm aware, there's no way to set multiple stopping conditions.

This is however a `GLOBAL_TIMEOUT` available, if you want to set an upper bound timeout over your non-maxtime search budget.

**Comment by beatngu13** [comment]
Thanks for the prompt feedback. I did not know that there is usually only one stopping condition; with that (and `stopping_condition`) in mind, it makes sense now.
