### ISSUE TITLE
EvoSuit Maven Plugin attempts to use JRE instead of JDK and fails

### ISSUE THREAD

**Issue by araguacaima** [EvoSuite/evosuite#137]
### Context

The hardcoded use of "**java**" executable on "**org.evosuite.maven.util.EvoSuiteRunner**" causes an exception when SO provides a JRE instead of expected JDK java executable.

If you configure inside your PATH env a valid path of java pointing to **${JRE_HOME}/bin**, EvoSuite doesn't find needed libraries and it fails.

### Steps to Reproduce

1. Configure your PATH env variable like: PATH=$PATH;$JRE_HOME/bin
2. Be sure when you call "java" you are running those provided by JRE instead of JDK
3. Attempt to execute goal mvn evosuite:generate

### EvoSuite Arguments

Don't care

### Current Result

No test are generated 

**Plugin Log:**

`
[INFO] Going to execute 1 jobs
[INFO] Estimated completion time: 1 minutes, by 2017-09-05T15:40:48.461
[INFO] Going to start job for: org.araguacaima.utils.DataTypesConverter. Expected to end in 60 seconds, by 2017-09-05T15:40:48.951
[INFO] Registered remote process from /127.0.0.1:58198
[INFO] Registered remote process from /127.0.0.1:58206
[INFO] Completed job. Left: 0
[INFO] * Updating database to org.araguacaima.utils.DataTypesConverter
[INFO] === CTG run results ===
[INFO] Removed test suites: 0
[INFO] New test suites: 0
[INFO] WARN: failed to generate tests for org.araguacaima.utils.DataTypesConverter
[INFO] Stopping spawn process manager
`
 
**std_err_MASTER.log**

`
[MASTER] 15:40:06.997 [Thread-3] ERROR ExternalProcessHandler - Exception while reading output of client process. Stream closed
[MASTER] 15:40:07.935 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 15:40:08.036 [main] ERROR TestGeneration - failed to write statistics data
`

### Expected result

A test for all classes (or at leats one) in a valid project

### Additional info

Even my PATH env point correctly to JDK for java, attempting to run java throws the SO installed one...

![java](https://user-images.githubusercontent.com/979801/30082699-5a355b20-9251-11e7-8206-89f1b8cd98a5.png)

so it fails...

**Comment by araguacaima** [comment]
After uninstalling JRE (for testing)

![java2](https://user-images.githubusercontent.com/979801/30083204-3b8267c0-9253-11e7-8bbb-0e26f0eb4f40.png)

Test are generated as expected

**Comment by gofraser** [comment]
This actually seems to be an instance of the problem fixed in c41855f568290825ec9f65322e6d2bb1b9eed641. Thus I am closing this issue; please re-open if the problem re-appears.
