### ISSUE TITLE
configuration using the command line 

### ISSUE THREAD

**Issue by eran505** [EvoSuite/evosuite#138]
Hi,
I'm using Evosuite via the command line, using a script that run each class in the project, like it was running alone.
can i control the amount of memory (RAM) for generating a class?
One more question can i control the amount of time (in seconds) for generating each class?
so far i used the -Dsearch_budget and -Dglobal_timeout, but when i open the statistics.csv file (after adding _Doutput_variables=Total_Time) many classes exceed the allotted time, i guesses it because the minimization and assertion processes after the search.

Thanks

**Comment by gofraser** [comment]
You can use the -mem option to specify the amount of memory that EvoSuite will use for the client process. What you specify here will be passed on to the -Xmx JVM parameter of the client process. For the master process, you can set the JVM options directly.

The option -Dsearch_budget specifies only the time spent on the actual search; the minimisation, assertion generation, compile check, etc. are not included. There currently is no option to set a global timeout that covers all these phases, you'll have to set individual timeouts. Note that even if you specify a search_budget you might get some minimal variation, depending on how long test executions last and how much cleanup there needs to be done after each test.
