### ISSUE TITLE
EvoSuite and unstable assertion

### ISSUE THREAD

**Issue by jcr2015** [EvoSuite/evosuite#14]
In one application I got this test generated by EvoSuite

  public void test10()  throws Throwable  {
      Entier entier0 = Entier.UN; // constructed with "1" as a value
      int int0 = entier0.getValue();
      //  // Unstable assertion:   assertEquals(1, int0);
  }

What means "unstable assertion" ?
Furthermore evaluating int0 I found "-65" during test, I do not understand that.
regards

**Comment by arcuri82** [comment]
To be usable, a test should be deterministic: ie, if run several times, it should always pass unless a change is introduced in the target class. Unfortunately, there might be several sources of non-determinism, like for example threads and CPU clock-time. EvoSuite tries to mock away most sources of non-determinism, but it is not 100% bullet proof :(  In that case, EvoSuite might try to run the same test several times. If it fails, then it would be an "unstable" test. An option could be to just get rid of the test. Another option (which is the one we use) is to keep the test, but comment out its assertions (so it will not fail)

**Comment by jcr2015** [comment]
OK thanks for the reply.
I understand the first point but I don't see why I got "-65", I will try to isolate the problem.
regards

**Comment by jcr2015** [comment]
I think the problem is linked with another test (which was also marked unstable)

Changing value (-65) to (-42) in test00 is also changing it into test10.
Masking test00 or running test10 alone then test10 is OK
Renaming test10 into test100 and running it is OK

There is a strange implicit execution link between "test00" and "test10" ??? 

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Entier_ESTest extends Entier_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      Entier entier0 = Entier.UN;
      entier0.valeur = 4835;
      //entier0.valeur = (-65);
      entier0.valeur = (-42); // changing it change it into test10
      boolean boolean0 = entier0.isZero();
      assertFalse(boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      Entier entier0 = Entier.UN;
      // entier0 seems OK here
      int int0 = entier0.getValue();
      System.out.println("test10 "+ int0); // (-65) ???
      // // Unstable assertion:
      // it is OK without test00 or renaming this test
      assertEquals(1, int0);
  }
}

package code;
public class Entier  {
	
	public final static Entier ZERO = new Entier(0);
	
	public final static Entier UN = new Entier(1);
	
	protected int valeur;

	public int getValue() {
		return valeur;
	}
	
	public Entier(int a){
		this.valeur = a;
	}

	public boolean isZero() {
		return this.valeur==0;
	}
}

**Comment by jgaleotti** [comment]
Hi, 
Could you please also paste the command line you used (EvoSuite options) and copy the Entier_ESTest_scaffolding too?

Regards,
JP

**Comment by jgaleotti** [comment]
Hi
One more thing, did you explicitly set any value to -Dreset_static_fields (default=true) ?

Regards,
JP

**Comment by jcr2015** [comment]
Hi
Command line ? I use the Eclipse menu and did not explicitly change any option, by the way I see some options in preferences and in the project properties.
<img width="666" alt="capture d ecran 2016-02-01 a 15 10 07" src="https://cloud.githubusercontent.com/assets/13961318/12719553/00fefee2-c8f6-11e5-8940-cbf98df450b6.png">

In the Junit launch configuration I did not change any option (and there is no argument there).

// here is the scaffolding
package code;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class Entier_ESTest_scaffolding {

  @org.junit.Rule 
  public org.junit.rules.Timeout globalTimeout = new org.junit.rules.Timeout(4000); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "code.Entier"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Entier_ESTest_scaffolding.class.getClassLoader() ,
      "code.Entier"
    );
  } 
}

**Comment by gofraser** [comment]
Hi,

Can you try activating "Transform nondeterministic calls" in the settings,
and see if you get rid of the flaky tests? If this doesn't work, could you
please show us the resulting test again?

Best wishes,
Gordon

**Comment by jcr2015** [comment]
I test it alls are green, no unstable assertion.
Do I understand this is the solution ?
