### ISSUE TITLE
ERROR ClassStateSupport 

### ISSUE THREAD

**Issue by kpepper** [EvoSuite/evosuite#140]
### Context

Hi,

I am seeing errors like:

ERROR ClassStateSupport - Could not initialize net.sf.samtools.util.BlockCompressedInputStream: net/sf/samtools/seekablestream/SeekableStream
ERROR ClassStateSupport - Could not initialize com.sshtools.j2ssh.sftp.SftpSubsystemClient: com/sshtools/j2ssh/sftp/SshFxpFSetStat
etc

Is this anything to worry about and if so how do I fix it?

Thanks.

### Steps to Reproduce

Running the evosuite jar command via ant  to create unit tests in Java 8.

### EvoSuite Arguments

Ant task:

<jvmarg value="-noverify" />
<arg line="-Duse_separate_classloader=true -Dreport_dir=${evosuite.tests.report.dir} -Dshow_progress=false -Dconsider_main_methods=false -Dheadless_mode=true -base_dir ${evosuite.tests.dir} -mem 2000 -prefix a.package.prefix -target ${classes.dir} -projectCP ${evosuite.projectcp.arg}" />

**Comment by gofraser** [comment]
I assume this message was reported during the compile check at the end. As long as the generated tests pass anyway, there isn't a problem. The worst that could happen is likely flakey tests.

**Comment by kpepper** [comment]
Okay, thanks.
