### ISSUE TITLE
Compile and run generated Junit test case (in the ESTest class)

### ISSUE THREAD

**Issue by Mohannadcse** [EvoSuite/evosuite#142]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

I'm following the steps in the 1st tutorial which is based on the Tutorial Stack project ([http://www.evosuite.org/documentation/tutorial-part-1/]). I generate the Junit test cases successfully, and now trying to compile them according to the provided instructions.
So after 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. exporting the class path `export CLASSPATH=target/classes:evosuite-runtime-1.0.3.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar`
2. compile using `javac evosuite-tests/tutorial/*.java`

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

 
![image](https://user-images.githubusercontent.com/15859139/31192026-a0460540-a905-11e7-86a1-822c8b7fc64f.png)

Here are the generated file by EvoSuite under the evosuite-tests
[Stack_ESTest.txt](https://github.com/EvoSuite/evosuite/files/1356935/Stack_ESTest.txt)
[Stack_ESTest_scaffolding.txt](https://github.com/EvoSuite/evosuite/files/1356934/Stack_ESTest_scaffolding.txt)

 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

I should be able to compile and run the test cases

### Additional info
*Please add any information of interest here below*

**Comment by tussharalagh** [comment]
i am facing the exact error..i don't know why it is not compiling the tests

**Comment by gofraser** [comment]
Your classpath contains the EvoSuite dependencies and the test classes, but it doesn't include the actual classpath entry where the class tutorial.Stack can be found. This is not in the evosuite-tests directory, but it is what you specified as -projectCP when invoking EvoSuite.

**Comment by yixuanhuangyx** [comment]
Its because typo on the http://www.evosuite.org/documentation/tutorial-part-1/ 
for windows
![image](https://user-images.githubusercontent.com/26773855/49126564-6afbaf00-f307-11e8-8134-95c4f3870e4a.png)

should be 
set CLASSPATH=target/classes;evosuite-standalone-runtime-1.0.6.jar;evosuite-tests;target/dependency/junit-4.12.jar;target/dependency/hamcrest-core-1.3.jar
