### ISSUE TITLE
Loop Logger Throwing Null Pointer Exception

### ISSUE THREAD

**Issue by loren138** [EvoSuite/evosuite#143]
### Context
I'm running EvoSuite 1.0.5 with my own instrumenter, which is getting repeatedly called and hits the resource limit at times.  It also at times causes a Null Pointer Exception from Java.

(I'm running parts of Defects4J.  This is a part of the run for the Math_45 bug.)

### EvoSuite Arguments
Command to Build:
java -jar /home/loren/pullTest/bertGithub/evosuite-1.0.5.jar -class org.apache.commons.math.linear.OpenMapRealMatrix -projectCP /home/loren/repos/d4jBugs/Math_45/version/new/ -Dtest_dir=/home/loren/repos/d4jBugs/Math_45/version/evosuite/ -Dsearch_budget=180 -Dassertion_timeout=300 -Dshow_progress=true -Djunit_check=false -Dvirtual_fs=false -Dsandbox_mode=OFF -Dfilter_assertions=false -Dassertions=false -Dtest_comments=false -mem 1500

Command to Run Tests:
java -cp /home/loren/pullTest/bertGithub/:/home/loren/pullTest/bertGithub/src/main/java/:/home/loren/pullTest/bertGithub/junit-4.12.jar:/home/loren/pullTest/bertGithub/randoop-all-3.1.5.jar:/home/loren/pullTest/bertGithub/javassist.jar:/home/loren/pullTest/bertGithub/evosuite-standalone-runtime-1.0.5.jar:/home/loren/pullTest/bertGithub/hamcrest-core-1.3.jar:/home/loren/repos/d4jBugs/Math_45/version/oldInst/:/home/loren/repos/d4jBugs/Math_45/version/TestCaseInst/ -DtestXMLLogFolder=/home/loren/repos/d4jBugs/Math_45/version/XMLOut/old2/ org.junit.runner.JUnitCore org.apache.commons.math.linear.OpenMapRealMatrix_ESTest

### Current Result
![loop2](https://user-images.githubusercontent.com/1224505/31524632-03d45d08-af89-11e7-8f46-11ccf40ea5c2.png)

### Expected result
No NullPointerException

### Additional Info
I tried to skim through the EvoSuite code, and it looks like everything is checking out for the length of the LinkedList, but somehow things are going wrong inside Java where it steps off the end of the list causing a null pointer exception.  It seems unlikely, but my best guess is that the size of the list somehow rolled over the size of an int causing it to search in the wrong direction for the item.

On a different note, what was the reasoning for selecting a linked list to hold these counts?  Since you frequently update a specific node (theoretically more often than you insert nodes), it seems like an ArrayList would be more efficient.

(https://github.com/EvoSuite/evosuite/blob/master/runtime/src/main/java/org/evosuite/runtime/LoopCounter.java)

**Comment by gofraser** [comment]
Thanks! I have no idea what causes this NPE, so I am not sure what to do here.

I assume this happens deterministically so we could just ignore the counter? I've pushed a workaround to swallow the NPE, let me know if this works.

Good point about the LinkedList. I changed that as well. Thanks!

**Comment by gofraser** [comment]
This should be fixed in 03d254dcb655b97e9b2c33d620cfa6d86e7c2a2a. If it's not fixed, please let me know.
