### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot access statement due to wrong position 71, where total number of statements is 71

### ISSUE THREAD

**Issue by loren138** [EvoSuite/evosuite#144]
### Context
I'm running parts of Defects4J through EvoSuite.  I get this error on certain random seeds (but not on others).

### Steps to Reproduce
Run the command in the result log with the random seed.

The /new folder for the classpath can be found at: http://klingmandesign.com/Math45New.tgz or by compiling Math_45_Buggy from Defects4J.

### EvoSuite Arguments
Not EvoSuite used the seed: 1507853668679

java -jar /home/loren/pullTest/bertGithub/evosuite-1.0.5.jar -class org.apache.commons.math.linear.OpenMapRealMatrix -projectCP /home/loren/repos/d4jBugs/Math_45/version/new/ -Dtest_dir=/home/loren/repos/d4jBugs/Math_45/version/evosuite/ -Dsearch_budget=180 -Dassertion_timeout=300 -Dshow_progress=true -Djunit_check=false -Dvirtual_fs=false -Dsandbox_mode=OFF -Dfilter_assertions=false -Dassertions=false -Dtest_comments=false -mem 1500

### Current Result
[screen.log](https://github.com/EvoSuite/evosuite/files/1381105/screen.log)

### Expected result
No crash

PS Is the length of the random seed important?  I tried a fixed seed of 3347, and it ran, but I only got 2 tests out. One of my other runs which used a time-based seed (that I don't know) produced 25 tests.

**Comment by gofraser** [comment]
I tried reproducing this with version 1.0.5 and the current HEAD version, using your exact command line, classpath (using your zip file), and seed, but I don't get to see the error. This is an elusive bug that has been haunting us for a long time. Any help to reliably reproduce this would be helpful!

The value of the seed should not matter. You're just seeing the effects of a stochastic algorithm, and the result will be different for every seed. I agree that a difference of 25 to 2 seems really bad, I wonder if the run with 2 went down some bad search path leading to tests with timeouts, or similar.

**Comment by gofraser** [comment]
I believe a workaround for this was added in 4f7eaf96f0e8973f88a25c483eb2e5531343551a after the 1.0.5 release. I'll close this issue, but if it happens again please re-open.
