### ISSUE TITLE
Test suites not getting compiled in order to run

### ISSUE THREAD

**Issue by tussharalagh** [EvoSuite/evosuite#145]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
After the generation of test suites namely, OrdSetSimple_ESTest.java and OrdSetSimple_ESTest_scaffolding.java in the "evosuite-tests", i tried compiling them. The location screenshot is given below:
![classpathfortests](https://user-images.githubusercontent.com/16580847/31866380-a171599c-b74c-11e7-89a9-66672b09a33e.png)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. Both the evosuite and standalone.jar files were added to the classpaths and java is installed on the system.
2.  The class was prepared using the command mvn compile( it was generated in the class folder of the target)
3.  The class was executed using the command $EVOSUITE -class OrdSetSimple -projectCP target/classes
4. After the generation of test suites namely, OrdSetSimple_ESTest.java and OrdSetSimple_ESTest_scaffolding.java in the "evosuite-tests", i tried compiling them. so i ran the command javac evosuite-tests/*.java which produced errors.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
I ran the command, javac evosuite-tests/*.java
Then i got the following errors:
![compilation](https://user-images.githubusercontent.com/16580847/31866404-e9f4483c-b74c-11e7-974e-c722a1642a4c.png)

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
I am facing multiple errors while compiling the test suites.
This is the whole folder
![full folder](https://user-images.githubusercontent.com/16580847/31866525-d7c02f12-b74e-11e7-8945-c30f79ec2062.png)

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*
The evosuite tests should be compiled so i can run them and record the results.

### Additional info
*Please add any information of interest here below*

**Comment by sinaa** [comment]
Obviously you're missing dependencies in the classpath.

Can you put the classpath directly on the javac command and try again? For example:

    $EVOSUITE -cp "standalone.jar:target/classes:etc." -class OrdSetSimple -projectCP target/classes

**Comment by tussharalagh** [comment]
No the class is generated, i have to compile the test suites OrdSetSimple_ESTest.java and OrdSetSimple_ESTest_scaffolding.java so they can run on command line

**Comment by tussharalagh** [comment]
i specified the dependencies using export CLASSPATH=target/classes:evosuite-runtime-1.0.5.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar

**Comment by sinaa** [comment]
I can see that your evosuite-runtime jar doesn't match the file in your screenshot above.

**Comment by tussharalagh** [comment]
can you plz provide me a complete command to execute the test cases if you have understood my problem? i am new to this setup..thnx

**Comment by tussharalagh** [comment]
the command u talked about" $EVOSUITE -cp "standalone.jar:target/classes:etc." -class OrdSetSimple -projectCP target/classes" is the initial step in creating the test suites...i am asking about executing the test suites..the command u listed generates the test suites..but my problem is running the test suites..

**Comment by sinaa** [comment]
you can run:

    javac -cp "evosuite-standalone-runtime-1.0.5.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar" evosuite-tests/*.java

**Comment by tussharalagh** [comment]
I am still getting the same errors like in the screenshot above

**Comment by tussharalagh** [comment]
getting errors like this :`evosuite-tests/OrdSetSimple_ESTest.java:19: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(3405);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:19: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(3405);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:59: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(947);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:59: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(947);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:74: error: cannot find symbol
      OrdSetSimple ordSetSimple2 = ordSetSimple0.difference(ordSetSimple1);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:278: error: cannot find symbol
      OrdSetSimple ordSetSimple3 = ordSetSimple2.difference(ordSetSimple1);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:356: error: cannot find symbol
      OrdSetSimple ordSetSimple4 = ordSetSimple3.difference(ordSetSimple0);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:454: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(1557);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:454: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(1557);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:476: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(1557);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:476: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(1557);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:481: error: cannot find symbol
      OrdSetSimple ordSetSimple2 = ordSetSimple0.difference(ordSetSimple1);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:574: error: cannot find symbol
      OrdSetSimple ordSetSimple3 = ordSetSimple2.difference(ordSetSimple1);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:788: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(3391);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:788: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(3391);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:792: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(3391);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:792: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(3391);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:822: error: cannot find symbol
      OrdSetSimple ordSetSimple2 = ordSetSimple0.difference(ordSetSimple1);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:882: error: cannot find symbol
      OrdSetSimple ordSetSimple3 = new OrdSetSimple(3391);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:882: error: cannot find symbol
      OrdSetSimple ordSetSimple3 = new OrdSetSimple(3391);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:887: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(1324);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:887: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(1324);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:891: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(0);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:891: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(0);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:903: error: cannot find symbol
      OrdSetSimple ordSetSimple2 = ordSetSimple1.difference(ordSetSimple0);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:971: error: cannot find symbol
      OrdSetSimple ordSetSimple3 = ordSetSimple0.difference(ordSetSimple1);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:1006: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(1527);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:1006: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(1527);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:1040: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(4572);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:1040: error: cannot find symbol
      OrdSetSimple ordSetSimple0 = new OrdSetSimple(4572);
                                       ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
evosuite-tests/OrdSetSimple_ESTest.java:1062: error: cannot find symbol
      OrdSetSimple ordSetSimple1 = new OrdSetSimple(1442);
      ^
  symbol:   class OrdSetSimple
  location: class OrdSetSimple_ESTest
`

**Comment by tussharalagh** [comment]
this is my code..

`public class OrdSetSimple {

  private int _set_size;

  private int _set[];

  private int _last;





  public OrdSetSimple(int size) {

    int k;

  	_set_size=size;

    _set = new int[_set_size];

  	for(k=0; k<_set_size; k++)

	  	_set[k]=0;

    _last=-1;

  }



  private int make_a_free_slot(int val) {

  	int pos, i, j;



	  pos = binSearch(val);

  	if (pos >= 0)

	  	return -1;

  	for (i=0; i<=_last; i++) {

	  	if (_set[i] > val)

		  	break;

   	}



  	if ((i<=_last)||(_last==-1)) {

	  	for (j=_last; j>=i; j--)

		  	_set[j+1] = _set[j];

  		pos = i;

    } else {

		    pos = _last+1;

  	}

	  _last++;

  	return pos;

  }



  public void addElement(int n) {

  	int pos;

	  if (n<0) {

		  System.out.println("Addition of a negative integer impossible\n");

  		return;

	  }

  	if (_last+1>=_set_size) {

	  	System.out.print("Addition of " + n);

      System.out.println(" impossible since the array is already full");

		  System.out.println("The array is: " + toString());

  	} else {

		  pos = make_a_free_slot(n);

  		if (pos>=0)

	  		_set[pos]=n;

  	}

    return;

  }



  public int getSize() {

    return _last+1;

  }



  public int getElementAt(int i) {

  	if ((i<0)||(i>_last))

	  	return -1;

  	else

	  	return _set[i];

  }



  private int binSearch(int x) {

  	int i=0;

	  int j=_last-1;

  	int m=0;



  	if (_last==-1)

	  	return -1;



  	while(i<j) {

	  	m= (i+j)/2;

    	if (x>_set[m])

		  	i=m+1;

  		else

	  		j=m;

  	}

  	if (x == _set[i]) return i;

    else return -1;

  }



  public OrdSetSimple difference(OrdSetSimple s2) {

    OrdSetSimple s1 = this;

    int size1=s1.getSize();

    int size2=s2.getSize();



    OrdSetSimple set=new OrdSetSimple(size2);



    int k;



    for(k=0; k<size1; k++)

		if (s2.binSearch(s1.getElementAt(k)) < 0)

			set.addElement(s1.getElementAt(k));



    return set;

  }



  public String toString() {

  	int k = 0;

    String s="";



    for (k=0; k<=_last; k++)

  		s += _set[k] + " ";



    return s;

  }



}









 



`

**Comment by sinaa** [comment]
I edited my comment/command above, can you please try again?

As long as the dependencies are on the classpath, the compilation will work. In your code example above, the name of the evosuite runtime jar for example did not match the file that was in your directory.

Either way, I'm closing this issue since this is basic Java, and not an Evosuite bug. Please use stackoverflow if you need help with running the tool.

**Comment by tussharalagh** [comment]
Hi thnx for the command above, the reason is that the generated test suites are not getting executed..they have successfully combined but are not getting executed..it would be really helpful if u can help me to execute the test cases after successful compilation..i will be highly thankful..when i run the command java org.junit.runner.JUnitCore tutorial.Stack_ESTest..,, it says failed to find or load main class..

**Comment by tussharalagh** [comment]
This is what I am getting hp@ubuntu:~/Tutorial_Stack$ java -cp "target/classes:evosuite-standalone-runtime-1.0.5.jar:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar" OrdSetSimple_ESTest
Error: Could not find or load main class OrdSetSimple_ESTest

**Comment by sinaa** [comment]
you need to put `evosuite-tests` (where the tests are compiled) on the classpath again. The error you're getting is telling you what's missing :-)

**Comment by tussharalagh** [comment]
hp@ubuntu:~/Tutorial_Stack$ java -cp "target/classes:evosuite-standalone-runtime-1.0.5.jar:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar" evosuite-tests/OrdSetSimple_ESTest
Error: Could not find or load main class evosuite-tests.OrdSetSimple_ESTest

**Comment by tussharalagh** [comment]
No luck..getting the same error

**Comment by sinaa** [comment]
` java -cp "target/classes:evosuite-standalone-runtime-1.0.5.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar" OrdSetSimple_ESTest`

**Comment by tussharalagh** [comment]
I am getting this error after running the above command 
@ubuntu:~/Tutorial_Stack$ java -cp "target/classes:evosuite-standalone-runtime-1.0.5.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar" OrdSetSimple_ESTest
Error: Main method not found in class OrdSetSimple_ESTest, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application


is that it?

**Comment by sinaa** [comment]
you also need `org.junit.runner.JUnitCore` before the class name.

**Comment by tussharalagh** [comment]
Thanks a lot man!!!! this helped..i got the following output

@ubuntu:~/Tutorial_Stack$ java -cp "target/classes:evosuite-standalone-runtime-1.0.5.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore OrdSetSimple_ESTest
JUnit version 4.12
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
.Addition of a negative integer impossible

Addition of 2 impossible since the array is already full
The array is: 
Addition of 0 impossible since the array is already full
The array is: 
...Addition of 0 impossible since the array is already full
The array is: 
.Addition of a negative integer impossible

Addition of a negative integer impossible

..Addition of 1324 impossible since the array is already full
The array is: 
Addition of 0 impossible since the array is already full
The array is: 
.Addition of 754 impossible since the array is already full
The array is: 
Addition of a negative integer impossible

Addition of 1 impossible since the array is already full
The array is: 
Addition of 1 impossible since the array is already full
The array is: 
Addition of 1 impossible since the array is already full
The array is: 
Addition of 2 impossible since the array is already full
The array is: 
..Addition of 1 impossible since the array is already full
The array is: 
Addition of 1442 impossible since the array is already full
The array is: 
Addition of 4572 impossible since the array is already full
The array is: 
..Addition of 1276 impossible since the array is already full
The array is: 
Addition of 3405 impossible since the array is already full
The array is: 
Addition of 3405 impossible since the array is already full
The array is: 
Addition of 3 impossible since the array is already full
The array is: 
Addition of 947 impossible since the array is already full
The array is: 
.Addition of 1557 impossible since the array is already full
The array is: 
Addition of 23 impossible since the array is already full
The array is: 
Addition of 1557 impossible since the array is already full
The array is: 
Addition of 1557 impossible since the array is already full
The array is: 
Addition of 1557 impossible since the array is already full
The array is: 
Addition of 23 impossible since the array is already full
The array is: 
Addition of 1557 impossible since the array is already full
The array is: 
Addition of 1557 impossible since the array is already full
The array is: 
.Addition of 1557 impossible since the array is already full
The array is: 
Addition of 0 impossible since the array is already full
The array is: 
Addition of 1557 impossible since the array is already full
The array is: 
Addition of 1557 impossible since the array is already full
The array is: 
Addition of 1557 impossible since the array is already full
The array is: 
Addition of 0 impossible since the array is already full
The array is: 
.
Time: 2.013

OK (15 tests)

Thanks a lot bud..you r a lifesaver
