### ISSUE TITLE
EvoSuite BenchMark values for different arguments

### ISSUE THREAD

**Issue by mohanachelvi** [EvoSuite/evosuite#148]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

On running evosuite for a class, got exception saying search budget exceeded. Even after giving very high value on search budget not able to generate test  class. Is there any benchmark value available for search budget argument?

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. Ran Evosuite generate test with search budget  300 s and got an exception saying search budget exceeded
2. Increased the search budget value to 1000 s and still got an exception saying search budget exceeded.
3. I dont think, it is worth to keep on increasing the  search budget.
4. Is there any benchmark/threshold value upto which usually one  can try otherwise consider it as evosuite will not generate test case? Saw in  the  competition results pdf that 480 s was considered as max search budget. Can I consider this as  the benchmark value that can be used for search budget?
5. Usually get this scenario when trying to generate for a class which implements runnable or which has multiple annotations declared. For e.g. spring boot application.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
-DcutsFile=c:\temp\cutsFile.txt
-Dsearch_budget=300

where cutsFile.txt has the fully qualified name of the  class under test.

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
Getting exception search budget exceeded
 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*
Generate EvoSuite test class

### Additional info
*Please add any information of interest here below*

**Comment by sinaa** [comment]
Hi. What you're seeing is the _expected_ behaviour of Evosuite.

The tool will continue the test generation process until it fully covers all given criteria (e.g., achieves 100% coverage) or the search budget is exhausted.

The search budget you give to Evosuite depends often on the following:
- complexity of the classes you're testing
- the computation budget you have

Based on the previous publications with Evosuite, you're likely to get a reasonably high coverage by using 2-3 minutes as the search budget for classes with small/medium complexity, and ~10 minutes for more complex classes. Though this is not a general rule, and running a pilot experiment on your classes might give you a better insight.

In our experiments we've seen that while giving a much higher budget than what I've mentioned above can lead to an improvement in coverage, this improvement is fairly marginal and often not worth the extra computation cost.
