### ISSUE TITLE
Problem with generating tests in Windows with very long classpaths

### ISSUE THREAD

**Issue by alex-dressler** [EvoSuite/evosuite#15]
Hello everyone,

I am attempting to generate unit tests for a project with rather extreme amounts of dependencies. I'm using Ant to generate a classpath string and pass it to EvoSuite using -projectCP (no, this issue is not specific to Ant). It seems that if the size of the classpath is long enough, the test generation will fail, with the following error:

java.io.IOException: Cannot run program "C:\Program Files\Java\jdk1.8.0_71\jre\bin\java.exe": Create
Process error=206, The filename or extension is too long

With other projects with smaller classpaths, the test generation works perfectly. I believe that this issue is specific to Windows, because I executed the same command with the same project on Linux, and it ran without errors. It seems as if the only way to fix this is to shrink the classpath, so I tried using wildcards in the classpath to get rid of the repetition of "my/file/path/someJarFile.jar;my/file/path/someOtherJarFile.jar; ...". However, it doesn't look like EvoSuite supports wildcards in its classpath either through -projectCP or by setting it in the evosuite.properties file. Is there any workaround to this which I am missing?

-Alex

**Comment by arcuri82** [comment]
Hi,
  that is a common issue on Windows. In Maven, we automatically handle it. However, we do not directly support Ant (and likely not in any near feature, as nowadays most people use either Maven or Gradle). You can however play with some configurations. For example, you can try to write the classpath on disk to a file, and then use -DCP_file_path=<pathToThatFile> (that is actually what the Maven plugin does). At any rate, I guess we should update the documentation to discuss it

cheers

Andrea

**Comment by arcuri82** [comment]
nice, Github automatically remove what is inside <  > ...

it should had read `-DCP_file_path=<pathToThatFile>`

**Comment by alex-dressler** [comment]
Thanks for the prompt reply. Using the -DCP_file_path argument in place of -projectCP worked!

**Comment by arcuri82** [comment]
documentation has been updated at:

http://www.evosuite.org/documentation/commandline/
