### ISSUE TITLE
ERROR TestCluster - Failed to check cache for javax.swing.RowFilter<M, I>.ComparisonType : Type points to itself

### ISSUE THREAD

**Issue by shubhagrover94** [EvoSuite/evosuite#152]
I am doing a project on EvoSuite to generate tests and I am completely new to this. I tried to execute a class and getting this error at the first step. But the whole process runs just fine. And i get the results as follows and I am not sure if the error is affecting my overall result or not. Please comment your opinion.

ERROR TestCluster - Failed to check cache for javax.swing.RowFilter<M, I>.ComparisonType : Type points to itself
[Progress:=>                            6%] [Cov:>                              [Progress:=>                            6%] [Cov:=>                             [Progress:=>                            6%] [Cov:=====>                         [Progress:=>                            6%] [Cov:=========>                     [Progress:=>                            6%] [Cov:==========>                    [Progress:=>                            6%] [Cov:===========>                   [Progress:=>                            6%] [Cov:===========>                   [Progress:=>                            6%] [Cov:=============>                 [Progress:=>                            6%] [Cov:=============>                 [Progress:==>                           8%] [Cov:>                              [Progress:==>                           8%] [Cov:=>                             [Progress:==>                           8%] [Cov:=====>                         [Progress:==>                           8%] [Cov:=========>                     [Progress:==>                           8%] [Cov:==========>                    [Progress:==>                           8%] [Cov:===========>                   [Progress:====>                         15%] [Cov:>                             [Progress:====>                         15%] [Cov:=>                            [Progress:====>                         15%] [Cov:=====>                        [Progress:====>                         15%] [Cov:=========>                    [Progress:====>                         15%] [Cov:==========>                   [Progress:====>                         15%] [Cov:===========>                  [Progress:====>                         15%] [Cov:============>                 [Progress:====>                         15%] [Cov:==============>               [Progress:====>                         15%] [Cov:==============>               [Progress:====>                         16%] [Cov:>                             [Progress:====>                         16%] [Cov:=>                            [Progress:====>                         16%] [Cov:=====>                        [Progress:====>                         16%] [Cov:=========>                    [Progress:====>                         16%] [Cov:==========>                   [Progress:====>                         16%] [Cov:===========>                  [Progress:====>                         16%] [Cov:============>                 [Progress:====>                         16%] [Cov:=============>                [Progress:====>                         16%] [Cov:==============>               [Progress:=====>                        18%] [Cov:=>                            [Progress:=====>                        18%] [Cov:==>                           [Progress:=====>                        18%] [Cov:======>                       [Progress:=====>                        18%] [Cov:========>                     [Progress:=====>                        18%] [Cov:============>                 [Progress:=====>                        18%] [Cov:=============>                [Progress:=====>                        18%] [Cov:==============>               [Progress:=====>                        18%] [Cov:==============>               [Progress:======>                       20%] [Cov:===========>                  [Progress:======>                       20%] [Cov:==============>               [Progress:======>                       20%] [Cov:==============>               [Progress:======>                       20%] [Cov:==============>               [Progress:======>                       20%] [Cov:===============>              [Progress:======>                       21%] [Cov:===============>              [Progress:======>                       21%] [Cov:===============>              [Progress:======>                       23%] [Cov:===============>              [Progress:======>                       23%] [Cov:===============>              [Progress:======>                       23%] [Cov:===============>              [Progress:=======>                      25%] [Cov:===============>              [Progress:=======>                      25%] [Cov:===============>              [Progress:=======>                      26%] [Cov:===============>              [Progress:=======>                      26%] [Cov:===============>              [Progress:========>                     28%] [Cov:===============>              [Progress:========>                     28%] [Cov:===============>              [Progress:========>                     28%] [Cov:===============>              [Progress:========>                     28%] [Cov:===============>              [Progress:=========>                    30%] [Cov:===============>              [Progress:=========>                    30%] [Cov:===============>              [Progress:=========>                    30%] [Cov:===============>              [Progress:=========>                    30%] [Cov:===============>              [Progress:=========>                    31%] [Cov:===============>              [Progress:=========>                    31%] [Cov:===============>              [Progress:=========>                    31%] [Cov:===============>              [Progress:=========>                    31%] [Cov:===============>              [Progress:=========>                    33%] [Cov:===============>              [Progress:=========>                    33%] [Cov:===============>              [Progress:=========>                    33%] [Cov:===============>              [Progress:=========>                    33%] [Cov:===============>              [Progress:=========>                    33%] [Cov:===============>              [Progress:==========>                   35%] [Cov:===============>              [Progress:==========>                   35%] [Cov:===============>              [Progress:==========>                   35%] [Cov:===============>              [Progress:==========>                   35%] [Cov:===============>              [Progress:==========>                   36%] [Cov:===============>              [Progress:==========>                   36%] [Cov:===============>              [Progress:==========>                   36%] [Cov:===============>              [Progress:==========>                   36%] [Cov:===============>              [Progress:==========>                   36%] [Cov:===============>              [Progress:===========>                  38%] [Cov:===============>              [Progress:===========>                  38%] [Cov:===============>              [Progress:===========>                  38%] [Cov:===============>              [Progress:===========>                  38%] [Cov:===============>              [Progress:===========>                  38%] [Cov:===============>              [Progress:============>                 40%] [Cov:===============>              [Progress:============>                 40%] [Cov:===============>              [Progress:============>                 40%] [Cov:===============>              [Progress:============>                 40%] [Cov:===============>              [Progress:============>                 40%] [Cov:===============>              [Progress:============>                 41%] [Cov:===============>              [Progress:============>                 41%] [Cov:===============>              [Progress:============>                 41%] [Cov:===============>              [Progress:============>                 41%] [Cov:===============>              [Progress:============>                 41%] [Cov:===============>              [Progress:============>                 43%] [Cov:===============>              [Progress:============>                 43%] [Cov:===============>              [Progress:============>                 43%] [Cov:===============>              [Progress:============>                 43%] [Cov:===============>              [Progress:=============>                45%] [Cov:===============>              [Progress:=============>                45%] [Cov:===============>              [Progress:=============>                45%] [Cov:===============>              [Progress:=============>                45%] [Cov:===============>              [Progress:=============>                46%] [Cov:===============>              [Progress:=============>                46%] [Cov:===============>              [Progress:=============>                46%] [Cov:===============>              [Progress:=============>                46%] [Cov:===============>              [Progress:=============>                46%] [Cov:===============>              [Progress:==============>               48%] [Cov:===============>              [Progress:==============>               48%] [Cov:===============>              [Progress:==============>               48%] [Cov:===============>              [Progress:==============>               48%] [Cov:===============>              [Progress:==============>               48%] [Cov:===============>              [Progress:===============>              50%] [Cov:===============>              [Progress:===============>              50%] [Cov:===============>              [Progress:================>             55%] [Cov:===============>              [Progress:================>             55%] [Cov:===============>              [Progress:================>             55%] [Cov:===============>              [Progress:================>             55%] [Cov:===============>              [Progress:================>             55%] [Cov:===============>              [Progress:================>             56%] [Cov:===============>              [Progress:================>             56%] [Cov:===============>              [Progress:================>             56%] [Cov:===============>              [Progress:================>             56%] [Cov:===============>              [Progress:=================>            58%] [Cov:===============>              [Progress:=================>            58%] [Cov:===============>              [Progress:=================>            58%] [Cov:===============>              [Progress:=================>            58%] [Cov:===============>              [Progress:=================>            58%] [Cov:===============>              [Progress:==================>           60%] [Cov:===============>              [Progress:==================>           60%] [Cov:===============>              [Progress:==================>           60%] [Cov:===============>              [Progress:==================>           60%] [Cov:===============>              [Progress:==================>           60%] [Cov:===============>              [Progress:==================>           61%] [Cov:===============>              [Progress:==================>           61%] [Cov:===============>              [Progress:==================>           61%] [Cov:===============>              [Progress:==================>           61%] [Cov:===============>              [Progress:==================>           61%] [Cov:===============>              [Progress:==================>           61%] [Cov:===============>              [Progress:==================>           63%] [Cov:===============>              [Progress:==================>           63%] [Cov:===============>              [Progress:==================>           63%] [Cov:===============>              [Progress:==================>           63%] [Cov:===============>              [Progress:===================>          65%] [Cov:===============>              [Progress:===================>          65%] [Cov:===============>              [Progress:===================>          65%] [Cov:===============>              [Progress:===================>          65%] [Cov:===============>              [Progress:===================>          65%] [Cov:===============>              [Progress:===================>          66%] [Cov:===============>              [Progress:===================>          66%] [Cov:===============>              [Progress:===================>          66%] [Cov:===============>              [Progress:===================>          66%] [Cov:===============>              [Progress:===================>          66%] [Cov:===============>              [Progress:====================>         68%] [Cov:===============>              [Progress:====================>         68%] [Cov:===============>              [Progress:====================>         68%] [Cov:===============>              [Progress:====================>         68%] [Cov:===============>              [Progress:====================>         68%] [Cov:===============>              [Progress:=====================>        70%] [Cov:===============>              [Progress:=====================>        70%] [Cov:===============>              [Progress:=====================>        70%] [Cov:===============>              [Progress:=====================>        70%] [Cov:===============>              [Progress:=====================>        70%] [Cov:===============>              [Progress:=====================>        71%] [Cov:===============>              [Progress:=====================>        71%] [Cov:===============>              [Progress:=====================>        71%] [Cov:===============>              [Progress:=====================>        71%] [Cov:===============>              [Progress:=====================>        71%] [Cov:===============>              [Progress:=====================>        71%] [Cov:===============>              [Progress:=====================>        73%] [Cov:===============>              [Progress:=====================>        73%] [Cov:===============>              [Progress:=====================>        73%] [Cov:===============>              [Progress:=====================>        73%] [Cov:===============>              [Progress:=====================>        73%] [Cov:===============>              [Progress:======================>       75%] [Cov:===============>              [Progress:======================>       75%] [Cov:===============>              [Progress:======================>       75%] [Cov:===============>              [Progress:======================>       75%] [Cov:===============>              [Progress:======================>       75%] [Cov:===============>              [Progress:======================>       76%] [Cov:===============>              [Progress:======================>       76%] [Cov:===============>              [Progress:======================>       76%] [Cov:===============>              [Progress:======================>       76%] [Cov:===============>              [Progress:======================>       76%] [Cov:===============>              [Progress:======================>       76%] [Cov:===============>              [Progress:=======================>      78%] [Cov:===============>              [Progress:=======================>      78%] [Cov:===============>              [Progress:=======================>      78%] [Cov:===============>              [Progress:=======================>      78%] [Cov:===============>              [Progress:=======================>      78%] [Cov:===============>              [Progress:========================>     80%] [Cov:===============>              [Progress:========================>     80%] [Cov:===============>              [Progress:========================>     80%] [Cov:===============>              [Progress:========================>     80%] [Cov:===============>              [Progress:========================>     80%] [Cov:===============>              [Progress:========================>     80%] [Cov:===============>              [Progress:========================>     81%] [Cov:===============>              [Progress:========================>     81%] [Cov:===============>              [Progress:========================>     81%] [Cov:===============>              [Progress:========================>     81%] [Cov:===============>              [Progress:========================>     81%] [Cov:===============>              [Progress:========================>     81%] [Cov:===============>              [Progress:========================>     83%] [Cov:===============>              [Progress:========================>     83%] [Cov:===============>              [Progress:========================>     83%] [Cov:===============>              [Progress:========================>     83%] [Cov:===============>              [Progress:========================>     83%] [Cov:===============>              [Progress:=========================>    85%] [Cov:===============>              [Progress:=========================>    85%] [Cov:===============>              [Progress:=========================>    85%] [Cov:===============>              [Progress:=========================>    85%] [Cov:===============>              [Progress:=========================>    85%] [Cov:===============>              [Progress:=========================>    85%] [Cov:===============>              [Progress:=========================>    86%] [Cov:===============>              [Progress:=========================>    86%] [Cov:===============>              [Progress:=========================>    86%] [Cov:===============>              [Progress:=========================>    86%] [Cov:===============>              [Progress:==========================>   88%] [Cov:===============>              [Progress:==========================>   88%] [Cov:===============>              [Progress:==========================>   88%] [Cov:===============>              [Progress:==========================>   88%] [Cov:===============>              [Progress:==========================>   88%] [Cov:===============>              [Progress:==========================>   88%] [Cov:===============>              [Progress:===========================>  90%] [Cov:===============>              [Progress:===========================>  90%] [Cov:===============>              [Progress:===========================>  90%] [Cov:===============>              [Progress:===========================>  90%] [Cov:===============>              [Progress:===========================>  90%] [Cov:===============>              [Progress:===========================>  91%] [Cov:===============>              [Progress:===========================>  91%] [Cov:===============>              [Progress:===========================>  91%] [Cov:===============>              [Progress:===========================>  91%] [Cov:===============>              [Progress:===========================>  91%] [Cov:===============>              [Progress:===========================>  91%] [Cov:===============>              [Progress:===========================>  91%] [Cov:===============>              [Progress:===========================>  93%] [Cov:===============>              [Progress:===========================>  93%] [Cov:===============>              [Progress:===========================>  93%] [Cov:===============>              [Progress:===========================>  93%] [Cov:===============>              [Progress:============================> 95%] [Cov:===============>              [Progress:============================> 95%] [Cov:===============>              [Progress:============================> 95%] [Cov:===============>              [Progress:============================> 95%] [Cov:===============>              [Progress:============================> 95%] [Cov:===============>              [Progress:============================> 95%] [Cov:===============>              [Progress:============================> 96%] [Cov:===============>              [Progress:============================> 96%] [Cov:===============>              [Progress:============================> 96%] [Cov:===============>              [Progress:============================> 96%] [Cov:===============>              [Progress:============================> 96%] [Cov:===============>              [Progress:============================> 96%] [Cov:===============>              [Progress:=============================>98%] [Cov:===============>              [Progress:=============================>98%] [Cov:===============>              [Progress:=============================>98%] [Cov:===============>              [Progress:=============================>98%] [Cov:===============>              [Progress:=============================>98%] [Cov:===============>              [Progress:=============================>98%] [Cov:===============>              [Progress:==============================100%] [Cov:===============>             [Progress:==============================100%] [Cov:===============>             [Progress:==============================100%] [Cov:===============>             [Progress:==============================100%] [Cov:===============>             [Progress:==============================100%] [Cov:===============>             [Progress:==============================100%] [Cov:===============>             [Progress:==============================100%] [Cov:===============>             [Progress:==============================100%] [Cov:================>                  46%]
* Search finished after 61s and 177 generations, 25957 statements, best individual has fitness: 64.57927170868346
* Minimizing test suite
* Going to analyze the coverage criteria
* Coverage analysis for criterion LINE
* Coverage of criterion LINE: 32%
* Total number of goals: 50
* Number of covered goals: 16
* Coverage analysis for criterion BRANCH
* Coverage of criterion BRANCH: 33%
* Total number of goals: 9
* Number of covered goals: 3
* Coverage analysis for criterion EXCEPTION
* Coverage of criterion EXCEPTION: 100%
* Total number of goals: 3
* Number of covered goals: 3
* Coverage analysis for criterion WEAKMUTATION
* Coverage of criterion WEAKMUTATION: 37%
* Total number of goals: 51
* Number of covered goals: 19
* Coverage analysis for criterion OUTPUT
* Coverage of criterion OUTPUT: 100% (no goals)
* Coverage analysis for criterion METHOD
* Coverage of criterion METHOD: 67%
* Total number of goals: 3
* Number of covered goals: 2
* Coverage analysis for criterion METHODNOEXCEPTION
* Coverage of criterion METHODNOEXCEPTION: 0%
* Total number of goals: 3
* Number of covered goals: 0
* Coverage analysis for criterion CBRANCH
* Coverage of criterion CBRANCH: 33%
* Total number of goals: 9
* Number of covered goals: 3
* Generated 5 tests with total length 14
* Resulting test suite's coverage: 46% (average coverage for all fitness functions)
* Generating assertions
* Resulting test suite's mutation score: 0%
* Compiling and checking tests
* Writing JUnit test case 'ATMMain_ESTest' to evosuite-tests
* Done!

* Computation finished

**Comment by gofraser** [comment]
I don't think this is anything to worry about. This "XY refers to itself" is just when EvoSuite's analysis hits a recursion when trying to resolve type parameters (e.g., Foo<T extends Foo<T>> or whatnot). This should not affect coverage - the low coverage in your example will have other reasons.
