### ISSUE TITLE
Many properties in Properties.java are marked as Constant in javadoc - What is the Rationale?

### ISSUE THREAD

**Issue by VigneswaranR** [EvoSuite/evosuite#153]
### Context
Many properties in Properties.java are marked as Constant in its javadoc. Does it mean we dont need to alter its value when generating test case using EvoSuite?

For instance,

/** Constant <code>INSERTION_SCORE_OBJECT=1</code> */
@Parameter(key = "insertion_score_object", group = "Test Creation", description = "Score for selection of insertion of call on existing object")
	public static int INSERTION_SCORE_OBJECT = 1;

Does it mean we don't need to change the value of 'insertion_score_object' by passing as configuration parameter when running EvoSuite test generation?

If yes, then we can atleast ignore those constant properties and concentrate on other properties to tune the parameters in order to generate a optimized test case.  Please confirm.

**Comment by gofraser** [comment]
Thanks for pointing this out. These comments were auto-generated by a Maven plugin some years ago and never cleaned up successively. I'll try to clean this up - best ignore them for now.

**Comment by gofraser** [comment]
The misleading JavaDoc comments are now gone (45ed604b4aaba8c9157d43b3c0d7ed538473e5df)
