### ISSUE TITLE
Help to share the arguments that are used to run evosuite in competition

### ISSUE THREAD

**Issue by mohanachelvi** [EvoSuite/evosuite#154]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

We are in the process of generating test case for our project and we wanted to try with the arguments that evosuite has used in the competition. Kindly help to share the same, which helps us a lot in deciding the best argument combination.

Currently we are utilizing or playing around only with private, functional mocking, assertion strategy and search budget related arguments.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.
2.
3.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by mohanachelvi** [comment]
Got the data from SF100 and SF110 evosuite setup file attachment from evosuite.org.

**Comment by gofraser** [comment]
Note that the setup files in the SF100/110 repos are not the same ones as used in the competitions. Let me know if you need to know the exact competition configuration.
