### ISSUE TITLE
Feature request:  Method-level code generation configuration parameter.

### ISSUE THREAD

**Issue by JavaJimFl** [EvoSuite/evosuite#155]
I work on a legacy application that uses a lot of static calls to wrap database queries.  Were EvoSuite to generate tests for classes that use these classes, they would in effect be integration tests because EvoSuite uses Mockito, which can't mock static methods (#50).

That said, a lot of these classes implement interfaces or abstract methods where EvoSuite would be useful (data binding comes to mind).  I'd like you all to consider a feature request where I could configure a test generation run to act on only certain methods in a CUT list.

**Comment by gofraser** [comment]
In theory there is -Dtarget_method=<method name> and -Dtarget_method_list=method1:method2:...

However, these would need some testing - it is likely they haven't been maintained for a while now. Can you try this out, and if (as I assume) this doesn't work, we'll change this issue from "feature request" to "bug"...

Note also that, in theory, targeting individual methods may lead to lower coverage, if, for example, a target method depends on an object state achieved by other methods.

**Comment by JavaJimFl** [comment]
Ahh, I don't recall seeing that parameter.  Thanks for pointing that out.  I will give it a try.

Thanks for replying so quickly!

**Comment by gofraser** [comment]
In case this is broken, can you please let us know?

**Comment by JavaJimFl** [comment]
I will.   Sorry, I haven't been able to get back to this task.   Hopefully, I can circle back to this closer to the end of the year.

**Comment by gofraser** [comment]
The `target_method` parameter should work for all coverage criteria at least from 73284a7732fcc2d3561e9e25714f33d6a411ba84 on, so I'm going to close this issue.
