### ISSUE TITLE
Completed 18 tests with total length 53? Meaning?

### ISSUE THREAD

**Issue by singham999** [EvoSuite/evosuite#158]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
What is the meaning of this line "Completed 18 tests with total length 53"?  is it the test suite length?
![coverageforordsetsimple 1](https://user-images.githubusercontent.com/34329025/33699202-b06edec2-dadf-11e7-9624-0f2b7fa7a63f.png)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.
2.
3.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by gofraser** [comment]
Yes, 53 is the total number of statements in the 18 tests (not including assertions). If you have any suggestions on how to make this more obvious, please do let us know.

**Comment by singham999** [comment]
Thank You for the reply, sir

So can we term this as **test suite length**?

Also can you please provide me a way to check pre and post conditions of evosuite?

Thanks

**Comment by gofraser** [comment]
Yes, this would be the test suite length. I don't think "test suite length" is a well defined term - I think "total number of statements" seems appropriate. But if there is a reason to change this, please let me know.

I don't know what pre and post conditions of EvoSuite you are referring to.

**Comment by singham999** [comment]
hi, i mean to say that Evosuite is supposed to produce pre and post conditions for the methods it tests. How can we possibly know them? for eg. i need to compare the pre and post conditions of a method..so i can tell if its correct or not?
