### ISSUE TITLE
How to know the pre and post conditions of evosuite?

### ISSUE THREAD

**Issue by singham999** [EvoSuite/evosuite#159]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.
2.
3.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by gofraser** [comment]
I am sorry, I am not sure what the question really is. Is there an issue that needs resolving?

**Comment by singham999** [comment]
hi, i mean to say that Evosuite is supposed to produce pre and post conditions for the methods it tests. How can we possibly know them? for eg. i need to compare the pre and post conditions of a method..so i can tell if its correct or not?

**Comment by gofraser** [comment]
I think what you are asking is how EvoSuite finds bugs? EvoSuite generates regression assertions. That is, it generates assertions that capture the current behaviour of the class under test. You can either manually inspect these, and if they don't reflect your expectation, then you have found a bug. Or, you keep them as they are, and use them for regression testing (i.e., you run the tests later, after changing the software, and then any failure shows regressions).
