### ISSUE TITLE
Client state is not set to "SEARCH" after "INITIALIZATION".

### ISSUE THREAD

**Issue by Mozhan** [EvoSuite/evosuite#160]
### Context
In `TestSuiteGenerator.java`, in `generateTestSuite()`, after the client state is set to `ClientState.INITIALIZATION`, it is not updated to `ClientState.SEARCH` when the search phase starts.

Therefore, if search takes longer than _120 seconds_, which is the default time budget for initialization,  `TimeController.java` may issue a warning, stating that initialization last too long.

### Steps to Reproduce
Running EvoSuite on a case that takes longer than 2 minutes should probably trigger this warning.

### Fix Suggestion
Before the call to `generateTests()`, the client state could be updated as: `ClientServices.getInstance().getClientNode().changeState(ClientState.SEARCH);`

**Comment by gofraser** [comment]
I tried reproducing this on a simple class with 3min search budget, but don't see what you mean. In generateTests() there is a call to change the state to ClientState.SEARCH immediately before invoking the search. Do you have a concrete example how I can reproduce this problem?

**Comment by Mozhan** [comment]
My apologies for my late response in this thread.

Previously, I assumed the state should be set to _ClientState.SEARCH_ inside _generateTestSuite()_ in _TestSuiteGenerator_.
I see that indeed the state is set in generateTests() when using _WholeTestSuiteStratey_.  However, I think this is still missing in generateTests() in _IndividualTestStrategy_ and _EntBugTestStrategy_ .

Meanwhile I try to find a concrete example I used at the time.

**Comment by gofraser** [comment]
I see what you mean for IndividualTestStrategy and EntBugTestStrategy. Unfortunately, we'll have to fix #180 first before we can test a fix here.

**Comment by gofraser** [comment]
I believe this issue was fixed in b28334f28858469d8c8ae291b55737b0ebc91f66. Please re-open the issue in case that fix was incomplete.
