### ISSUE TITLE
IllegalArgumentException: Cannot access statement due to wrong position <num> where total number of statements is <num>

### ISSUE THREAD

**Issue by eran505** [EvoSuite/evosuite#163]
**Context**
I'm running EvoSuite 1.0.5 on  Apache Commons Math 3.5, on Linear Package.
When i looked at the output i noticed that EvoSuite generated a failing tests on "ArrayRealVector", EvoSuite is a mainly for Regression so i dont understand how i got a failing Assertion.
As i tried to reproduced the failing test, Evosuite didn't generate any test for this class in 9 out of 10 trials,  i always got the following exception:
IllegalArgumentException: Cannot access statement due to wrong position <num> where total number of statements is <num>
   
**One more thing i used different seeds, so if dont think the problem is in the seed 

I have two questions:
1. why did EvoSuite generated a failing test
2. why some test get this exception, and how to fix it
[output.txt](https://github.com/EvoSuite/evosuite/files/1579828/output.txt)

[ArrayRealVector.zip](https://github.com/EvoSuite/evosuite/files/1579831/ArrayRealVector.zip)

i added the failing test made by EvoSuite, and the exception outputs 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

Evosutie 1.0.5 jar and  Apache Commons Math 3.5 , with the class prefix org.apache.commons.math3.linear.ArrayRealVector

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
command: 
java -jar evosuite-1.0.5.jar -class org.apache.commons.math3.linear.ArrayRealVector -projectCP /eran/repo/common_math/commons-math3-3.5-src/target/classes -seed 65533 -Dsearch_budget=120 -Dshow_progress=false -Dtest_comments=false -Dconfiguration_id=65533 Doutput_variables=TARGET_CLASS,criterion,configuration_id,Total_Branches,Covered_Branches,Size,Length,Total_Time,Covered_Goals,Total_Goals,Coverage,search_budget

Thanks Eran

**Comment by gofraser** [comment]
I believe a workaround for this was added in 4f7eaf96f0e8973f88a25c483eb2e5531343551a after the 1.0.5 release. I'll close this issue, but if it happens again please re-open.
