### ISSUE TITLE
Maven downloads not available

### ISSUE THREAD

**Issue by kmartin5223** [EvoSuite/evosuite#168]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
After pulling down the Jenkins plugin and running the batch script, maven is unable to pull jar files since website is down.  Any timeframe on when it will be back up?

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.
2.
3.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by gofraser** [comment]
Hopefully the website will be up by the weekend, but bureaucracy might delay things until next week.

**Comment by gofraser** [comment]
Website is up again.
