### ISSUE TITLE
Maven and Jacoco

### ISSUE THREAD

**Issue by kpepper** [EvoSuite/evosuite#172]
Just a couple of questions:

1) Are the Maven plugins up to date with latest GitHub master changes? If not is there an update planned?
2) Can Evosuite be used with Jacoco yet?

Thanks.

**Comment by gofraser** [comment]
Jacoco can be used (1) with offline instrumentation (which creates instrumented versions of the class files) or (2) with a javaagent that instruments on the fly. 

(1) If you use the javaagent version, then this works fine if you use -Duse_separate_classloader=false  when generating tests (the default is true). The use of the separate classloader will lead to 0% coverage being reported by Jacoco. In the generated tests you can change this in the @EvoRunnerParameters options by setting separateClassLoader = false. 

(2) If you use Jacoco offline instrumentation then this works fine either way, regardless of the classloader setting.

However, note that we recently committed some fixes related to Jacoco (and other coverage tools) so I think (but haven't verified) that at this point released version 1.0.5 will only work with solution (1). The current version in the repo should work with both configurations. A new release 1.0.6 will follow after we've fixed a couple of known bugs, so hopefully soon-ish.

**Comment by kpepper** [comment]
Thanks for the info. 
1) Are you planning on updating the Maven plugins? 
2) Do you have any feeling as to the 1.0.6 release date?

**Comment by gofraser** [comment]
The maven plugins will be updated with the 1.0.6 release. I don't know the date, but it should be within the next few weeks.

**Comment by kpepper** [comment]
Okay, thanks. I'm just about to start converting an existing ant build process to Gradle so the Maven plugins would be really handy.

**Comment by gofraser** [comment]
1.0.6 has been released, and this should be fixed - when following the instructions: http://www.evosuite.org/documentation/measuring-code-coverage/
