### ISSUE TITLE
failed to add serialID

### ISSUE THREAD

**Issue by Anouartech** [EvoSuite/evosuite#173]
### Context
Hi, I am beginner with Evosuite and I want to test his capabilities in  test generation I have a small project (is multi agent system (jade platform) developed under Java )
when I run the evosuite I got this error
### Current Result
![screenshot 2](https://user-images.githubusercontent.com/36560709/36340586-cb81672c-13e0-11e8-865b-c40f19f0feca.png)

**Comment by gofraser** [comment]
It's a bit difficult to say from the screenshot. The most likely explanation would be that the class jade.core.Agent isn't on the classpath that you specified using -projectCP. Is it? If it is, then could you please point me to the project you are testing, and the exact command line you are using?

**Comment by Anouartech** [comment]
the command was 
java -jar evosuite-1.0.5.jar -class examples.behaviours.SimpleAgent -projectCP /home/aktech/workspace/WS_Eclipse_Kepler/jadeexp/bin
and jade.core.Agent is class defined within Jar file in project library

**Comment by Anouartech** [comment]
yes,the problem was about messing jade classes in bin directory; I compiled the jade code and I added the result classes to bin directory ; now  it works fine . thanks for your help

**Comment by gofraser** [comment]
Thanks, closing this issue.
