### ISSUE TITLE
Getting MockitoException while running all tests simultaneously.

### ISSUE THREAD

**Issue by Saroj2Kumar** [EvoSuite/evosuite#176]
I have integrated evosuite with gradle project and able to create all test cases. I am able to run individual test-class but while running all test-cases I am getting "MockitoException", exception is as below : 

**org.evosuite.shaded.org.mockito.exceptions.base.MockitoException: 
ClassCastException occurred while creating the mockito proxy :
  class to mock : 'zat.co.group.bas.service.AuthServiceDB', loaded by classloader : 'org.evosuite.runtime.instrumentation.EvoClassLoader@2890c451'
  created class : 'zat.co.group.bas.service.AuthServiceDB$$EnhancerByMockitoWithCGLIB$$3cfe3d6', loaded by classloader : 'org.evosuite.shaded.org.mockito.internal.creation.util.SearchingClassLoader@69d6a7cd'
  proxy instance class : 'zat.co.group.bas.service.AuthServiceDB$$EnhancerByMockitoWithCGLIB$$3cfe3d6', loaded by classloader : 'org.evosuite.shaded.org.mockito.internal.creation.util.SearchingClassLoader@ec2bf82'
  instance creation by : ObjenesisInstantiator

You might experience classloading issues, disabling the Objenesis cache *might* help (see MockitoConfiguration)**

Kindly see this issue, and suggest me anything needs to change or configure.

**Comment by gofraser** [comment]
Can you please confirm whether this issue persists in version 1.0.6? We have fixed a number of issues with Mockito recently.

**Comment by gofraser** [comment]
This seems to be the problem fixed in dd311ab35cbc4dcef2d3e7d8ac6745595c99340a. Unless you can confirm that it still happens with 1.0.6 I will consider this resolved.

**Comment by gofraser** [comment]
I'm closing this issue since it seems to be fixed with dd311ab, and I haven't heard any objections.

**Comment by mdev111** [comment]
it still happens with 1.0.6
but I'm using mvn.
![image](https://user-images.githubusercontent.com/37219024/48980062-8cb92400-f0c4-11e8-891a-34a4cea178e6.png)
