### ISSUE TITLE
Java 9 compatibility: System classloader is no longer a URLClassLoader

### ISSUE THREAD

**Issue by gofraser** [EvoSuite/evosuite#183]
When using a Java Agent (e.g. for the compile check at the end of test generation), EvoSuite uses the `org.evosuite.ClassPathHacker` class to add the `tools.jar` to the classpath using the common assumption that the system classloader is a URLClassLoader:

`URLClassLoader sysloader = (URLClassLoader) ClassLoader.getSystemClassLoader();`

This, however, is only true up to Java 8. With Java 9, the system classloader is no longer a URLClassLoader, and this code results in a ClassCastException. This is a known problem also for other projects, e.g. see https://stackoverflow.com/questions/48041764/add-jar-to-classpath-at-runtime-under-java-9

We either need a different way to add tools.jar to the classpath, or find a way to use a different classloader...or find a way not to depend on tools.jar.

**Comment by kpepper** [comment]
tools.jar has been completely removed as of Java 9.

**Comment by jose** [comment]
@VoglSebastian, does your [Java9 pull request](https://github.com/EvoSuite/evosuite/pull/267) address this issue?

**Comment by gofraser** [comment]
Actually it should, yes -- it should now be possible to run EvoSuite on Java 9+. It's not possible to *compile* EvoSuite with Java 9+ yet though, that's what #269 is for. I'll close this issue though.
