### ISSUE TITLE
TestTestSuiteMinimizer fails when enabling defuse criterion

### ISSUE THREAD

**Issue by mjkim720** [EvoSuite/evosuite#189]
This is a follow-up issue after Issue  https://github.com/EvoSuite/evosuite/issues/188  is closed.
 
Now, ```DefUseAnalysisSystemTest``` doesn't crash. But, after enabling ```Criterion.DEFUSE``` by default in ```Properties.java```, ```TestTestSuiteMinimizer``` fails and I can't package the snapshot with ```mvn package```.

The stack trace looks like below:
```
ERROR org.evosuite.TestGenerationContext - null
java.lang.NullPointerException: null
	at org.evosuite.setup.TestClusterGenerator.generateCluster(TestClusterGenerator.java:108) ~[classes/:na]
	at org.evosuite.TestGenerationContext.resetContext(TestGenerationContext.java:223) ~[classes/:na]
	at org.evosuite.testsuite.TestTestSuiteMinimizer.setUp(TestTestSuiteMinimizer.java:70) [test-classes/:na]
  invocations: 16 took 6ms (0) found 1 pairs
  invocations: 2 took 0ms (0) found 0 pairs
ERROR org.evosuite.TestGenerationContext - null
java.lang.NullPointerException: null
	at org.evosuite.setup.TestClusterGenerator.generateCluster(TestClusterGenerator.java:108) ~[classes/:na]
	at org.evosuite.TestGenerationContext.resetContext(TestGenerationContext.java:223) ~[classes/:na]
	at org.evosuite.testsuite.TestTestSuiteMinimizer.tearDown(TestTestSuiteMinimizer.java:81) [test-classes/:na]
```

I need to run the packaged jar file with defuse criterion, so enabled defuse   in ```Properties.java``` like below and ran ```mvn package```:
```
    @Parameter(key = "criterion", group = "Runtime", description = "Coverage criterion. Can define more than one criterion by using a ':' separated list")
    public static Criterion[] CRITERION = new Criterion[] {
            //these are basic criteria that should be always on by default
            Criterion.LINE, Criterion.BRANCH, Criterion.EXCEPTION, Criterion.WEAKMUTATION, Criterion.OUTPUT, Criterion.METHOD, Criterion.METHODNOEXCEPTION, Criterion.CBRANCH,
			Criterion.DEFUSE}; 
```

**Comment by gofraser** [comment]
The way the class TestTestSuiteMinimizer is written makes it incompatible with DefUse coverage. The proper way to fix this will be to rewrite these tests. Until that happens, you can use `-DskipTests` if you want to build a jar file even with failing tests.

**Comment by jose** [comment]
Btw, you don't need to explicitly change the `Properties.java` file to enable any other criterion, you can use the `-Dcriterion=...` parameter. For example, to run EvoSuite with all default criteria and `DefUse`

```
-Dcriterion=LINE:BRANCH:EXCEPTION:WEAKMUTATION:OUTPUT:METHOD:METHODNOEXCEPTION:CBRANCH:DEFUSE
```
