### ISSUE TITLE
-measureCoverage returns incorrect coverage values with Test Suites generated by EvoSuite

### ISSUE THREAD

**Issue by jgaleotti** [EvoSuite/evosuite#19]
The ``-measureCoverage`` option does not return correct values when using test suites generated by EvoSuite. 
For example, given the following class:
```
package code;

public class Foo {
	public Foo() {
	}
	public boolean testMe(int x) {
		if (x == 0) {
			return true;
		} else {
			return false;
		}
	}
} 
```
EvoSuite returns the following coverage values:

```
* Coverage analysis for criterion LINE
* Coverage of criterion LINE: 100%
* Total number of goals: 4
* Number of covered goals: 4
* Coverage analysis for criterion BRANCH
* Coverage of criterion BRANCH: 100%
* Total number of goals: 3
* Number of covered goals: 3
* Coverage analysis for criterion EXCEPTION
* Coverage of criterion EXCEPTION: 100% (no goals)
* Coverage analysis for criterion WEAKMUTATION
* Coverage of criterion WEAKMUTATION: 100%
* Total number of goals: 8
* Number of covered goals: 8
* Coverage analysis for criterion OUTPUT
* Coverage of criterion OUTPUT: 100%
* Total number of goals: 2
* Number of covered goals: 2
* Coverage analysis for criterion METHOD
* Coverage of criterion METHOD: 100%
* Total number of goals: 2
* Number of covered goals: 2
* Coverage analysis for criterion METHODNOEXCEPTION
* Coverage of criterion METHODNOEXCEPTION: 100%
* Total number of goals: 2
* Number of covered goals: 2
* Coverage analysis for criterion CBRANCH
* Coverage of criterion CBRANCH: 100%
* Total number of goals: 3
* Number of covered goals: 3
* Generated 3 tests with total length 6
* Resulting test suite's coverage: 100% (average coverage for all fitness functions)
```

But then, if the generated test suite is used with the ```-measureCoverage```option, almost no coverage is reported:
```
* Executing test(s)
  Executing Foo_ESTest
* Number of test cases to execute: 3
[MASTER] 16:04:34.786 [logback-1] WARN  Sandbox - Sandbox can be initalized only once
* Started: ClassName: code.Foo_ESTest, MethodName: test2
* Finished: ClassName: code.Foo_ESTest, MethodName: test2
* Started: ClassName: code.Foo_ESTest, MethodName: test0
* Finished: ClassName: code.Foo_ESTest, MethodName: test0
* Started: ClassName: code.Foo_ESTest, MethodName: test1
* Finished: ClassName: code.Foo_ESTest, MethodName: test1
* Number of test cases to executed: 3
* Executed 3 unit test(s)
* Target class code.Foo
* Coverage of criterion LINE: 0%
* Number of covered goals: 0 / 4
* Coverage of criterion BRANCH: 0%
* Number of covered goals: 0 / 3
* Coverage of criterion EXCEPTION: 100% (no goals)
* Coverage of criterion WEAKMUTATION: 0%
* Number of covered goals: 0 / 8
* Coverage of criterion OUTPUT: 0%
* Number of covered goals: 0 / 2
* Coverage of criterion METHOD: 0%
* Number of covered goals: 0 / 2
* Coverage of criterion METHODNOEXCEPTION: 0%
* Number of covered goals: 0 / 2
* Coverage of criterion CBRANCH: 0%
* Number of covered goals: 0 / 3
* Total number of covered goals: 0 / 24
* Total coverage: 0%
```

**Comment by jose** [comment]
thanks @jgaleotti for reporting this issue.
it seems to be a classloader issue. I added a (failing) test case (3f76e62a73d3cc9ad88bec5a58931d3247739136) to investigate this issue.

**Comment by gofraser** [comment]
The problem is that the EvoRunner parameter "useSeparateClassloader" is now set to true by default, and then -measureCoverage uses a different classloader than the tests. I have pushed a fix/hack for this which makes Jose's test pass. Can you confirm it solves the problem?

**Comment by jgaleotti** [comment]
It works fine now. Thanks!

**Comment by LeandroMoura3** [comment]
I have same problem here.

This is the EvoSuite gen:
* Going to analyze the coverage criteria
* Coverage analysis for criterion LINE
* Coverage of criterion LINE: 100%
* Total number of goals: 33
* Number of covered goals: 33
* Coverage analysis for criterion BRANCH
* Coverage of criterion BRANCH: 100%
* Total number of goals: 21
* Number of covered goals: 21
* Coverage analysis for criterion EXCEPTION
* Coverage of criterion EXCEPTION: 100%
* Total number of goals: 9
* Number of covered goals: 9
* Coverage analysis for criterion WEAKMUTATION
* Coverage of criterion WEAKMUTATION: 95%
* Total number of goals: 58
* Number of covered goals: 55
* Coverage analysis for criterion OUTPUT
* Coverage of criterion OUTPUT: 100%
* Total number of goals: 9
* Number of covered goals: 9
* Coverage analysis for criterion METHOD
* Coverage of criterion METHOD: 100%
* Total number of goals: 6
* Number of covered goals: 6
* Coverage analysis for criterion METHODNOEXCEPTION
* Coverage of criterion METHODNOEXCEPTION: 100%
* Total number of goals: 6
* Number of covered goals: 6
* Coverage analysis for criterion CBRANCH
* Coverage of criterion CBRANCH: 100%
* Total number of goals: 21
* Number of covered goals: 21

This is the measureCoverage:
* Coverage of criterion LINE: 100%
* Number of covered goals: 33 / 33
* Coverage of criterion BRANCH: 95%
* Number of covered goals: 20 / 21
* Coverage of criterion EXCEPTION: 100% (no goals)
* Coverage of criterion WEAKMUTATION: 89%
* Number of covered goals: 54 / 61
* Coverage of criterion OUTPUT: 0%
* Number of covered goals: 0 / 9
* Coverage of criterion METHOD: 0%
* Number of covered goals: 0 / 6
* Coverage of criterion METHODNOEXCEPTION: 0%
* Number of covered goals: 0 / 6
* Coverage of criterion CBRANCH: 95%
* Number of covered goals: 20 / 21
* Total number of covered goals: 127 / 157
* Total coverage: 81%

I am using evosuite-1.1.0 on win10.
