### ISSUE TITLE
ConstantPoolProblem

### ISSUE THREAD

**Issue by PragueSquare** [EvoSuite/evosuite#192]
Hello, could you please tell me which classes or packages in the program call the classes about constant pools in the package "seeding" ? In other words, which packages or classes contain the operations that extract constants in the program to the constant pools ?

**Comment by gofraser** [comment]
I suggest you look at the classes invoking `org.evosuite.seeding.ConstantPoolManager.getInstance()`. The constant pool is populated by the `PrimitivePoolMethodAdapter`, which adds constants from the bytecode to the constant pool. In addition, the helper classes in `org.evosuite.instrumentation.testability` (e.g. `StringHelper`) dynamically update the constant pool. For example, if you execute a condition `if(foo.equals(bar))` where `foo` and `bar` are Strings, then `foo` and `bar` will be added to the constant pool. The values of the constant pool are used in the various `PrimitiveStatement` subclasses when mutating/initialising.
