### ISSUE TITLE
EvoSuite is not finding the Java compiler in JAVA_HOME

### ISSUE THREAD

**Issue by rjust** [EvoSuite/evosuite#2]
EvoSuite logs the following error, despite setting JAVA_HOME to the installed JDK:
[MASTER] 20:31:06.099 [pool-1-thread-3] ERROR TestSuiteGenerator - No Java compiler is available. Are you running with the JDK?

How does EvoSuite pick up the Java compiler?

**Comment by arcuri82** [comment]
The code is in:

public static boolean isJavaCompilerAvailable() {
		JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
		return compiler != null;
	}

btw, is this question related to http://stackoverflow.com/questions/33694390/how-to-run-evosuite-without-jdk/33718253?noredirect=1#comment55234045_33718253  ?

**Comment by rjust** [comment]
Hi Andrea,

Yes, the question is related -- actually, it is exactly the same problem. However, the solutions described don't work for me.

I tested my environment with the following simple class:
```
public class TestCompiler {
    public static void main(String ... args) {
        System.out.println(javax.tools.ToolProvider.getSystemJavaCompiler());
    }
}
```
The output is (as expected):
`com.sun.tools.javac.api.JavacTool@9dd0fe7`

Running EvoSuite from the command line in exactly the same environment, however, leads to the aforementioned error -- Java compiler not found.

Any ideas?

Thanks,
René

**Comment by jgaleotti** [comment]
Hi Rene,
Have you tried adding tools.jar to the classpath?

Cheers,
JP

**Comment by arcuri82** [comment]
Hi Rene,

   in regard to your JDK, where is tools.jar located? Which operating system are you using? Maybe it is an issue in finding the tools.jar (see ToolsJarLocator code). If that is the case, you can try to set it with -Dtools_jar_location 

Cheers

Andrea

**Comment by rjust** [comment]
Hi,

I tried my code snippet, which uses the same code as EvoSuite to check for the system's Java compiler, on OSX and GNU Linux. The results are identical: my code snippet returns a reference to JavacTool, whereas the same code in EvoSuite apparently returns null.

On either OS, tools.jar is located in $JAVA_HOME/lib. Also, I only have the JDK installed, which means I don't even have to set JAVA_HOME to make the little code snippet above work.

I'll try to explicitly set the tools.jar, but I am still wondering why the same code behaves differently when executed standalone vs. embedded in EvoSuite.

Thanks,
René

**Comment by arcuri82** [comment]
Hi,
  I guess it is behaving differently because in EvoSuite that code is executed on a spawn process, which might have differences in the classpath (I did some changes recently to try to make ES working on Windows, and that might have unfortunately broke something, but not sure yet if related)

cheers

Andrea

**Comment by arcuri82** [comment]
Hi Rene,

  do you still have this issue? 

Andrea

**Comment by rjust** [comment]
Hi Andrea,

I previously used the released version, but using the most recent version in the repo seems to fix the problem. I think it is fine to close this issue.

Thanks,
Rene
