### ISSUE TITLE
Ambiguous method call in generated test

### ISSUE THREAD

**Issue by glains** [EvoSuite/evosuite#204]
### Context
Using evosuite 1.0.6, i have generated tests for a project, but a lot of them could not be compiled.

Ambiguous method call. Both
`doReturn(Object,Object...)` in Mockito and
`doReturn(Object,Object...)` in MockitoExtension match

A quick view in the import section shows both imports
```java
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*; // deprecated
```
but the latter is marked as deprecated.

Removing the deprecated imports solved the problem, but they shouldnt be there in the first place.

**Comment by gofraser** [comment]
That's strange, version 1.0.6 should not import MockitoExtension -- the import was removed in dba4901f0661dbef2b9279743a240044aa5fdefd

I just tried version 1.0.6 (using the jar-file from the releases section) and the import does not appear. Are you sure these tests were not generated by a previous version?

**Comment by glains** [comment]
You are correct, the errors were only occuring in 1.0.5. I have been using 1.0.6 elsewhere, but this part was still using 1.0.5.

**Comment by glains** [comment]
I have verified that this is not working with 1.0.6. Could you please have a further look?

**Comment by gofraser** [comment]
Could you please point me to a class under test to reproduce this problem? That would make it easier to look into it.

**Comment by glains** [comment]
Surprisingly, i have isolated one of the classes and i seems to work fine. This is a private project, so im afraid it is not possible to share any files. But i will have a look if i can narrow down the problem.

**Comment by prathmesh-halgekar** [comment]
Hi Gordon,
a) I confirmed this on v1.0.6 as mentioned in the issue and it's only 'org.evosuite.shaded.org.mockito.Mockito.* ' which is imported in the generated tests. I mean that's the correct behavior as per the related fix. We can close that issue saying not reproducible anymore.
b) Also, initially while trying to reproduce this issue, i.e. for the EvoSuite to use mocking - my CUT involved reading from a File on disk and making a REST web service call. But then the generated tests did not use any Mockito at all. In the case( .a ) where the CUT had a method with an argument as an 'annotation type' e.g @interface, then EvoSuite used Mockito. Are there also any other scenarios where EvoSuite uses mocking? My initial assumptions were - file reading and network access but turn out not to be true.
Best Regards,Prathmesh Halgekar 

    On Monday, July 30, 2018, 1:00:27 PM GMT+2, Gordon Fraser <notifications@github.com> wrote:  
 
 
Assigned #204 to @prathmesh-halgekar.
