### ISSUE TITLE
Fatal crash on main EvoSuite process. Class  using seed 1528872907266. Configuration id : null

### ISSUE THREAD

**Issue by tigerqiu712** [EvoSuite/evosuite#205]
[INFO] [MASTER] 14:55:07.273 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1528872907266. Configuration id : null
[INFO] java.lang.Error: Unresolved compilation problems:

 It is indirectly referenced from required .class files

[INFO] 	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_112]
[INFO] 	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_112]
[INFO] 	at org.evosuite.continuous.project.ProjectAnalyzer.getCutsToAnalyze(ProjectAnalyzer.java:169) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.continuous.project.ProjectAnalyzer.analyze(ProjectAnalyzer.java:200) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.continuous.ContinuousTestGeneration.execute(ContinuousTestGeneration.java:157) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.executionmode.Continuous.execute(Continuous.java:131) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:266) ~[evosuite-master-1.0.6.jar:1.0.6]
[INFO] 	at org.evosuite.EvoSuite.main(EvoSuite.java:302) ~[evosuite-master-1.0.6.jar:1.0.6]

**Comment by gofraser** [comment]
Is this an unresolved compilation problem in EvoSuite (did you build it yourself?) or is this an unresolved compilation problem in the class under test or one of its dependencies?

**Comment by tigerqiu712** [comment]
does it's supports @Component of spring ?

i check that can not find class have keyword @Component

**Comment by gofraser** [comment]
I will close this issue since it seems to be a basic compile error in the classes you're applying EvoSuite to, rather than an issue in EvoSuite.

Regarding @component, EvoSuite does not provide any special treatment of this Spring annotation.
