### ISSUE TITLE
how check failed to generate tests for 100 classes out of 100

### ISSUE THREAD

**Issue by tigerqiu712** [EvoSuite/evosuite#206]
[INFO] WARN: failed to generate tests for 100 classes out of 100
[DEBUG] EvoSuite terminated
[INFO] Stopping spawn process manager

have a parameter to check the detail information for the failed reason ?

**Comment by tigerqiu712** [comment]
check the log show [MASTER] 14:37:03.615 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 14:37:03.718 [main] ERROR TestGeneration - failed to write statistics data
what and where have  the detail ERROR SearchStatistics?

**Comment by MENG2010** [comment]
Kept meeting this same issue.
I deployed the experiment onto several different VMs (with exactly same configurations), however, experiments on ALL VMs EXCEPT ONE failed to generate tests for all classes.

BTW, I ran evosuite in maven.

**Comment by gofraser** [comment]
If you run EvoSuite with Maven, you can get detailed log files in the `.evosuite` directory. There will be a subdirectory for each invocation of evosuite:generate in there (e.g. `tmp_2018_09_08_07_04_32`) with a subdirectory `logs`.

I'm closing this issue, but if there's a bug causing the classes not to be tested please create a new issue for that.

**Comment by amit-github-personal** [comment]
WARN: failed to generate tests for 143 classes out of 143
Same Issue

**Comment by zohrakaouter** [comment]
Same issue
