### ISSUE TITLE
How to  generate test classes only for specific class with EvoSuite Maven plugin 

### ISSUE THREAD

**Issue by anandsubram** [EvoSuite/evosuite#207]
Is it possible to configure in maven plugin, to select specific classes for which JUNIT tests should be generated? I don't want to create test classes for all the classes. 

Right now I use **mvn evosuite:generate** in command line, which generates test class for all the classes

**Comment by jose** [comment]
`$ mvn evosuite:generate -Dcuts=org.foo.Bar`

**Comment by anandsubram** [comment]
Thank you!! 

One more check - Is it possible to generate test classes only for **specific methods** inside one single class? Because if its a huge class, we don't want to generate test classes for all methods inside it every time

**Comment by anandsubram** [comment]
Thank you!!

**Comment by TahaSaber** [comment]
mvn evosuite:generate -Dcuts=org.foo.Bar
it doesn't work for me, no class was created

**Comment by igorstojanovski** [comment]
> 
> 
> `$ mvn evosuite:generate -Dcuts=org.foo.Bar`

mvn evosuite:generate -Dcuts='org.foo.Bar' 

When using Apache Maven 3.6.0 not using single quotes causes an exception.
