### ISSUE TITLE
Issues generating test classes only for specific class through command line

### ISSUE THREAD

**Issue by anandsubram** [EvoSuite/evosuite#208]
Hi,

I facing issue as below issue, when trying to create test classes only for specific classes through command line. Can you please help on this?

I am using command as below

java -jar <Path_to_Jar>\evosuite-1.0.6.jar -projectCP <Project Path>\target\classes\<package name> -class <classname with .class extension>

[MASTER] 20:26:14.892 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1531009574886. Configuration id : null
java.lang.IllegalArgumentException: **The target -class should be a JVM qualifying name (e.g., org.foo.SomeClass) and not a source file**
        at org.evosuite.CommandLineParameters.validateInputOptionsAndParameters(CommandLineParameters.java:60) ~[evosuite-1.0.6.jar:1.0.6]
        at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:204) ~[evosuite-1.0.6.jar:1.0.6]
        at org.evosuite.EvoSuite.main(EvoSuite.java:302) ~[evosuite-1.0.6.jar:1.0.6]

**Comment by jose** [comment]
I think the command you're trying to execute isn't correct. Try the following:
`$ java -jar <Path_to_Jar>\evosuite-1.0.6.jar -projectCP target\classes -class <classname *without* .class extension, i.e., JVM qualifying name, e.g., org.foo.Bar>`
