### ISSUE TITLE
Empty Test Cases throw a SecurityException during coverage report generation.

### ISSUE THREAD

**Issue by MartinRogalla** [EvoSuite/evosuite#21]
After running a suite of automated generated tests for [JodaTime](https://github.com/JodaOrg/joda-time) and creating a coverage report in Intellij and Cobertura, the reported coverage is 0%. I was able to pinpoint the problem to empty generated test cases such as this one:

``` java
@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PreciseDurationDateTimeField_ESTest extends PreciseDurationDateTimeField_ESTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
```

An exception being thrown and stacktrace printed, when the coverage report is created:

```
Exception in thread "Thread-0" java.lang.SecurityException: Security manager blocks ("java.io.FilePermission" "/Users/mrogalla/Library/Caches/IntelliJIdea2016.1/coverage/coverage-error.log" "write")
java.lang.Thread.getStackTrace(Thread.java:1552)
org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:433)
java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
java.io.FileOutputStream.<init>(FileOutputStream.java:200)
com.intellij.rt.coverage.util.ErrorReporter.getErrorLogStream(ErrorReporter.java:84)
com.intellij.rt.coverage.util.ErrorReporter.reportError(ErrorReporter.java:51)
com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:86)
com.intellij.rt.coverage.instrumentation.SaveHook.run(SaveHook.java:51)
java.lang.Thread.run(Thread.java:745)

    at org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:451)
    at java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:200)
    at com.intellij.rt.coverage.util.ErrorReporter.getErrorLogStream(ErrorReporter.java:84)
    at com.intellij.rt.coverage.util.ErrorReporter.reportError(ErrorReporter.java:51)
    at com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:86)
    at com.intellij.rt.coverage.instrumentation.SaveHook.run(SaveHook.java:51)
    at java.lang.Thread.run(Thread.java:745)
```

The problem can be resolved by removing these empty test cases manually.

**Comment by arcuri82** [comment]
Hi,
  thx for reporting the problem. When tests are run, ES setups a sandbox before they start, and shut it down after they are finished. It looks like the sandbox here was not properly shutdown. Or rather the logging to that ``coverage-error.log`` file is done while tests are executed. We have never tried to run ES from IntellIj with Cobertura. Do you get same problem if you use default coverage of IntelliJ? (it is only available in Ultimate edition, not Community one) 

Can you please specify which version of ES and IntelliJ you are using?

**Comment by MartinRogalla** [comment]
### Clarification
Ah, sorry let me clarify. So when I generate and run tests either with 
 - Intellij w/ default coverage reporting and the EvoSuite plugin

or by

 - Generating tests using [evosuite-1.0.3.jar](https://github.com/EvoSuite/evosuite/releases/download/v1.0.3/evosuite-1.0.3.jar) and running Maven w/ cobertura: `mvn cobertura:cobertura`

It gives me 0% when such an empty test case is in the suite.

---------------------------
### Versions

**Intellij Idea Ultimate Edition**
```
IntelliJ IDEA 2016.1
Build #IU-145.258, built on March 17, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
**EvoSuite 1.0.3**
using [evosuite-1.0.3.jar](https://github.com/EvoSuite/evosuite/releases/download/v1.0.3/evosuite-1.0.3.jar)

**Comment by gofraser** [comment]
Cobertura should work now, see http://www.evosuite.org/documentation/measuring-code-coverage/ for instructions.
