### ISSUE TITLE
Test Class for RestController Observations

### ISSUE THREAD

**Issue by anandsubram** [EvoSuite/evosuite#211]
Hi,

I was trying to create test class for below sample RestController class

package io.java.springbootstartup.hello;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMethod;

@RestController
public class HelloController {
	@RequestMapping(path = "/springtest")
	
	public String sayHi()
	{
		return "Welcome to Spring";
	}

}

The EvoSuite test class which generated didn't contain any mock validations to touch the end point

Expected something like this:-

@Test
		public void testMockPhoneNumberRequest() throws Exception {
		   System.out.println("content is "+this.mockMvc.perform(get("/springtest")));
	        this.mockMvc.perform(get("/springtest")).andExpect(status().isOk());
	    this.mockMvc.perform(get("/springtest")).andExpect(content().string(containsString("Welcome")));

Actual EvoSuite test class:- (**Issue - Didn't do any validations with "/springtest"**)

@Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HelloController helloController0 = new HelloController();
      String string0 = helloController0.sayHi();
      assertEquals("Welcome to Spring", string0);
  }
}

Is this something you can please help with? Does EvoSuite work very well with service testing?

**Comment by anandsubram** [comment]
Is there any update on this?

**Comment by AaratiT** [comment]
Hi Anandsubram ,
Is this challenge of generating Spring framework related test classes is resolved ?
If yes, then it will be helpful if u can  share,  how did u solve it ?

**Comment by gofraser** [comment]
I'm afraid EvoSuite only produces assertions on objects in the test, their observers, fields, and return values.
