### ISSUE TITLE
Does EvoSuite Maven plugin to generate test classes only for specific class, compiles all the classes in Project?

### ISSUE THREAD

**Issue by anandsubram** [EvoSuite/evosuite#214]
I ran the command $ mvn evosuite:generate -Dcuts=org.foo.Bar to generate test class only for a specific class.  However it resulted in "Build Failure", because other classes had issues in Project. So does this mean that even though we try to create test class for a particular class, it compiles everything in target/classes ? Any way to skip that?

**Comment by jose** [comment]
> So does this mean that even though we try to create test class for a particular class, it compiles everything in target/classes ?

Just to be clear, EvoSuite does not compile anything. However, the `evosuite:generate` option depends on the outcome of the `compile` phase. When you run `mvn evosuite:generate`, maven compiles all classes that have been modified and if there are any class with compilation issues, the build stops.

> Any way to skip that?

You can configure [maven-compiler-plugin](https://maven.apache.org/plugins/maven-compiler-plugin/) to ignore classes with compilation issues (see [failOnError](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#failOnError)), however I would not recommend it!

PS: Can you please use the developers' [mailing list](https://groups.google.com/forum/#!forum/evosuite) to ask questions like this one and use the issues tracker to **only** report issues / bugs?
