### ISSUE TITLE
Unable to add Evosuite plugin to pom.xml

### ISSUE THREAD

**Issue by goutham85** [EvoSuite/evosuite#216]
### Context
I was trying to add the evosuite dependency to my project pom.xml in eclips. Then received an error related to certification

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. Create a new Maven Project
2. Add the evosuite dependency 
<dependency>
  <groupId>org.evosuite</groupId>
  <artifactId>evosuite-standalone-runtime</artifactId>
  <version>1.0.6</version>
  <scope>test</scope>
</dependency>
3. Build the project

### EvoSuite Arguments
NA

### Current Result
ArtifactDescriptorException: Failed to read artifact descriptor for org.evosuite:evosuite-standalone-runtime:jar:1.0.6: ArtifactResolutionException: Failure to transfer org.evosuite:evosuite-standalone-runtime:pom:1.0.6 from https://repo.forge.lmig.com/content/groups/ciit was cached in the local repository, resolution will not be reattempted until the update interval of ciit has elapsed or updates are forced. Original error: Could not transfer artifact org.evosuite:evosuite-standalone-runtime:pom:1.0.6 from/to ciit (https://repo.forge.lmig.com/content/groups/ciit): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target	pom.xml	/testEvo	line 1	Maven Dependency Problem

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
I tried on my project and also created a brand new maven project and tried again. In both cases, when the dependency was added to pom.xml, the above listed error was displayed.

**Comment by AaratiT** [comment]
Can u check ur pom.xml, if below entries are correct

```
 <plugin>
        <groupId>org.evosuite.plugins</groupId>
        <artifactId>evosuite-maven-plugin</artifactId>
        <version>1.0.6</version>
      </plugin>
```
```
<pluginRepositories>
  <pluginRepository>
    <id>EvoSuite</id>
    <name>EvoSuite Repository</name>
    <url>http://www.evosuite.org/m2</url>
  </pluginRepository>
</pluginRepositories>
``` 

Also to generate test classes, are u using 
evosuite:generate goal

May this [tutorial ](http://www.evosuite.org/documentation/tutorial-part-2/) be of some help

**Comment by gofraser** [comment]
EvoSuite is actually on Maven Central (http://repo.maven.apache.org/maven2/org/evosuite/evosuite-standalone-runtime/1.0.6/) so it should be sufficient to add:

```
 <plugin>
        <groupId>org.evosuite</groupId>
        <artifactId>evosuite-standalone-runtime</artifactId>
        <version>1.0.6</version>
</plugin>
```

The error message you listed seems to be related to your connection rather than EvoSuite itself (e.g. https://stackoverflow.com/questions/48593183/maven-unable-to-find-valid-certification-path).
