### ISSUE TITLE
1.0.6 test failure on Windows

### ISSUE THREAD

**Issue by AP-Hunt** [EvoSuite/evosuite#220]
### Context
I'm attempting to compile and test EvoSuite 1.0.6 prior to making any changes, but currently getting the same test failure as described in #10 (except I'm compiling on Windows). I've checked permissions and the user, as implied by that issue, but I don't see anything amiss. Are there any known problems with testing EvoSuite on Windows?

OS: Win 10 v1803(17134.165)
EvoSuite: 1.0.6
Java
>java version "1.8.0_181"
>Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
>Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### Steps to Reproduce
```
cd C:\path\to\src
mvn clean
mvn test
```

### Current Result
```
[ERROR] Errors:
[ERROR]   MockJFileChooserTest.testGetCurrentDirectory:57 NullPointer
[INFO]
[ERROR] Tests run: 123, Failures: 0, Errors: 1, Skipped: 4
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] EvoSuite 1.0.6 ..................................... SUCCESS [  0.281 s]
[INFO] evosuite-runtime ................................... FAILURE [01:00 min]
[INFO] evosuite-client .................................... SKIPPED
[INFO] evosuite-master .................................... SKIPPED
[INFO] evosuite-plugins ................................... SKIPPED
[INFO] Maven Plugin for EvoSuite .......................... SKIPPED
[INFO] evosuite-maven-plugin-test ......................... SKIPPED
[INFO] build-support-test ................................. SKIPPED
[INFO] evosuite-standalone-runtime ........................ SKIPPED
[INFO] evosuite-shaded .................................... SKIPPED
[INFO] evosuite-generated 1.0.6 ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 min
[INFO] Finished at: 2018-08-06T15:17:58+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by gofraser** [comment]
Apologies for the late response. I don't have a Windows system so can't easily debug this. Since the MockJFileChooser seems to return `null` as `currentDirectory` in your case, something must be going wrong when `MockJFileChooser.setCurrentDirectory` is called with parameter `null` by the constructor. It would probably be helpful to set a breakpoint around line 213 and step through that method to see what's happening. 

Can anyone with a Windows system reproduce this and help?

**Comment by prathmesh-halgekar** [comment]
This issue cannot be reproduced for (EvoSuite 1.0.6 and 1.0.7): Verified on Windows 10 and using Java 1.8.0_121

**Comment by AP-Hunt** [comment]
This looks to be caused by [MockJFileChooser#233-236](https://github.com/EvoSuite/evosuite/blob/1.0.6/runtime/src/main/java/org/evosuite/runtime/mock/javax/swing/MockJFileChooser.java#L233) and the implementation of  [MockFileSystemView::getFileSystemView()](https://github.com/EvoSuite/evosuite/blob/1.0.6/runtime/src/main/java/org/evosuite/runtime/mock/javax/swing/filechooser/MockFileSystemView.java#L52)

When I debug the test, [MockJFileChooser#223](https://github.com/EvoSuite/evosuite/blob/1.0.6/runtime/src/main/java/org/evosuite/runtime/mock/javax/swing/MockJFileChooser.java#L233) returns a [MockFile](https://github.com/EvoSuite/evosuite/blob/1.0.6/runtime/src/main/java/org/evosuite/runtime/mock/java/io/MockFile.java) representing `C:\`. On the first iteration, it is found to not be traversable, and hits [MockFileSystemView::getParentDirectory](https://github.com/EvoSuite/evosuite/blob/1.0.6/runtime/src/main/java/org/evosuite/runtime/mock/javax/swing/filechooser/MockFileSystemView.java#L355), which subsequently finds that the directory doesn't exist.

This is because [MockFile::getAbsolutePath()](https://github.com/EvoSuite/evosuite/blob/1.0.6/runtime/src/main/java/org/evosuite/runtime/mock/java/io/MockFile.java#L169) is appending the `C:\` path to the location under `D:\` in which the code is kept, to create a path of `D:\CODE\UNI\evosuite-1.0.6\runtime/C:\`, which doesn't exist.

If I move the code to a directory under `C:\` this test failure goes away. I'll make a change to address it and issue a pull request.
