### ISSUE TITLE
assertThrownBy cannot load/analyze class <evosuite>

### ISSUE THREAD

**Issue by Greg4cr** [EvoSuite/evosuite#24]
At times, I am generating tests that look like this:

```
 @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Reporter reporter0 = new Reporter();
      // Undeclared exception!
      try { 
        reporter0.incorrectUseOfApi();
        fail("Expecting exception: RuntimeException");

      } catch(RuntimeException e) {
         //
         // 
         // java.lang.String@0000000004
         // org.mockito.internal.debugging.LocationImpl@0000000003
         // java.lang.String@0000000005
         // java.lang.String@0000000006
         // java.lang.String@0000000007
         // java.lang.String@0000000008
         // java.lang.String@0000000009
         // java.lang.String@0000000005
         //
         assertThrownBy("<evosuite>", e);
      }
   }
```

When I run these tests, I get the error:
`junit.framework.AssertionFailedError: Cannot load/analyze class <evosuite>`
after a RuntimeException is thrown (as expected), but then it hits that assertThrownBy comparison.

This makes sense, as it appears that `<evosuite>` is a default value, and should be filled in with some actual class name. 

Can you provide any insight on this issue, and what might cause the `evosuite>` value to be used instead of an actual class?

**Comment by Greg4cr** [comment]
This is one of the classes that causes this issue: 
https://github.com/mockito/mockito/blob/80452c7a42777513c35fd30c4e12bcd7ee438fb9/src/org/mockito/exceptions/Reporter.java

**Comment by arcuri82** [comment]
Hi,
  that is definitively a bug :(  we have been making few changes in `assertThrownBy `. Which version of EvoSuite did you use? 1.0.3? or latest SNAPSHOT ?

**Comment by Greg4cr** [comment]
I'm using 1.0.3.

**Comment by Greg4cr** [comment]
I found a similar case on a different version of the same class, but slightly different context:
```
 @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Reporter reporter0 = new Reporter();
      // Undeclared exception!
      try { 
//         reporter0.incorrectUseOfAdditionalMatchers("-> at <evosuite>.<evosuite>(<evosuite>)", 793, (Collection<LocalizedMatcher>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.mockito.exceptions.Reporter", e);
      }
  }
```

See the input to the `incorrectUseOfAdditionalMatchers` method. 

Class used for generation: https://github.com/mockito/mockito/blob/42b391d4209024292b6101048389570e4ec36b2a/src/org/mockito/exceptions/Reporter.java

**Comment by gofraser** [comment]
There is an explicit check on classes in `assertThrownBy` so the original issue should not occur anymore. It might still happen that fake stacktraces occur in other strings though (this is because stacktraces tend to introduce flakiness)
