### ISSUE TITLE
Debugging with Properties.CLIENT_ON_THREAD = true

### ISSUE THREAD

**Issue by llmhyy** [EvoSuite/evosuite#241]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

Hi, I am debugging Evosuite with source code imported into Eclipse. Following the tutorial http://www.evosuite.org/documentation/tutorial-part-4/, I use `Properties.CLIENT_ON_THREAD = true` to allow the Evosuite client running in the same process of Evosuite mater. However I got the following error:

```
WARN  org.evosuite.junit.JUnitAnalyzer - Found unstable test named initializationError -> class java.lang.RuntimeException: Cannot find either the compilation target folder nor the EvoSuite jar in classpath: 
E:\linyun\git_space\evosuite\runtime\target\test-classes
E:\linyun\git_space\evosuite\runtime\target\classes
E:\linyun\workspace\workspace_for_evosuite\Test\bin
E:\linyun\git_space\evosuite\client\target\test-classes
E:\linyun\git_space\evosuite\client\target\classes
E:\linyun\git_space\evosuite\runtime\target\test-classes
E:\linyun\git_space\evosuite\runtime\target\classes
E:\linyun\git_space\evosuite\master\target\classes
E:\linyun\git_space\evosuite\master\target\test-classes
...
```
Would you please advise why the problem happens?

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.  The source code to run Evosuite is as follows:
```
public class Test {

	@SuppressWarnings("unchecked")
	public void evosuite(String targetClass, String targetMethod, String cp, int seconds) {
		EvoSuite evo = new EvoSuite();
		Properties.TARGET_CLASS = targetClass;
//		Properties.TARGET_METHOD = targetClass+".test(DDI)V";
		Properties.ALGORITHM = Algorithm.MONOTONICGA;
		Properties.TRACK_COVERED_GRADIENT_BRANCHES = true;
		Properties.CRITERION = new Criterion[] {Criterion.BRANCH};
		
		String[] command = new String[] {"-generateSuite", "-class", targetClass, 
				"-projectCP", cp, "-Dsearch_budget", String.valueOf(seconds), "-criterion", "branch"};
		
		List<List<TestGenerationResult>> list 
			= (List<List<TestGenerationResult>>) evo.parseCommandLine(command);
		for(List<TestGenerationResult> l: list) {
			for(TestGenerationResult r: l) {
				System.out.println(r);
			}
		
		}
		
	}
	
	public static void main(String[] args) {
		String targetClass = Example4.class.getName();
		String targetMethod = "test0";
		String cp = "bin";
		
		Properties.LOCAL_SEARCH_RATE = 1;
//		Properties.DEBUG = true;
		Properties.PORT = 8000;
		Properties.CLIENT_ON_THREAD = true;
		
		int timeBudget = 30;
		
		Test t = new Test();
		t.evosuite(targetClass, targetMethod, cp, timeBudget);

	}

}
```
2. The example Java code is as follows:
```
package com.test;

public class Example4 {
	public void test(int a){
		int b = 2*a;
		if(b==1234588888){
			return;
		}
		
		return;
	}
}

```
3.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
See above Java code.

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
See above description.
 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by Anand0583** [comment]
Why is this issue closed even without a comment @llmhyy
