### ISSUE TITLE
Is there a command line option to "not generate catch block" so that the junit test can fail.

### ISSUE THREAD

**Issue by firetorch** [EvoSuite/evosuite#26]
`@Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ListOfStrings listOfStrings0 = new ListOfStrings(73);
      // Undeclared exception!
      try { 
        listOfStrings0.toArray((Class) null);
        fail("Expecting exception: NullPointerException");

```
  } catch(NullPointerException e) {
     //
     // no message in exception (getMessage() returned null)
     //
     assertThrownBy("ListOfStrings", e);
  }
```

  }` 

In the generated test the try block raises a **NullPointerException** and the **catch** block suppresses it. This will cause the junit test to pass. Is there a way in which the test cases can be generated without **catch** block. So that junit test indicates a failure?

**Comment by arcuri82** [comment]
No, there is no such option, although it should be not too difficult to add (although there would be some side-effects in the assertion generation and automated-checks for flaky tests).

But what would be the business case? More often than not, an exception is just a violated pre-condition on input data, and not a bug in the code, making it a false positive. And throwing an exception would make the test quite useless for regression testing. 

Can you explain why you would like to have failing tests when exceptions are thrown?

**Comment by firetorch** [comment]
I think this blocks the tests to fail due to a real bug in code rather than it passing unnecessarily.
Additionally, running Evosuite will help developers to uncover bugs in methods whether they tend to miss out on the trivial null checks which are then quite often caught by the code reviewer.
In large projects, due to regression tests being run periodically, as a developer I would like to find out all the possible bugs in my code myself rather than fail the regression tests and then fix my code.
Probably providing an option to either print the error trace in log as part of catch statement/fail the test/continue like today will be very useful.

**Comment by giphon** [comment]
Related with this issue. 
How to collect the execution trace of tests that generated by EvoSuite? Line numbers in the trace can help to debug. Thx.

**Comment by gofraser** [comment]
You can now set the property -Dcatch_undeclared_exceptions=false and no catch-blocks for undeclared exceptions will be caught. You can also use -Dcheck_contracts=true to generate a separate test suite with all tests that fail some generic contract (such as "no undeclared exceptions").
