### ISSUE TITLE
How to generate test cases only for specific methods inside a class with EvoSuite using command line?

### ISSUE THREAD

**Issue by ps073006** [EvoSuite/evosuite#261]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
I am currently using evosuite1.0.6 from CLI.
I am trying to use the target_method property to generate test cases for a particular method.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1.
2.
3.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
1. java -jar evosuite-1.0.6.jar -Dtarget_method="add_values([I)I"  -class MethodCollection2   -projectCP .\src -criterion weakmutation
2.java -jar evosuite-1.0.6.jar -Dtarget_method="add_values"  -class MethodCollection2   -projectCP .\src -criterion weakmutation

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
It is generating test case for whole MethodCollection2 class
 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*
I want to generate test case for only add_values method

### Additional info
*Please add any information of interest here below*

**Comment by jose** [comment]
Hi @ps073006,

Last time I checked (see #209), the generation of test cases for specific methods was working. Could you please provide the signature of the `add_values` method?

PS: I noticed that you are specifying `.\src` as the project class... Is the `MethodCollection2.class` file in `.\src`?


--
Best,
Jose

**Comment by ps073006** [comment]
Hi Jose,
I am using evosuite from command line. I have not tested it from maven. my tested method is and method is  ..
public static  int add_values( int[] a )
    {
}
Signature is add_values([I)I ..i guess it is correct!
And yes. .class file is in the src folder of the project.

thanks,
Prashanta

**Comment by jose** [comment]
The parameter `-Dtarget_method="add_values([I)I"` seems to be working as expected.

### Example of a class under test

```java
public class MethodCollection2 {
    public static int add_values(int[] a) {
        return 42;
    }

    public boolean foo(int x) {
        if (x % 2 == 0) {
            return true;
        }
        return false;
    }
}
```

### Generate tests for all methods (default)

```
$ java -jar evosuite-1.0.6.jar -class MethodCollection2 -projectCP . -criterion weakmutation
```
Here are the tests generated by EvoSuite:
```java
  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MethodCollection2 methodCollection2_0 = new MethodCollection2();
      boolean boolean0 = methodCollection2_0.foo(3257);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MethodCollection2 methodCollection2_0 = new MethodCollection2();
      boolean boolean0 = methodCollection2_0.foo(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MethodCollection2 methodCollection2_0 = new MethodCollection2();
      boolean boolean0 = methodCollection2_0.foo((-1679));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[5];
      int int0 = MethodCollection2.add_values(intArray0);
      assertEquals(42, int0);
  }
```

### Generate tests for a single method

```
$ java -jar evosuite-1.0.6.jar -Dtarget_method="add_values([I)I" -class MethodCollection2 -projectCP . -criterion weakmutation
```
Here is the test generated by EvoSuite:
```java
  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int[] intArray0 = new int[13];
      int int0 = MethodCollection2.add_values(intArray0);
      assertEquals(42, int0);
  }
```

**Comment by ps073006** [comment]
Hi Jose,
I have repeated the same process as you did. But the issue remains same. What could be the possible reason?
Thanks

**Comment by jose** [comment]
No clue. What's the output of the following command `javap -c -p -s MethodCollection2` ?

**Comment by ps073006** [comment]
Error: class not found: MethodCollection2

**Comment by jose** [comment]
You've to execute the command in the `src` directory, otherwise `javap` cannot find the .class file.

**Comment by ps073006** [comment]
I had to give MethodCollection2.class and it returns....
C:\Users\p66n633\workspace\evosuite\src>javap -c -p -s MethodCollection2.class
Compiled from "MethodCollection2.java"
public class MethodCollection2 {
  public MethodCollection2();
    descriptor: ()V
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":
()V
       4: return

  public static int add_values(int[]);
    descriptor: ([I)I
    Code:
       0: bipush        42
       2: ireturn

  public boolean foo(int);
    descriptor: (I)Z
    Code:
       0: iload_1
       1: iconst_2
       2: irem
       3: ifne          8
       6: iconst_1
       7: ireturn
       8: iconst_0
       9: ireturn
}

**Comment by jose** [comment]
Interesting, I got the exact same bytecode...

- Are you using this [evosuite.jar](evosuite-1.0.6.jar)?
- Which Java version are you using?

Could you please execute the following command `java -jar evosuite-1.0.6.jar -class MethodCollection2 -projectCP . -criterion weakmutation -Dsearch_budget=10 -Dlog.level=DEBUG > issue_261_log.txt` and send me the `issue_261_log.txt` file?

**Comment by ps073006** [comment]
I am using evosuite-1.0.6.jar and java version 1.8.0_191.
[issue_261_log.txt](https://github.com/EvoSuite/evosuite/files/3214369/issue_261_log.txt)

Thanks.

**Comment by btsaubt** [comment]
I am also having this same problem, but I suspect that it may be caused by . If I wanted to specify a target method using the `-Dtarget_method` flag, what syntax would the method signature follow? For example, if I had a method:

```java
public static int mult(int a, int b) {
    return a * b;
}
```

would the signature I pass in as an argument be `mult(II)I`, without accounting for the static?

**Comment by GuanmingQiao** [comment]
This issue still exists for me and my colleague. Very obviously a bug

**Comment by rachelt44** [comment]
Hi, it seems that this issue still exists. I'm using evosuite-1.0.6.jar and both -Dtarget_method and -Dtarget_method_list arguments are ignored and instead unit tests are created for all methods. Is there any fix or workaround for this issue? Thanks!

**Comment by yyy2015** [comment]
Hi,you can try the lateset 1.0.7 snapshot version, you can download it at the release page, with this version, I can generate test cases for one specific method.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rachelt44"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 晚上10:15
收件人:&nbsp;"EvoSuite/evosuite"<evosuite@noreply.github.com&gt;;
抄送:&nbsp;"找呀找呀找尾巴"<2456700983@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [EvoSuite/evosuite] How to generate test cases only for specific methods inside a class with EvoSuite using command line? (#261)





 
Hi, it seems that this issue still exists. I'm using evosuite-1.0.6.jar and both -Dtarget_method and -Dtarget_method_list arguments are ignored and instead unit tests are created for all methods. Is there any fix or workaround for this issue? Thanks!

**Comment by rachelt44** [comment]
@yyy2015 thank you! where can i find the 1.0.7 snapshot version? the release page https://www.evosuite.org/downloads/ doesn't seem to contain it.

**Comment by yyy2015** [comment]
Oh, since the release page doesn't provide the version, you have to build it from the code yourself. the readme explains it clearly. https://github.com/EvoSuite/evosuite. Here is my build result before, maybe a little old, just for reference:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;link： https://pan.baidu.com/s/1QsakbEuAhgzg9IlNA7-M_w&nbsp;password：fzpw




------------------ 原始邮件 ------------------
发件人:&nbsp;"rachelt44"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 晚上10:38
收件人:&nbsp;"EvoSuite/evosuite"<evosuite@noreply.github.com&gt;;
抄送:&nbsp;"找呀找呀找尾巴"<2456700983@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [EvoSuite/evosuite] How to generate test cases only for specific methods inside a class with EvoSuite using command line? (#261)





 
@yyy2015 thank you! where can i find the 1.0.7 snapshot version? the release page https://www.evosuite.org/downloads/ doesn't seem to contain it.

**Comment by rachelt44** [comment]
that's what i suspected :-) many thanks !
