### ISSUE TITLE
Test failures in DependencyAnalysisTest

### ISSUE THREAD

**Issue by Bjorn48** [EvoSuite/evosuite#262]
I am trying to build EvoSuite (master branch) using the Maven commands also used in CircleCI, so first `mvn clean`, then `mvn dependency:resolve -DskipITs package`. All tests in the `DependencyAnalysisTest` class fail. Relevant Maven output:

```
[ERROR] Failures:
[ERROR]   DependencyAnalysisTest.test1levelContext:64 expected:<[[]]> but was:<[[com.examples.with.different.packagename.context.complex.EntryPointsClass:dosmt(ILjava/lang/String;D)V com.examples.with.different.packagename.context.complex.SubClass:checkFiftneen(I)Z]]>
[ERROR]   DependencyAnalysisTest.test2levelContext:80 expected:<[[]]> but was:<[[com.examples.with.different.packagename.context.complex.EntryPointsClass:dosmt(ILjava/lang/String;D)V com.examples.with.different.packagename.context.complex.SubClass:checkFiftneen(I)Z com.examples.with.different.packagename.context.complex.SubClass:bla(I)Z]]>
[ERROR]   DependencyAnalysisTest.test3levelContext:95 expected:<[[]]> but was:<[[com.examples.with.different.packagename.context.complex.EntryPointsClass:dosmt(ILjava/lang/String;D)V com.examples.with.different.packagename.context.complex.SubClass:checkFiftneen(I)Z com.examples.with.different.packagename.context.complex.SubClass:bla(I)Z com.examples.with.different.packagename.context.complex.SubSubClass:innermethod(I)Z]]>
[ERROR]   DependencyAnalysisTest.testContextInParamethers:107 expected:<[[]]> but was:<[[com.examples.with.different.packagename.context.complex.EntryPointsClass:doObj(Lcom/examples/with/different/packagename/context/complex/AParameterObject;)V com.examples.with.different.packagename.context.complex.ParameterObject:isEnabled()Z]]>
````

I see that those tests pass on CircleCI. What could be the problem on my machine? Note that I am using Windows 10.

**Comment by Bjorn48** [comment]
# Additional info
I have some additional info that I hope might help solve the problem.

- In the assert statements in the tests, the expected and actual values are apparently switched around.
- While I am not familiar enough with the code to determine what it should do exactly, I tried to output some of the variable values it produces during run-time. See below.
- In the `initialize()` method, a directory is specified for adding to the classpath in this line: `String cp = System.getProperty("user.dir") + "/target/test-classes";` Changing the hard-coded forward slashes to back-slashes for Windows does not seem to solve the problem (it appears nothing changes in the variable values).

## Variable values
For `test1levelContext()` I have specified where the variable values come from. This is the same for the other tests.
### `test1levelContext()`
So for example consider the `test1levelContext()` test, and inside that the call to `getAllContextsFromTargetClass()`. Inside that method, these are the values of the variables in that method:
```
root = com.examples.with.different.packagename.context.complex.SubClass.checkFiftneen(I)Z
paths = [[com.examples.with.different.packagename.context.complex.SubClass.checkFiftneen(I)Z]]
contexts = []
contexts = []
```
where the first `contexts` is right before the if-statement and the second on right before the return statement.

Inside the call to `convertIntoCallContext()` inside that method, these are some variable values:
```
list = [com.examples.with.different.packagename.context.complex.SubClass.checkFiftneen(I)Z]
className = com.examples.with.different.packagename.context.complex.EntryPointsClass
list.get(0).getClassName() = com.examples.with.different.packagename.context.complex.SubClass
```
### `test2levelContext`
```
root = com.examples.with.different.packagename.context.complex.SubClass.bla(I)Z
paths = [[com.examples.with.different.packagename.context.complex.SubClass.bla(I)Z, com.examples.with.different.packagename.context.complex.SubClass.checkFiftneen(I)Z]]
list = [com.examples.with.different.packagename.context.complex.SubClass.bla(I)Z, com.examples.with.different.packagename.context.complex.SubClass.checkFiftneen(I)Z]
className = com.examples.with.different.packagename.context.complex.EntryPointsClass
list.get(1).getClassName() = com.examples.with.different.packagename.context.complex.SubClass
list.get(0).getClassName() = com.examples.with.different.packagename.context.complex.SubClass
contexts = []
contexts = []
```

### `test3levelContext`
```
root = com.examples.with.different.packagename.context.complex.SubSubClass.innermethod(I)Z
paths = []
contexts = []
contexts = []
```

### `testContextInParamethers`
```
root = com.examples.with.different.packagename.context.complex.ParameterObject.isEnabled()Z
paths = []
contexts = []
contexts = []
```

**Comment by kevNii** [comment]
I'm running into the same problem, did you find a solution?

**Comment by Bjorn48** [comment]
> I'm running into the same problem, did you find a solution?

Hi @kevNii, I did not find a solution yet, unfortunately.

**Comment by hunan889** [comment]
I found the root cause:

in .class file, the class name is recorded as "com/examples/with/different/packagename/concolic/Assertions", while in windows, the File.separator is "\", and that will causes problems

![image](https://user-images.githubusercontent.com/6399498/89271465-51c80b80-d66f-11ea-8e6a-25d2e3092f76.png)


solution: 

replace 
	classname = classname.replace(File.separator, ".");
to 
	classname = classname.replace("/", ".");

and it works for me
