### ISSUE TITLE
[BUG] Target Method Test Generation Inconsistent When Running on Subprocess

### ISSUE THREAD

**Issue by GuanmingQiao** [EvoSuite/evosuite#273]
### Context
I'm trying to run EvoSuite in a subprocess created by Java ProcessBuilder, as part of a Java program. When running the command through EvoSuite CLI, the results are as expected. However, when running the same command from the Java `ProcessBuilder`, the generated tests are wrong.

Related: #261 #264 #209 

@jose And the issue in #261 persists for me: per-method test generation does not work when `weakmutation` or `strongmutation` is turned on. So far, it seems to only work with `1.0.7-master-SNAPSHOT` on commandline with `criterion=method`

### Steps to Reproduce

- The source code being tested:
```
package source_repo;

public class MultTester {
    public static int c = 2;

    public static int add_values(int[] a) {
        return 42;
    }

    public boolean foo(int x) {
        if (x % 2 == 0) {
            return true;
        }
        return false;
    }
}
```
- Run the command from Terminal 
<img width="718" alt="Screen Shot 2019-10-09 at 10 36 07 PM" src="https://user-images.githubusercontent.com/22064968/66534778-4d7da100-eae5-11e9-9233-7980532b0ef5.png">

- Run the command from Java ProcessBuilder
<img width="750" alt="Screen Shot 2019-10-09 at 10 37 57 PM" src="https://user-images.githubusercontent.com/22064968/66534835-83bb2080-eae5-11e9-9f25-d61b0d16fdfb.png">
<img width="1374" alt="Screen Shot 2019-10-09 at 10 50 55 PM" src="https://user-images.githubusercontent.com/22064968/66535359-596a6280-eae7-11e9-8016-60fca3a506cf.png">

### EvoSuite Arguments
- The command to generate test only for method `add_values`: 
`java -jar evosuite-master-1.0.7-SNAPSHOT.jar -Dtarget_method_list="add_values([I)I" -class source_repo.MultTester -projectCP ./src/main/java -criterion method`

### Expected Result
- Command generates the same tests whether running from Terminal or Subprocess

### Current Result
- Run the command directly in Terminal
Logs `Total number of test goals: 2`
<img width="250" alt="Screen Shot 2019-10-09 at 10 53 13 PM" src="https://user-images.githubusercontent.com/22064968/66535454-9cc4d100-eae7-11e9-80c5-2dd0426383d2.png">
Generates test for the correct method and a default Constructor
<img width="544" alt="Screen Shot 2019-10-09 at 10 39 52 PM" src="https://user-images.githubusercontent.com/22064968/66534910-c250db00-eae5-11e9-8d06-a552be278f44.png">

- Run the command from Java ProcessBuilder without modifying its environmental variables
Logs `Total number of test goals: 1`
<img width="293" alt="Screen Shot 2019-10-09 at 10 53 34 PM" src="https://user-images.githubusercontent.com/22064968/66535472-a817fc80-eae7-11e9-92ac-06659edb2e7e.png">
Generates test for the default Constructor only, which is WRONG
<img width="546" alt="Screen Shot 2019-10-09 at 10 38 57 PM" src="https://user-images.githubusercontent.com/22064968/66534881-a4837600-eae5-11e9-9044-8fcbb93588ef.png">

**Comment by VoglSebastian** [comment]
running your code results in PROPERTIES.TARGET_METHOD_LIST == "\"add_values([I)I\"" in EvoSuite, while running the command from command line leads to PROPERTIES.TARGET_METHOD_LIST == "add_values([I)I". Consequently, the method add_values gets excluded from the target methods.

To fix this, just remove the \" from the command (at least it fixed it on my machine):
-Dtarget_method_list=add_values([I)I

Maybe we should remove \" at the start and end of some Properties, since it can not be part of a method name anyway.

**Comment by gofraser** [comment]
How about throwing an exception if there's an invalid character in a property, like in this case? In my opinion that would be a cleaner solution than trying to fix wrong user input.
