### ISSUE TITLE
Error when try execute evosuite library

### ISSUE THREAD

**Issue by diogogyn** [EvoSuite/evosuite#275]
I am working on a research project at my university where I have been using evosuite to generate test cases.
But I have been having a problem using the evosuite jar that both manually and via maven, I can not run the framework due to a problem with the jar.

By using the suggested setting on the evosuite page, maven automatically downloads only the "evosuite-standalone-runtime" library. And even by inserting the "evosuite" library manually I get the following issues when executing the suggested hidden commands on the site.

I also try to run the same evosuite jar show on the site and get the following errors.

These problems occur even running on other computers using java 6 or 8

![image](https://user-images.githubusercontent.com/12502113/67895870-090c8080-fb3a-11e9-86b5-aef7b02cb7e9.png)

![image](https://user-images.githubusercontent.com/12502113/67895966-2fcab700-fb3a-11e9-8c6c-9fde3c7a8ea7.png)
![image](https://user-images.githubusercontent.com/12502113/67896030-4d981c00-fb3a-11e9-894c-465e3614cb3e.png)

**Comment by jose** [comment]
Hi @diogogyn,

Are you using JRE or JDK?


--
Best,
Jose

**Comment by diogogyn** [comment]
I've have using jdk with Eclipse Juno IDE. Also, I tried import the evosuite maven in other projects in other PCs and doesn't work

**Comment by diogogyn** [comment]
Eu resolvi o problema depois de reinstalar o java e o Maven e definir as variáveis novamente. Mas, por enquanto, eu tive um problema depois de executar o teste de geração com evosuite e, em seguida, tente executar os testes de cobertura.
Eu segui os tutoriais parte 2 e 3 da página de evosuite.

Existe um tutorial publicado na página evosuite para me ajudar com isso?
![image](https://user-images.githubusercontent.com/12502113/68156764-2c18a500-ff2b-11e9-863f-49ee796ee5c1.png)
![image](https://user-images.githubusercontent.com/12502113/68156806-3fc40b80-ff2b-11e9-8d8b-fbb6686c79d6.png)
![image](https://user-images.githubusercontent.com/12502113/68156843-523e4500-ff2b-11e9-8525-a2fc9d5d1bff.png)

![image](https://user-images.githubusercontent.com/12502113/68156647-fe336080-ff2a-11e9-9a1e-e312cb2eeeb4.png)
![image](https://user-images.githubusercontent.com/12502113/68156892-63875180-ff2b-11e9-9ae1-03a7aa3f3287.png)
![image](https://user-images.githubusercontent.com/12502113/68156923-6e41e680-ff2b-11e9-8c31-a4d7e9b4fc4a.png)
![image](https://user-images.githubusercontent.com/12502113/68156952-78fc7b80-ff2b-11e9-83c9-54d0cff65bbf.png)
