### ISSUE TITLE
An ERROR occurred when starting evolution

### ISSUE THREAD

**Issue by wangcwangc** [EvoSuite/evosuite#276]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
This error occurred when running the program.
![ERROR](https://user-images.githubusercontent.com/19590572/68175541-8c0b5c00-ffbc-11e9-9059-22f31a9a641d.png)
I want to know where to define this error, I want to solve it.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. Set CP in Properties. `Properties.CP = CP;`
2. Set TARGET_CLASS. `Properties.TARGET_CLASS = targetClass;`
3. Generate. `testSuiteGenerator.generateTestSuite();`

**Comment by gofraser** [comment]
Can you please provide a class under test we can use to reproduce this?
