### ISSUE TITLE
Can not compile the generated tests

### ISSUE THREAD

**Issue by Jianwei-Wu-1** [EvoSuite/evosuite#277]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

I tried to follow the tutorial 1 to use evosuite as command line tool, but I can not compile the generated tests and there are no instructions for how to fix the class path.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]
**Running EvoSuite tests.**
1. mvn dependency:copy-dependencies
2. export CLASSPATH=target/classes:evosuite-standalone-runtime-1.0.6.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar
3. javac evosuite-tests/tutorial/*.java (Failed)

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

javac evosuite-tests/tutorial/*.java

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

Result:
roaming-4-21-244:Tutorial_Stack wujianwei$ export CLASSPATH=target/classes:evosuite-standalone-runtime-1.0.6.jar:evosuite-tests:target/dependency/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar
roaming-4-21-244:Tutorial_Stack wujianwei$ javac evosuite-tests/tutorial/*.java
evosuite-tests/tutorial/Stack_ESTest.java:10: error: package org.evosuite.runtime does not exist
import static org.evosuite.runtime.EvoAssertions.*;
                                  ^
evosuite-tests/tutorial/Stack_ESTest.java:12: error: package org.evosuite.runtime does not exist
import org.evosuite.runtime.EvoRunner;
                           ^
evosuite-tests/tutorial/Stack_ESTest.java:13: error: package org.evosuite.runtime does not exist
import org.evosuite.runtime.EvoRunnerParameters;
                           ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:9: error: package org.evosuite.runtime.annotation does not exist
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
                                      ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:14: error: package org.evosuite.runtime.sandbox does not exist
import org.evosuite.runtime.sandbox.Sandbox;
                                   ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:15: error: package org.evosuite.runtime.sandbox.Sandbox does not exist
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
                                           ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:17: error: cannot find symbol
@EvoSuiteClassExclude
 ^
  symbol: class EvoSuiteClassExclude
evosuite-tests/tutorial/Stack_ESTest.java:17: error: cannot find symbol
@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
                           ^
  symbol: class EvoRunnerParameters
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:21: error: package org.evosuite.runtime.vnet does not exist
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();
                                  ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:25: error: package org.evosuite.runtime.thread does not exist
  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);
                                     ^
evosuite-tests/tutorial/Stack_ESTest.java:17: error: cannot find symbol
@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
         ^
  symbol: class EvoRunner
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:21: error: package org.evosuite.runtime.vnet does not exist
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();
                                                                                                   ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:25: error: package org.evosuite.runtime.thread does not exist
  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);
                                                                                                    ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:25: error: package org.evosuite.runtime.thread does not exist
  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);
                                                                                                                                               ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:30: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.RuntimeSettings.className = "tutorial.Stack"; 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:31: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.GuiSupport.initialize(); 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:32: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:33: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:34: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:35: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:35: error: package org.evosuite.runtime.sandbox.Sandbox does not exist
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
                                                                                           ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:36: error: package org.evosuite.runtime.sandbox does not exist
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
                                ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:37: error: package org.evosuite.runtime.classhandling does not exist
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
                                      ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:40: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:45: error: cannot find symbol
    Sandbox.resetDefaultSecurityManager(); 
    ^
  symbol:   variable Sandbox
  location: class Stack_ESTest_scaffolding
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:53: error: package org.evosuite.runtime.jvm does not exist
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
                            ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:54: error: package org.evosuite.runtime.sandbox does not exist
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
                                ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:56: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.GuiSupport.setHeadless(); 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:57: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:58: error: package org.evosuite.runtime.agent does not exist
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
                              ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:64: error: package org.evosuite.runtime.jvm does not exist
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
                            ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:65: error: package org.evosuite.runtime.classhandling does not exist
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
                                      ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:67: error: package org.evosuite.runtime.sandbox does not exist
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
                                ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:68: error: package org.evosuite.runtime.agent does not exist
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
                              ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:69: error: package org.evosuite.runtime does not exist
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
                        ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:87: error: package org.evosuite.runtime.classhandling does not exist
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Stack_ESTest_scaffolding.class.getClassLoader() ,
                                      ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:93: error: package org.evosuite.runtime.classhandling does not exist
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Stack_ESTest_scaffolding.class.getClassLoader()); 
                                      ^
evosuite-tests/tutorial/Stack_ESTest_scaffolding.java:95: error: package org.evosuite.runtime.classhandling does not exist
    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
                                      ^
evosuite-tests/tutorial/Stack_ESTest.java:64: error: cannot find symbol
         verifyException("tutorial.Stack", e);
         ^
  symbol:   method verifyException(String,EmptyStackException)
  location: class Stack_ESTest
evosuite-tests/tutorial/Stack_ESTest.java:90: error: cannot find symbol
         verifyException("tutorial.Stack", e);
         ^
  symbol:   method verifyException(String,RuntimeException)
  location: class Stack_ESTest
40 errors
 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

Compile and run the tests

### Additional info
*Please add any information of interest here below*

OS: Mac OS Mojave, JDK 1.8.0_231, maven 3.5.0

**Comment by Teogenesr1** [comment]
Hello Jianwei-Wu, I am with this same error in my compile, how did you fixed this error? Can you help me?

**Comment by AftabHussain** [comment]
Hi, so what is the solution for this issue? I am also facing the same problem.

**Comment by apanichella** [comment]
Did you include the EvoSuite jar in the classpath? Notice that the tests use a customized JUnit runner. Plus, if you do the compilation from the command line, you'd need to add the scaffolding class to the classpath as well.

**Comment by AftabHussain** [comment]
Thank you so much! Including the evosuite jar in the classpath worked. Appreciate your help.

**Comment by apanichella** [comment]
No problem! Have fun playing with EvoSuite :)
