### ISSUE TITLE
How to change the output directory or path? 

### ISSUE THREAD

**Issue by Yamuna-Rani** [EvoSuite/evosuite#291]
I want to change the output path instead of .evosuite folder.

**Comment by VoglSebastian** [comment]
You are probably trying to set "CTG_DIR", since it is the only property set to ".evosuite" by default ( in org.evosuite.Properties)? You can set all properties with "-Dkey=value" on the command line:
-Dctg_key="dir_name"

**Comment by Yamuna-Rani** [comment]
Thanks for your reply @VoglSebastian . I used this command  -Dtest_dir="my dir path" . Now It is working fine.
