### ISSUE TITLE
Unable to use cores parameter in my pom.xml

### ISSUE THREAD

**Issue by alsh1501** [EvoSuite/evosuite#301]
I am trying to add Evosuite Maven plugin  to Spring tool Suite as shown in the image.
                  
But the evosuite does not seem to recognise the Dcores value to be  4. 

![Screen Shot 2020-06-25 at 5 24 14 PM](https://user-images.githubusercontent.com/30875194/85715212-d3d82280-b708-11ea-8744-9d7246d35770.png)

I am using evosuite version 1.0.6
But the cores configuration in my pom.xml is not working as it is not able to set  Dcores to 4,and is running with only 1 (default) core value. (though it is able to set memoryInMB option to 2000 using memoryInMB configuration). Even the command `mvn  -DmemoryInMB=2000 -Dcores=4 evosuite:generate  evosuite:export` option is working fine. 

Can you help me resolve this issue.Is there any way to set the cores value in my pom.xml. 

Is this goals argument broken in EvoSuite maven plugin.

If no, Can someone help with a way out.

**Comment by aksh1501** [comment]
Same problem for me

**Comment by jose** [comment]
Hi @alsh1501,

> the command mvn -DmemoryInMB=2000 -Dcores=4 evosuite:generate evosuite:export option is working fine.

If that command works as expected but the number of cores in the `pom.xml` doesn't, I believe your pom.xml is not properly configured.  The plugin defined in your `pom.xml` (aka screenshot) doesn't look like any example described in the documentation:
- [Maven plugin docs](https://www.evosuite.org/documentation/maven-plugin/)
- [Maven integration docs](https://www.evosuite.org/documentation/tutorial-part-2/)

I suggest you look at EvoSuite's documentation and try to fix your `pom.xml`.


--
Best,
Jose
