### ISSUE TITLE
How to integrate EvoSuite with ANT build framework

### ISSUE THREAD

**Issue by GitHubLDR** [EvoSuite/evosuite#302]
### Context
*How to integrate EvoSuite with ANT build framework*

How to use Ant to invoke EvoSuite, run test cases generated by EvoSuite and Ant to collect coverage of test cases generated by EvoSuite.

**Comment by jose** [comment]
Hi @GitHubLDR,

What do you mean by "integrate"? Could you please provide more context on this?

Do you want to use Ant to invoke EvoSuite? Do you want to use Ant to run test cases generated by EvoSuite? Do you want to use Ant to collect coverage of test cases generated by EvoSuite?




--
Best,
Jose

**Comment by GitHubLDR** [comment]
> 
> 
> Hi @GitHubLDR,
> 
> What do you mean by "integrate"? Could you please provide more context on this?
> 
> Do you want to use Ant to invoke EvoSuite? Do you want to use Ant to run test cases generated by EvoSuite? Do you want to use Ant to collect coverage of test cases generated by EvoSuite?
> 
> --
> Best,
> Jose

yes, @jose,

I want to use Ant to invoke EvoSuite, want to use Ant to run test cases generated by EvoSuite and want to use Ant to collect coverage of test cases generated by EvoSuite.


Thanks,
@GitHubLDR
