### ISSUE TITLE
unable to run evosuite test case with java 11

### ISSUE THREAD

**Issue by chitrendra** [EvoSuite/evosuite#305]
### Context
i want to update my project from java 1.8 to java 11 
my project is maven spring boot project

### Steps to Reproduce
1 spring boot maven project 
2 updating java 1.8 to 11 in pom 
3 run 'mvn compile' command

### Current Result
getting error evosuite plugin 1.0.6 not found tools.jar in jdk11/../lib/tools.jar (com.sun.tools)
 
 
### Expected result
project should compile fine

### Additional info
*Please add any information of interest here below*

**Comment by reinman1985** [comment]
I have the same problem. I have tried multiple versions of de JDK, but to no avail.

**Comment by VoglSebastian** [comment]
It should work with EvoSuite 1.1.x
