### ISSUE TITLE
Jar files for the latest release

### ISSUE THREAD

**Issue by neelofarhassan** [EvoSuite/evosuite#314]
### Context

Hello,

Could you please provide the evosuite.jar and evosuite-standalone-runtime.jar for the latest release as provided for the versions 1.0.6 and below. It would help to update the tool in automated tools like defects4j etc. 

Thanks

**Comment by jose** [comment]
Hi @neelofarhassan,

You can find the jar files in [here](https://github.com/EvoSuite/evosuite/releases/tag/v1.1.0).


--
Best,
Jose
