### ISSUE TITLE
Evosuite ended abruptly

### ISSUE THREAD

**Issue by sushmadeepthi** [EvoSuite/evosuite#33]
Hi im using evosuite in intellij idea windows 7 im getting an error while running as EVOSUITE ENDED ABRUPTLY so plz suggest me how to resolve that error

**Comment by arcuri82** [comment]
sounds like a bug.

can you provide some more info? 

does it always happen? only for some classes? is there anything in the logs of the "EvoSuite" IntelliJ tab?

**Comment by sushmadeepthi** [comment]
ya when i was executing the project many times i will get this message please provide me the solution

**Comment by arcuri82** [comment]
hi,
  without further info, I cannot look into it :(  what is displayed in the "EvoSuite" IntelliJ tab? anything under .evosuite/tmp*/logs ?

**Comment by JustinThomsen** [comment]
I am also seeing this - but probably because of user error.  

in the console log I get:
```
Going to execute command:
C:\Program Files\Java\jdk1.8.0_91\bin\java.exe  -jar  C:\Users\blahblah\.m2\repository\org\evosuite\evosuite-standalone-runtime\1.0.4-alpha2\evosuite-standalone-runtime-1.0.4-alpha2.jar  -continuous  execute  -Dspawn_process_manager_port=60548  -Dctg_memory=2000  -Dctg_cores=1  -Dctg_time_per_class=3  -Dctg_export_folder=src/evo  -Dctg_selected_cuts=com.blah.blahblah.authentication.BlahBlahUserService  -DCP_file_path=C:\Users\blahblah\AppData\Local\Temp\EvoSuite_ctg_classpath_file5651053814132032843.txt  
in folder: C:\bench\blah\blah-web
no main manifest attribute, in C:\Users\blahblah\.m2\repository\org\evosuite\evosuite-standalone-runtime\1.0.4-alpha2\evosuite-standalone-runtime-1.0.4-alpha2.jar
```

**Comment by JustinThomsen** [comment]
I think its a configuration thing - I was running it with 'Evosuite location' selected, on a mavenized project.   I get a different error when I select the maven option - but I havent dug too deep.  I'll update when I figure something out.

**Comment by arcuri82** [comment]
Hi Justin, 
 from ``C:\Program Files\Java\jdk1.8.0_91\bin\java.exe  -jar  C:\Users\blahblah\.m2\repository\org\evosuite\evosuite-standalone-runtime\1.0.4-alpha2\evosuite-standalone-runtime-1.0.4-alpha2.jar``

I can see you chose the wrong evosuite jar file, ie the ``evosuite-standalone-runtime`` instead of ``evosuite-master``

**Comment by JustinThomsen** [comment]
I changed that and got it to successfully run.  For clarity, my issue was all configuration, not a bug :)

**Comment by arcuri82** [comment]
improved the check to prevent using a wrong jar file
