### ISSUE TITLE
How to use Intellij idea plugin ?

### ISSUE THREAD

**Issue by gillesfabre34** [EvoSuite/evosuite#336]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

Hi,

I want to use the Intellij's evoSuite plugin for the Tutorial_Maven project, and I don't understand very well how to use it.

I installed the evoSuite Maven plugin, and when I run `mvn evosuite:generate`, all is ok, the tests are correctly generated.

Now, I'd like to use the IntelliJ plugin to be able to click on a class and run evosuite on the contextual menu. When I click on it, a window appears for the EvoSuite options, like said in the official tutorial. But after, I don't know exactly what I should do.

At first, I suppose that I should choose "Maven location" and select the correct repository. But where is it exactly ? I think it's inside the folder .m2/repository, but it doesn't appears in the new pop-up (hidden folder, I presume). So I don't know how to do.

On a second time, I tried to choose "Evosuite location" instead of "Maven location". I completed the JAVA_HOME field, and after... what should I do ? I can just close this pop-up and try again to click on "Run EvoSuite", which re-opens this pop-up.

I probably made some trivial mistake, but any help would be great ...

Thanks.

My system : 
- Mac OS Big Sur
- Java 8

**Comment by VoglSebastian** [comment]
Hi, 

The "Maven location" is the location of the Maven binary.
(On my system it is `/usr/bin/mvn `, but this may be different for different systems and i don't use MAC OS)
The binary is quite certainly not in `.m2/repository`.

If you want to use "EvoSuite location", you must specify, where the JAR-File of EvoSuite is located on your system.

After setting up EvoSuite, you should have a "OK"-Button to start the generation:
![image](https://user-images.githubusercontent.com/22749363/108188712-31920280-7110-11eb-967b-c9de580e590a.png)
