### ISSUE TITLE
Missing class files

### ISSUE THREAD

**Issue by zhelasoft** [EvoSuite/evosuite#339]
Hello, 

I have imported the source code into intellij. but I can not compile the project as it is missing some file such as:

import org.evosuite.xsd.CUT;
import org.evosuite.xsd.Generation;
import org.evosuite.xsd.Project;

I wonder why these files are missing, because I have directly clone the source code from github.

Thanks

**Comment by siva-naresh** [comment]
Hi. I too find the same.. How do you resolve this.
