### ISSUE TITLE
reuse of mock framework

### ISSUE THREAD

**Issue by ravikanthvaka** [EvoSuite/evosuite#34]
hi i've started working with evosuite recently...i am generating test cases by using commandline version..
i want some information regarding to your previous publication mocking environmental interactions for generating test cases with high code coverage...you mentioned the mocking framework can be reused in manual and some other cases..how it can be achieved...? plz provide some suggestions

**Comment by arcuri82** [comment]
Hi,
 for publications, please see

http://www.evosuite.org/publications/

technically, the mocking framework could be reused in manually written test cases, but we would have to write documentation to explain how to do it. but this is a quite busy period, so I doubt we will have time to do it soon... :(

**Comment by gofraser** [comment]
While making the mocking framework available independently of EvoSuite is a good idea, it does not seem to be a specific issue in EvoSuite, so I am closing this issue.
