### ISSUE TITLE
How to get method argument values in ExecutionResult?

### ISSUE THREAD

**Issue by EhsanMashhadi** [EvoSuite/evosuite#341]
Hi,

Is there any way to get the method argument values of ```coveredMethods``` field of ```ExecutionResult``` in ```getFitness``` function?

Thanks

**Comment by apanichella** [comment]
Hi, 
yes, you need to look at the class `ExecutionResult`. Assuming you are working at the test case level (e.g., using MOSA or DynaMOSA),  a chromosome is an instance of the `TestChromosome` class.

Assuming you want to check the method covered by each test case, you can use the following method to retrieve all covered data, including covered methods:

`chromosome.getLastExecutionResult().getTrace().getCoveredMethods()`

 where `chromosome` is an object of the `TestChromosome` class.

Best,
Annibale
