### ISSUE TITLE
Don't write all_goals_file and coverage_matrix

### ISSUE THREAD

**Issue by LeandroMoura3** [EvoSuite/evosuite#348]
Hello,

I tried to write the all goals files using the command -Dwrite_all_goals_file=true, but this it isn't working. The -Dwrite_covered_goals_file=true are working fine. Need any configuration to write that or it's a bug? The same thing are happen with -Dcoverage_matrix=true.

I'm using win10 and evosuite-1.1.0.jar.

**Comment by VoglSebastian** [comment]
Hi,

This option is only used in the print stats execution mode and depends on the option print goals.

You can generate the file by:
`evosuite -class <class> -projectCP <projectCP> -Dwrite_all_goals_file=true -Dprint_goals=true -printStats`

Similar, the coverage_matrix option is only supported in the `-measureCoverage` execution mode.

**Comment by LeandroMoura3** [comment]
Thank you
