### ISSUE TITLE
EvoSuite 1.1.0 does not recongnize -regressionSuite parameter.

### ISSUE THREAD

**Issue by leofernandesmo** [EvoSuite/evosuite#353]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*
After an update to EvoSuite-1.1.0, there is no more option -regressionSuite.
I used to execute this option as presented on the website: [https://www.evosuite.org/evosuiter/](https://www.evosuite.org/evosuiter/)

What happened? Is there another way to follow? 

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
`java -jar evosuite-1.1.1.jar -regressionSuite -projectCP ./subjects/jsoup18/target/classes -Dregressioncp=./subjects/jsoup18/mutants/major/3 -class org.jsoup.parser.CharacterReader -Dsearch_budget=60 -DOUTPUT_DIR=./subjects/jsoup18/nimrodj-output/EvoSuite_14`

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
`[MASTER] 17:17:03.582 [main] ERROR EvoSuite - Parsing failed.  Reason: Unrecognized option: -regressionSuite`

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*
Normal execution.

### Additional info
*Please add any information of interest here below*

**Comment by jose** [comment]
Hi @leofernandesmo,

The `-regressionSuite` mode has been removed https://github.com/EvoSuite/evosuite/commit/96f9df6e08a9f0e6071364560d1499d86d53f831. Assuming you really need that mode, I would suggest you to use commit 4715c13.



--
Best,
Jose

**Comment by leofernandesmo** [comment]
Ok, Thank you.
