### ISSUE TITLE
The class belongs to one of the packages EvoSuite cannot currently handle

### ISSUE THREAD

**Issue by m-zakeri** [EvoSuite/evosuite#357]
### Context
*EvoSuite cannot generate tests for most of the classes in some Java projects, for instance, the Apache Xerces*

### Steps to Reproduce
For all classes in the Apache xerces2-j-trunk project, EvoSuite fails to generate tests. 

### EvoSuite Arguments
`java -jar evosuite.jar -projectCP ./build/classes -class org.apache.xerces.util.URI`

### Current Result

* EvoSuite 1.0.6
* Going to generate test cases for class: org.apache.xerces.util.URI
[MASTER] 12:06:10.306 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1621496170302. Configuration id : null
java.lang.IllegalArgumentException: Cannot consider org.apache.xerces.util.URI because it belongs to one of the packages EvoSuite cannot currently handle
        at org.evosuite.executionmode.TestGeneration.generateTests(TestGeneration.java:222) ~[evosuite.jar:1.0.6]
        at org.evosuite.executionmode.TestGeneration.executeTestGeneration(TestGeneration.java:79) ~[evosuite.jar:1.0.6]
        at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:269) ~[evosuite.jar:1.0.6]
        at org.evosuite.EvoSuite.main(EvoSuite.java:302) ~[evosuite.jar:1.0.6]

**Comment by gofraser** [comment]
EvoSuite has some issues with Xerces that we don't fully understand, hence this is deactivated. I have now enabled testing of Xerces classes in 9c7b31994bf65079272fa3e5d80cacd8eed13a66; it doesn't work well, and there are some individual classes where EvoSuite will just crash. But for many others it will generate tests.
