### ISSUE TITLE
[RELEASE] 1.1.0 is not deployed to Central Maven repository

### ISSUE THREAD

**Issue by NancyChunlan** [EvoSuite/evosuite#371]
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

We cannot find evosuite 1.1.0 from central maven repo. and as checked, it's not deployed in ossrh as defined in pom.xml.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

The 1.1.0 artifacts could not be found in maven central repo: https://search.maven.org/ 
But 1.0.6 does.

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*
NA

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]
https://search.maven.org/search?q=g:org.evosuite, 1.1.0 could not be found here.
 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by RenanGreca** [comment]
Hi, this issue was closed but EvoSuite is still only up to 1.0.6 on the Maven repository. Where can I find versions 1.1.0 and 1.2.0?

The project's own repository http://www.evosuite.org/m2 is even more outdated.

**Comment by NancyChunlan** [comment]
Hi @RenanGreca 

Seems we have the 1.1.0 tag here: https://github.com/EvoSuite/evosuite/tree/v1.1.0 
Would you mind to check? Thanks!
