### ISSUE TITLE
Missing class files

### ISSUE THREAD

**Issue by lilithyang2018** [EvoSuite/evosuite#378]
Hello,

I have imported the source code into intellij. but I can not compile the project as it is missing some file such as:

import org.evosuite.xsd.CUT;
import org.evosuite.xsd.Generation;
import org.evosuite.xsd.Project;

I wonder why these files are missing, because I have directly clone the source code from github.

Thanks

**Comment by gofraser** [comment]
These files are generated automatically during build by the jaxb2 Maven plugin. Did you import the project as a Maven project in IntelliJ?

**Comment by lilithyang2018** [comment]
yes,  i've found the jaxb2-maven-plugin in the pom.xml. thanks for your explanation. i'll close this.
