### ISSUE TITLE
How does EVOSUITE verify generated tests are executable?

### ISSUE THREAD

**Issue by jiseongg** [EvoSuite/evosuite#383]
Dear EVOSUITE community,

Hi, I'm a student researching on Java test generation. I'm currently trying to understand the implementation of EVOSUITE. 

As far as I know, EVOSUITE first generates test code randomly, which is the sequence of statements (method call, constructor, etc.), and they're passed to the genetic algorithm. However, I think the most of purely randomly generated tests are not executable. My questions are here.

1. Is there any verification logic that proves generated tests are executable? If so, which part of source code I have to look?
2. Or, without explicit implementation of the module verifying the executability, is there some rules to guarantee it somehow soundly? (e.g. _constructor call_ should precede _method call_) If so, which part of source code I have to look?

Thanks in advance for any help you are able to provide.

**Comment by giograno** [comment]
Hi @jiseongg, if you are interested in how the initial tests are generated, you should have a look at the `org.evosuite.testcase.TestFactory` class (and in particular, at the `insertRandomStatement` method). This class is used by all the concrete implementations of `org.evosuite.ga.ChromosomeFactory` to randomly generate an initial population of solutions.

**Comment by jiseongg** [comment]
Hi @giograno, thank you for detailed guide! I'll look at the part you said :)
