### ISSUE TITLE
Empty test classes

### ISSUE THREAD

**Issue by rjust** [EvoSuite/evosuite#4]
EvoSuite might not manage to create at least one test case for a given SUT. Consequently, the created test class is empty (i.e., it does not contain a single test method). Such an empty test class causes test errors, such as "No runnable methods".

Would it make sense to not output the test class in this case, or at least having an option to do so?

**Comment by gofraser** [comment]
In the repo this has been changed, and EvoSuite creates a no-op test to
avoid that the test suite is empty. It does still make sense to have
EvoSuite produce output.
Cheers,
Gordon
