### ISSUE TITLE
[ERROR] Some classes are loaded be reflection before the tests are run.

### ISSUE THREAD

**Issue by justinwm** [EvoSuite/evosuite#41]
Hi There,

I am running Evosuite and encountered the following error, which says that some classes are loaded be reflection before the tests are run:

1874 [mutationTestThread] ERROR org.evosuite.runtime.classhandling.ClassStateSupport - Class com.google.common.collect.AbstractMultimap$WrappedCollection was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.

I am curious about the workarounds to resolve this issue as the log indicated:-)

Thanks very much!
Best Wishes!

**Comment by arcuri82** [comment]
Hi,
  how are you running the tests? Maven? Gradle? Ant? Eclipse? IntelliJ? etc

**Comment by justinwm** [comment]
I am running directly from command line referring to this document : http://www.evosuite.org/documentation/commandline/

For example:

java -cp ./lib/junit-4.12.jar:./lib/hamcrest-all-1.3.jar:../TargetLibraries/google-collections-1.0/lib/google-collections-1.0.jar:./lib/evosuite-standalone-runtime-1.0.2.jar:./lib/slf4j-simple-1.6.1.jar:../TargetLibraries/google-collections-1.0/evosuite-tests/evosuite-tests-30-0 org.junit.runner.JUnitCore com.google.common.collect.ImmutableSortedSet_ESTest

**Comment by arcuri82** [comment]
Hi,
  at the moment we support tests run from Maven and from Ant (this latter is not documented/released yet). In the (near) future we ll support also Gradle. But running tests directly from command line using ``org.junit.runner.JUnitCore`` is not really common (as far as I know). We could support it (eg by providing a wrapper / test executor), but anyway I would wait until JUnit 5 is out of alpha (haven't checked yet if the issue with EvoSuite reflection/instrumentation also applies to JUnit 5 as well)

cheers

**Comment by justinwm** [comment]
Hi @arcuri82 
I have tried to run the test cases using Maven. However, still has the same problem :-(
The same test cases succeed and the same test cases failed.

I think the problem may be related to the test cases that Evosuite generated instead of the way of running it.

**Comment by arcuri82** [comment]
Hi,
 yep, you would also need to re-create all the tests. btw, are you using the ``org.evosuite.runtime.InitializingListener`` as discussed at http://www.evosuite.org/documentation/maven-plugin/ ?

**Comment by gofraser** [comment]
Since the InitializingListener seems to solve this problem, I'm closing this issue. If the problem re-appears, please re-open this issue.
