### ISSUE TITLE
Does EvoSuite have options to print intermediate test suite during evolution?

### ISSUE THREAD

**Issue by jiseongg** [EvoSuite/evosuite#418]
Hi, I'm trying to use EvoSuite on some open source projects for the experiment. I want to investigate the expressiveness of the EvoSuite's search spaces, by exhaustively searching method sequences that can be generated by EvoSuite on CUT. But since I can only check the final result, I'm not sure whether I have to extend the spaces or not.
For example, I may search for builder method in the whole project, for the class only having private constructor. I have some cases about which I'm not sure I can directly apply EvoSuite without extension.

So, is there any option to see intermediate results? Or if not, could you point the source code location where I can insert some logging statement? I appreciate any help and advice you might have. Thanks.

**Comment by jose** [comment]
What kind of logging are looking for?  Fitness values during evolution?  Individuals during evolution?

**Comment by jiseongg** [comment]
Hi @jose ,
I was looking for the latter, each individual test case during evolution.

Instead of logging, I have been running EvoSuite with `-generateRandom` option, which seems to generate random test case until it reached time-out, rather than optimize test suite. At the time of writing this question, I wasn't aware of such generation strategy.

**Comment by jose** [comment]
Well, you could try to print out each individual in the population at the of the [`evolve` method](https://github.com/EvoSuite/evosuite/blob/master/client/src/main/java/org/evosuite/ga/metaheuristics/mosa/DynaMOSA.java#L70).  In any case, I'm glad the `-generateRandom` option worked for you.
