### ISSUE TITLE
Error while generating test cases for classes "LookUtils" and "ClearLookUtils"

### ISSUE THREAD

**Issue by pooyamusavi** [EvoSuite/evosuite#42]
There is a key in its configuration named "headless_mode" which is set to true by default. The tool throws exception (Headless Exception) at the class "LookUtils".  I set this key to false and EvoSuite does not throw that error but shows another exception at the class "ClearLookUtils". Actually, I got stuck with this ...

JDK: 1.8.0_65
OS: Windows 10

Below is the LookUtils.java:

import java.awt.Color;
import java.awt.Component;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.Collections;
import java.util.List;

import javax.swing.AbstractButton;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.InsetsUIResource;
import javax.swing.plaf.UIResource;

public final class LookUtils
{
  private static final String JAVA_VERSION = getSystemProperty("java.version");
  private static final String OS_NAME = getSystemProperty("os.name");
  private static final String OS_VERSION = getSystemProperty("os.version");
  public static final boolean IS_JAVA_1_4 = startsWith(JAVA_VERSION, "1.4");
  static final boolean IS_JAVA_1_4_0 = startsWith(JAVA_VERSION, "1.4.0");
  public static final boolean IS_JAVA_1_4_2_OR_LATER = (!startsWith(JAVA_VERSION, "1.4.0")) && (!startsWith(JAVA_VERSION, "1.4.1"));
  public static final boolean IS_OS_FREEBSD = startsWithIgnoreCase(OS_NAME, "FreeBSD");
  public static final boolean IS_OS_LINUX = startsWithIgnoreCase(OS_NAME, "Linux");
  public static final boolean IS_OS_OS2 = startsWith(OS_NAME, "OS/2");
  public static final boolean IS_OS_MAC = startsWith(OS_NAME, "Mac");
  public static final boolean IS_OS_WINDOWS = startsWith(OS_NAME, "Windows");
  public static final boolean IS_OS_WINDOWS_MODERN = (startsWith(OS_NAME, "Windows")) && (!startsWith(OS_VERSION, "4.0"));
  public static final boolean IS_OS_WINDOWS_XP = (startsWith(OS_NAME, "Windows")) && (startsWith(OS_VERSION, "5.1"));
  public static final boolean IS_OS_SOLARIS = startsWith(OS_NAME, "Solaris");
  public static final boolean IS_LAF_WINDOWS_XP_ENABLED = isWindowsXPLafEnabled();
  public static final boolean IS_NETBEANS;
  public static final boolean IS_LOW_RESOLUTION = isLowResolution();
  private static boolean loggingEnabled = true;

  static
  {
    IS_NETBEANS = isNetBeans();
    if (IS_NETBEANS) {
      //ClearLookManager.getMode();
    }
  }

  public static String getSystemProperty(String key)
  {
    try
    {
      return System.getProperty(key);
    }
    catch (SecurityException e)
    {
      log("Can't read the System property " + key + ".");
    }
    return null;
  }

  public static String getSystemProperty(String key, String defaultValue)
  {
    try
    {
      return System.getProperty(key, defaultValue);
    }
    catch (SecurityException e)
    {
      log("Can't read the System property " + key + ".");
    }
    return defaultValue;
  }

  private static boolean isWindowsXPLafEnabled()
  {
    return (IS_OS_WINDOWS_XP) && (IS_JAVA_1_4_2_OR_LATER) && (Boolean.TRUE.equals(Toolkit.getDefaultToolkit().getDesktopProperty("win.xpstyle.themeActive"))) && (getSystemProperty("swing.noxp") == null);
  }

  public static boolean isTrueColor(Component c)
  {
    return c.getToolkit().getColorModel().getPixelSize() >= 24;
  }

  public static void installNarrowMargin(AbstractButton b, String propertyPrefix)
  {
    Object value = b.getClientProperty("jgoodies.isNarrow");
    boolean isNarrow = Boolean.TRUE.equals(value);
    String defaultsKey = propertyPrefix + (isNarrow ? "narrowMargin" : "margin");

```
Insets insets = b.getMargin();
if ((insets == null) || ((insets instanceof UIResource))) {
  b.setMargin(UIManager.getInsets(defaultsKey));
}
```

  }

  public static Insets createButtonMargin(boolean narrow)
  {
    int pad = narrow? 4 : 14;
    return IS_LOW_RESOLUTION ? new InsetsUIResource(2, pad, 1, pad) : new InsetsUIResource(3, pad, 3, pad);
  }

  public static Color getSlightlyBrighter(Color color)
  {
    return getSlightlyBrighter(color, 1.1F);
  }

  public static Color getSlightlyBrighter(Color color, float factor)
  {
    float[] hsbValues = new float[3];
    Color.RGBtoHSB(color.getRed(), color.getGreen(), color.getBlue(), hsbValues);

```
float hue = hsbValues[0];
float saturation = hsbValues[1];
float brightness = hsbValues[2];
float newBrightness = Math.min(brightness * factor, 1.0F);
return Color.getHSBColor(hue, saturation, newBrightness);
```

  }

  public static void setLookAndTheme(LookAndFeel laf, Object theme)
    throws UnsupportedLookAndFeelException
  {
    UIManager.setLookAndFeel(laf);
  }

  public static Object getDefaultTheme(LookAndFeel laf)
  {
    return null;
  }

  public static List getInstalledThemes(LookAndFeel laf)
  {
    return Collections.EMPTY_LIST;
  }

  public static void setLoggingEnabled(boolean enabled)
  {
    loggingEnabled = enabled;
  }

  public static void log()
  {
    if (loggingEnabled) {
      System.out.println();
    }
  }

  public static void log(String message)
  {
    if (loggingEnabled) {
      System.out.println("JGoodies Looks: " + message);
    }
  }

  private static boolean isLowResolution()
  {
      System.out.println(Toolkit.getDefaultToolkit().getScreenResolution());
      return Toolkit.getDefaultToolkit().getScreenResolution() < 120;
  }

  private static boolean isNetBeans()
  {
    String property = getSystemProperty("netbeans.buildnumber");
    boolean hasNetBeansBuildNumber = (property != null) && (property.length() > 0);
    if (hasNetBeansBuildNumber) {
      log("NetBeans detected - dobry den!");
    }
    return hasNetBeansBuildNumber;
  }

  private static boolean startsWith(String str, String prefix)
  {
    return (str != null) && (str.startsWith(prefix));
  }

  private static boolean startsWithIgnoreCase(String str, String prefix)
  {
    return (str != null) && (str.toUpperCase().startsWith(prefix.toUpperCase()));
  }
}

---

---

---

Below is the ClearLookUtils.java:

import javax.swing.JComponent;
import javax.swing.border.Border;

public final class ClearLookUtils
{
  private static final String CLEARLOOK_KEY = "ClearLook";
  private static final Object MARKER = "marker";

  public static boolean hasCheckedBorder(JComponent component)
  {
    return component.getClientProperty("ClearLook") != null;
  }

  public static Border getStoredBorder(JComponent component)
  {
    Object borderOrMarker = component.getClientProperty("ClearLook");
    return borderOrMarker == MARKER ? null : (Border)borderOrMarker;
  }

  public static void storeBorder(JComponent component, Border border)
  {
    Object borderOrMarker;
    //Object borderOrMarker;
    if (border == null) {
      borderOrMarker = MARKER;
    } else {
      borderOrMarker = border;
    }
    component.putClientProperty("ClearLook", borderOrMarker);
  }
}

**Comment by gofraser** [comment]
What specifically is the error? Using the latest release (1.0.3) as well as the current version in the Git repository I get no errors for ClearLookUtils, and LookUtils works fine if headless mode is deactivated.

**Comment by gofraser** [comment]
Since this seems to work fine for me, I'll close this issue. Please re-open if the problem persists.
