### ISSUE TITLE
Dealing with classes routes using CMD in windows.

### ISSUE THREAD

**Issue by Pablocgdev** [EvoSuite/evosuite#45]
Hello, I'm trying to create test classes with CMD in windows. In one of the example projects provided in the documentations, I can make it work flawlessly, but I can't generate test classes in more complex paths.

With this route (....\spark-master\src\main\java\spark) all I have to do to have my generated classes is: **java -jar evosuite.jar -class spark.ClassName -projectCP target/classes** and I get the test classes.

With this route (...\java8-tutorial-master\src\com\winterbe\java8\samples\time) I can't make it work. I've tried adding to the -class in my script the complete route using "\" and "." and many kind of literall routes, as well using just **-class samples.Time** or **-class winterbe.Time** .

Can you help me understanding how to generate test classes from CMD in those paths?

**Comment by arcuri82** [comment]
Hi,
 what you mean with CMD?

in ``....\spark-master\src\main\java\spark``, I assume you are using Maven/Gradle (ie, by looking at the standard structure ``src\main\java``), which will make ``-projectCP target/classes`` work, as that is where the bytecode is compiled (ES works at bytecode level, not on the source files). But that does not seem the case for  ``...\java8-tutorial-master\src\com\winterbe\java8\samples\time``. You need to add to ``-projectCP`` where the ``.class`` files are compiled

**Comment by Pablocgdev** [comment]
Thanks, it is solved now.
