### ISSUE TITLE
Can EvoSuite Generate Comments?

### ISSUE THREAD

**Issue by antonio-mastropaolo** [EvoSuite/evosuite#452]
Hi all,

I was wondering if there is a way to let EvoSuite generate comments.

Thanks for any help you can provide on this.

**Comment by jose** [comment]
Hi @antonio-mastropaolo,

EvoSuite may generate a header comment with coverage information for each test if you enable the `test_comments` property.  What kind of comments are you interested in?


--
Best,
Jose
