### ISSUE TITLE
Why is GA+DSE not being used?

### ISSUE THREAD

**Issue by SBOne-Kenobi** [EvoSuite/evosuite#458]
Hi, evosuite community!

Why is your approach described [here](https://www.evosuite.org/wp-content/papercite-data/pdf/issre13_dse.pdf) not being used now?

There are a lot of legacy and deprecated classes, so probably, I've missed something, and it's being used... If it is, please clarify the place of the approach and how to configure it.

It seems very useful and has high potential. Are there some issues with it, or is it hard to support and develop? 

Thanks in advance!

**Comment by SBOne-Kenobi** [comment]
Oh, I found it in local search components (:

**Comment by SBOne-Kenobi** [comment]
I see an application of DSE in local search, but I don't know how to turn it on or how to force applying of DSE. Could you help me with it?

**Comment by jose** [comment]
@ilebrero, @jgaleotti, any chance you could answer @SBOne-Kenobi's question?
