### ISSUE TITLE
EvoSuite non deterministic

### ISSUE THREAD

**Issue by martinezmatias** [EvoSuite/evosuite#48]
Hello Gordon, Andrea et all
For some classes, I executed Evosuite several times and the results, i.e., test cases generated, are different. Also the measures printed (Coverage, Total number of goals, fitness, statements, nr of generations) differ. In the command, I include -seed  and  -Drandom_seed  arguments.
I attach one example  (classes, command and output from two executions)  taken from Defects4J for ease the reproducibility of this issue. I generated the jar from commit 
608a41147e224af6889ba4c70b79f94dbbcc498f (not included in the attachment). I executed the same command two times and the output are different.

Thanks for you help
Best regards
Matias

[exampleRandom.zip](https://github.com/EvoSuite/evosuite/files/384306/exampleRandom.zip)

**Comment by monperrus** [comment]
regarding this determinism problem, is the seed given to the master process always passed to the spawned child processes?

**Comment by gofraser** [comment]
I have located and fixed several sources of non-determinism recently, but there is still one issue in the use of Mockito mocks and reflection that I haven't managed to overcome. The version in the repository should be deterministic when deactivating mocking and private reflection (which are currently on by default in the main branch). I'll let you know once I've had the time to look into this last issue deeper.

However, note that if you set a time limit as stopping condition, you will not get exactly the same result as time can be influenced by other processes running on the same machine. If you want exactly the same test suite, you'd probably need -Dstopping_condition=MaxStatements -Dsearch_budget=500000 or something like that -- the number of statements executed is deterministic. 

That being said, why is it important to get deterministic results? It is important for debugging EvoSuite, but what's the usecase that would require deterministic generation of test cases?

**Comment by monperrus** [comment]
Thanks Gordon.

> why is it important to get deterministic results?

- debugging
- reproducible automated experiments for the sake of open-science.

**Comment by gofraser** [comment]
Note that EvoSuite has a range of tests to check that it is deterministic, so we are generally trying to make it deterministic, precisely for the reasons you listed.

For debugging you should probably just set a statement limit rather than a time limit. Breakpoints etc will affect timing anyway.

If you require a specific seed to reproduce an experiment result, then arguably you should redesign the experiment: Experiments with a stochastic tool shouldn't be based on a single run.

**Comment by monperrus** [comment]
> If you require a specific seed to reproduce an experiment result, then arguably you should redesign the experiment: Experiments with a stochastic tool shouldn't be based on a single run.

I slightly disagree. The scientific findings shouldn't be based on a single run (external validity). However, the experiment itself, even with multiple runs, say `n` runs, should be `n` times exactly reproducible with `n` different seeds.

**Comment by monperrus** [comment]
> The version in the repository should be deterministic when deactivating mocking and private reflection (which are currently on by default in the main branch).

To be sure, do you mean setting `functional_mocking_percent` and `p_reflection_on_private` to 0?

**Comment by gofraser** [comment]
No, set `-Dp_functional_mocking=0 -Dp_reflection_on_private=0` - with the parameters you listed you would enable mocking and reflection from the start (that's the percentage of the search budget used up before mocking/reflection are considered).

If you can send me specific classes/configurations that lead to non-deterministic results please let me know then I can have a look at them (once I find the time).

**Comment by monperrus** [comment]
> `functional_mocking_percent` and `p_reflection_on_private` 

Do you mean setting them to 1 or 2 instead?

What about `reflection_start_percent` and `p_functional_mocking`?

**Comment by gofraser** [comment]
Just use `-Dp_functional_mocking=0 -Dp_reflection_on_private=0`

If for whatever reason you must use the percentage parameters then set them to 1.

**Comment by monperrus** [comment]
Thanks. To recap, **only** using `-Dp_functional_mocking=0 -Dp_reflection_on_private=0` should do the job?

**Comment by monperrus** [comment]
Good news, with those parameters, we get deterministic results. Thanks again @gofraser.

**Comment by monperrus** [comment]
We come back :-)  we get deterministic results on the same machine, but the tests change across machines (same JVM). 

In particular, the order of tests may be different (e.g., test19 in one run corresponds to test18 in another).

Is there a Set somewhere responsible for this, for which we can change the implementation so as to have a guarantee on the order?

**Comment by gofraser** [comment]
We are already using Linked-* versions of collections, so it's unlikely the answer is as simple as that. 
Can you try running with:
-Dassertions=false
-Dminimize=false
-Djunit_check=false
-Dinline=false
and see if that gives you deterministic results? If so, it's more likely a timeout in any of the many additional phases.

**Comment by monperrus** [comment]
OK, we'll try.

> If so, it's more likely a timeout in any of the many additional phases.

Do you mean that even by using max-statements, there are inner timeouts on which the machine performance can impact the results?

**Comment by gofraser** [comment]
Yes, each phase has a timeout. In particular, minimisation, assertion generation, and the compile/flaky checks can take very long.

**Comment by monperrus** [comment]
OK and 
    -Dassertions=false
    -Dminimize=false 
     -Djunit_check=false

disable those phases or disable their respective timeouts?

**Comment by gofraser** [comment]
It disables these phases.

You can set individual timeouts using:

-Dminimization_timeout=...
-Dassertion_timeout=...
-Djunit_check_timeout=...
-Dwrite_junit_timeout=...
-Dinitialization_timeout=...

(values in seconds, defaults are 60s except for initialisation which is 120s)

**Comment by zhongxingyu** [comment]
Hi Gordon

We have tried the following setting as suggested by you:

-Dassertions=false
-Dminimize=false
-Djunit_check=false
-Dinline=false

We still do not get deterministic results across different machines, and it seems that the differences across different machines are somewhat larger. Thanks for your help!

**Comment by gofraser** [comment]
Any suggestions or more concrete hints on how I should debug this?

I am still not convinced this is really a critical feature. For debugging it's sufficient if it is deterministic on one machine; for external validity of experiments it's sufficient if you have designed your experiment in a way that allows you to statistically get the same results even with different concrete test suites. The experiment _is_ reproducible if you get the same findings, not if you get the same test suites.

**Comment by zhongxingyu** [comment]
Currently no, we will come back if we have further progress on this problem. Thanks a lot for sharing your insight about the experimental design. We deeply appreciate your support and help all the way along!

**Comment by gofraser** [comment]
One thing we could try would be that you run EvoSuite on the class where you observe the problem using -Dlog.level=debug for the smallest search_budget that's sufficient to reproduce the problem, and with the simplest possible configuration (i.e., turn off assertions, minimize, junit_check, etc), then I could compare the log files from the two different machines and see where they diverge (or produce my own for comparison, if you give me the exact configuration)

**Comment by zhongxingyu** [comment]
Thanks for your advice. I have minimized the search budget to 500 when MaxStatements is used as the stopping condition, using some smaller values like 200, 300 will hide the problem in my case. As the log file is still large when the debug mode is enabled, I will give you my configuration. 
I run EvoSuite on the org.apache.commons.math.analysis.solvers.UnivariateRealSolverUtils class of Math-85 in the Defects4j repository, the jdk version I used is jdk1.8.0_101, and I run EvoSuite with the following setting:
" -seed 88 -Dlog.level=debug -Dassertions=false -Dminimize=false -Djunit_check=false -Dinline=false -Dglobal_timeout=120 -Dsearch_budget=500  -Dstopping_condition=MaxStatements  -Dno_runtime_dependency=true -Dsandbox=false -Dp_reflection_on_private=0.0 -Dreflection_start_percent=1.0 -Dp_functional_mocking=0.0 -Dfunctional_mocking_percent=1.0 -mem 2000 "
I am always available to provide any further information needed. Thanks again for your generous help!

**Comment by gofraser** [comment]
I tried this on a Mac and a Linux machine and saw some differences in the order in which classes are stored during the initial static analysis. I am not sure if that's due to reflection or the order in which files are returned by the FS, but after switching to (sorted) TreeSets for some part of that analysis I get the same result for this specific call on my Mac and the Linux machine. Let me know if you have other examples.

**Comment by gofraser** [comment]
The TreeSet change is in c79d055d4c6cf439d499e489ee97b355606bb19d btw

**Comment by zhongxingyu** [comment]
Excellent. According to your latest commit, we get deterministic results across different machines for this specific example using the following Evosuite setting:

" -seed 88 -Dassertion_timeout=900 -Dminimization_timeout=900 -Djunit_check_timeout=900 -Dwrite_junit_timeout=180 -Dinitialization_timeout=180 -Dglobal_timeout=10000  -Dsearch_budget=1000000 -Dstopping_condition=MaxStatements -Dno_runtime_dependency=false -Dsandbox=false -Dp_reflection_on_private=0.0 -Dreflection_start_percent=1.0 -Dp_functional_mocking=0.0 -Dfunctional_mocking_percent=1.0 -mem 2000 "

We will try further to see whether it is the case for other scenarios. BTW, is it possible for you to give us some professional advice on the appropriate values used for Dminimization_timeout, Djunit_check_timeout, Dwrite_junit_timeout, Dinitialization_timeout, Dglobal_timeout, in particular Dsearch_budget and Dglobal_timeout (when MaxStatements is used as the stopping condition) in a  general context (I mean, what do you think are the suitable values for these parameters when generating tests for a random java class? ). For this specific example and my EvoSuite setting, EvoSuite runs about 1.5 hours. 

Really appreciate your generous time and kind help! @gofraser

**Comment by gofraser** [comment]
Thanks for confirming. When using mockito-mocking there may still be some cases of non-determinism which seems out of our control, but other than that I assume it works.
