### ISSUE TITLE
How can I launch test for only a class/selected class?

### ISSUE THREAD

**Issue by Pablocgdev** [EvoSuite/evosuite#49]
It would save a lot of time, when the project is big filtering classes is a really good feature. I've seen in [https://github.com/EvoSuite/evosuite/issues/27] that excluding is not possible but including is. Is it possible to tweak it so you only generate tests for a selected class?

I know you can just move the plugin to the folder, delete target/classes and run the command but is kinda a bad solution.

**Comment by gofraser** [comment]
If you are running EvoSuite from the command line you can specify a target class (-class name.of.class) or a prefix (-prefix your.package.prefix) or a specific class path entry (-target some/module/target/classes). Is this a feature request for the Maven plugin?

**Comment by gofraser** [comment]
Besides the above mentioned -class / -prefix / -target options on the command line, you can also specify -Dctg_selected_cuts=... or -Dctg_selected_cuts_file_location=... to the maven plugin, so I'm closing this issue.
