### ISSUE TITLE
Non determinism with different budgets

### ISSUE THREAD

**Issue by mausotog** [EvoSuite/evosuite#56]
Hello.
I have ran into a problem regarding the determinism of Evosuite when creating test suites using different budgets.
I am currently working with defects4j, which uses Evosuite to create test suites.
I have looked into detail of several of the test suites created, and it makes me believe that the test suites are not created in a deterministic way when using different budgets.
I have ran Evosuite using the same seed (ex: "1") and the only difference being the budget, in one of them I ran it with budget 180 seconds, in the next one with a budget of 1800 seconds.
I would expect that the test suite created in 180 seconds would be the beginning of the test suite created in 1800 seconds.
The result that I get is two test suites that are very different.
Example:
3 min budget
--------
/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 19:36:29 GMT 2016
 */

package org.apache.commons.math3.ode;

import static org.junit.Assert.*;
import org.junit.Test;
import org.apache.commons.math3.ode.events.EventHandler;
import org.apache.commons.math3.ode.nonstiff.DormandPrince54Integrator;
import org.apache.commons.math3.ode.nonstiff.DormandPrince853Integrator;
import org.apache.commons.math3.ode.nonstiff.GraggBulirschStoerIntegrator;
import org.apache.commons.math3.ode.nonstiff.MidpointIntegrator;
import org.apache.commons.math3.ode.nonstiff.ThreeEighthesIntegrator;
import org.apache.commons.math3.ode.sampling.StepHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.EvoSuiteLocalAddress;
import org.evosuite.runtime.testdata.EvoSuiteRemoteAddress;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class AbstractIntegrator_ESTest extends AbstractIntegrator_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      double[] doubleArray0 = new double[9];
      DormandPrince853Integrator dormandPrince853Integrator0 = new DormandPrince853Integrator(0.0, 0.0, doubleArray0, doubleArray0);
      dormandPrince853Integrator0.getName();
      assertEquals(2147483647, dormandPrince853Integrator0.getMaxEvaluations());
  }

  @Test
  public void test01()  throws Throwable  {
      DormandPrince54Integrator dormandPrince54Integrator0 = new DormandPrince54Integrator(0.0, (-4003.636), (-2081.8607640646514), 2495.6457800202284);
      double double0 = dormandPrince54Integrator0.getCurrentSignedStepsize();
      assertEquals(0.0, double0, 0.01D);
      assertEquals(2147483647, dormandPrince54Integrator0.getMaxEvaluations());
  }

  @Test
  public void test02()  throws Throwable  {
      MidpointIntegrator midpointIntegrator0 = new MidpointIntegrator(94326.0);
      midpointIntegrator0.getStepHandlers();
      assertEquals(2147483647, midpointIntegrator0.getMaxEvaluations());
      assertEquals(Double.NaN, midpointIntegrator0.getCurrentSignedStepsize(), 0.01D);
      assertEquals(Double.NaN, midpointIntegrator0.getCurrentStepStart(), 0.01D);
  }

  @Test
  public void test03()  throws Throwable  {
      DormandPrince54Integrator dormandPrince54Integrator0 = new DormandPrince54Integrator((-0.04471061572777259), (-9.147934308113573), (-0.04432804463693693), (-9.147934308113573));
      dormandPrince54Integrator0.clearEventHandlers();
      assertEquals(2147483647, dormandPrince54Integrator0.getMaxEvaluations());
  }

  @Test
  public void test04()  throws Throwable  {
      DormandPrince54Integrator dormandPrince54Integrator0 = new DormandPrince54Integrator(1.3333333333333333, 0.0, 358.2532442203, 2479.9074609852114);
      int int0 = dormandPrince54Integrator0.getMaxEvaluations();
      assertEquals(Integer.MAX_VALUE, int0);
  }

  @Test
  public void test05()  throws Throwable  {
      DormandPrince54Integrator dormandPrince54Integrator0 = new DormandPrince54Integrator(0.0, (-4.422011983080043), 462.49369, 462.49369);
      dormandPrince54Integrator0.getEvaluations();
      assertEquals(2147483647, dormandPrince54Integrator0.getMaxEvaluations());
  }

  @Test
  public void test06()  throws Throwable  {
      MidpointIntegrator midpointIntegrator0 = new MidpointIntegrator(94326.0);
      midpointIntegrator0.clearStepHandlers();
      assertEquals(Double.NaN, midpointIntegrator0.getCurrentStepStart(), 0.01D);
      assertEquals(2147483647, midpointIntegrator0.getMaxEvaluations());
      assertEquals(Double.NaN, midpointIntegrator0.getCurrentSignedStepsize(), 0.01D);
  }

  @Test
  public void test07()  throws Throwable  {
      ThreeEighthesIntegrator threeEighthesIntegrator0 = new ThreeEighthesIntegrator(0.0);
      double double0 = threeEighthesIntegrator0.getCurrentStepStart();
      assertEquals(Double.NaN, threeEighthesIntegrator0.getCurrentSignedStepsize(), 0.01D);
      assertEquals(Double.NaN, double0, 0.01D);
      assertEquals(2147483647, threeEighthesIntegrator0.getMaxEvaluations());
  }

  @Test
  public void test08()  throws Throwable  {
      MidpointIntegrator midpointIntegrator0 = new MidpointIntegrator(3901.7717);
      midpointIntegrator0.addStepHandler((StepHandler) null);
      assertEquals(Double.NaN, midpointIntegrator0.getCurrentSignedStepsize(), 0.01D);
      assertEquals(Double.NaN, midpointIntegrator0.getCurrentStepStart(), 0.01D);
      assertEquals(2147483647, midpointIntegrator0.getMaxEvaluations());
  }

  @Test
  public void test09()  throws Throwable  {
      double[] doubleArray0 = new double[1];
      GraggBulirschStoerIntegrator graggBulirschStoerIntegrator0 = new GraggBulirschStoerIntegrator(1000.0, 0.0, doubleArray0, doubleArray0);
      // Undeclared exception!
      try {
        graggBulirschStoerIntegrator0.initializeStep(false, 2410, doubleArray0, 0.0, doubleArray0, doubleArray0, doubleArray0, doubleArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test10()  throws Throwable  {
      GraggBulirschStoerIntegrator graggBulirschStoerIntegrator0 = new GraggBulirschStoerIntegrator(3622.9633996963657, (-1555.425658269), 1052.42921242, 0.0);
      graggBulirschStoerIntegrator0.addEventHandler((EventHandler) null, 0.0, (-1124.365343921062), (-1));
      graggBulirschStoerIntegrator0.getEventHandlers();
      assertEquals(2147483647, graggBulirschStoerIntegrator0.getMaxEvaluations());
  }

  @Test
  public void test11()  throws Throwable  {
      DormandPrince54Integrator dormandPrince54Integrator0 = new DormandPrince54Integrator(1.3333333333333333, 0.0, 358.2532442203, 2479.9074609852114);
      assertEquals(2147483647, dormandPrince54Integrator0.getMaxEvaluations());
      
      dormandPrince54Integrator0.setMaxEvaluations(0);
      assertEquals(0, dormandPrince54Integrator0.getMaxEvaluations());
  }
}

--------

30 min budget:
--------
/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 17 11:07:18 GMT 2016
 */

package org.apache.commons.math3.ode;

import static org.junit.Assert.*;
import org.junit.Test;
import org.apache.commons.math3.ode.events.EventHandler;
import org.apache.commons.math3.ode.nonstiff.DormandPrince853Integrator;
import org.apache.commons.math3.ode.nonstiff.EulerIntegrator;
import org.apache.commons.math3.ode.nonstiff.GillIntegrator;
import org.apache.commons.math3.ode.nonstiff.GraggBulirschStoerIntegrator;
import org.apache.commons.math3.ode.nonstiff.ThreeEighthesIntegrator;
import org.apache.commons.math3.ode.sampling.StepHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.EvoSuiteLocalAddress;
import org.evosuite.runtime.testdata.EvoSuiteRemoteAddress;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class AbstractIntegrator_ESTest extends AbstractIntegrator_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      EulerIntegrator eulerIntegrator0 = new EulerIntegrator((-0.7856738509935047));
      eulerIntegrator0.getName();
      assertEquals(Double.NaN, eulerIntegrator0.getCurrentSignedStepsize(), 0.01D);
      assertEquals(Double.NaN, eulerIntegrator0.getCurrentStepStart(), 0.01D);
      assertEquals(2147483647, eulerIntegrator0.getMaxEvaluations());
  }

  @Test
  public void test01()  throws Throwable  {
      GillIntegrator gillIntegrator0 = new GillIntegrator(676.052512391);
      double double0 = gillIntegrator0.getCurrentSignedStepsize();
      assertEquals(Double.NaN, double0, 0.01D);
      assertEquals(Double.NaN, gillIntegrator0.getCurrentStepStart(), 0.01D);
      assertEquals(2147483647, gillIntegrator0.getMaxEvaluations());
  }

  @Test
  public void test02()  throws Throwable  {
      EulerIntegrator eulerIntegrator0 = new EulerIntegrator(0.0);
      eulerIntegrator0.getStepHandlers();
      assertEquals(Double.NaN, eulerIntegrator0.getCurrentStepStart(), 0.01D);
      assertEquals(2147483647, eulerIntegrator0.getMaxEvaluations());
      assertEquals(Double.NaN, eulerIntegrator0.getCurrentSignedStepsize(), 0.01D);
  }

  @Test
  public void test03()  throws Throwable  {
      DormandPrince853Integrator dormandPrince853Integrator0 = new DormandPrince853Integrator(277.3233, (-302.778320964826), (-302.778320964826), 277.3233);
      dormandPrince853Integrator0.clearEventHandlers();
      assertEquals(2147483647, dormandPrince853Integrator0.getMaxEvaluations());
  }

  @Test
  public void test04()  throws Throwable  {
      EulerIntegrator eulerIntegrator0 = new EulerIntegrator(0.0);
      int int0 = eulerIntegrator0.getMaxEvaluations();
      assertEquals(Integer.MAX_VALUE, int0);
      assertEquals(Double.NaN, eulerIntegrator0.getCurrentStepStart(), 0.01D);
      assertEquals(Double.NaN, eulerIntegrator0.getCurrentSignedStepsize(), 0.01D);
  }

  @Test
  public void test05()  throws Throwable  {
      DormandPrince853Integrator dormandPrince853Integrator0 = new DormandPrince853Integrator(Double.NaN, 4437.8, 1288.9, 4437.8);
      dormandPrince853Integrator0.getEvaluations();
      assertEquals(2147483647, dormandPrince853Integrator0.getMaxEvaluations());
  }

  @Test
  public void test06()  throws Throwable  {
      double[] doubleArray0 = new double[6];
      GraggBulirschStoerIntegrator graggBulirschStoerIntegrator0 = new GraggBulirschStoerIntegrator((-55.43250082), 2549.5, doubleArray0, doubleArray0);
      graggBulirschStoerIntegrator0.clearStepHandlers();
      assertEquals(2147483647, graggBulirschStoerIntegrator0.getMaxEvaluations());
  }

  @Test
  public void test07()  throws Throwable  {
      EulerIntegrator eulerIntegrator0 = new EulerIntegrator(0.0);
      double double0 = eulerIntegrator0.getCurrentStepStart();
      assertEquals(Double.NaN, eulerIntegrator0.getCurrentSignedStepsize(), 0.01D);
      assertEquals(Double.NaN, double0, 0.01D);
      assertEquals(2147483647, eulerIntegrator0.getMaxEvaluations());
  }

  @Test
  public void test08()  throws Throwable  {
      GraggBulirschStoerIntegrator graggBulirschStoerIntegrator0 = new GraggBulirschStoerIntegrator(0.0, 0.0, 0.0, 0.0);
      graggBulirschStoerIntegrator0.addStepHandler((StepHandler) null);
      assertEquals(2147483647, graggBulirschStoerIntegrator0.getMaxEvaluations());
  }

  @Test
  public void test09()  throws Throwable  {
      ThreeEighthesIntegrator threeEighthesIntegrator0 = new ThreeEighthesIntegrator(1854.895619);
      double[] doubleArray0 = new double[7];
      // Undeclared exception!
      try {
        threeEighthesIntegrator0.computeDerivatives(1854.895619, doubleArray0, doubleArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test10()  throws Throwable  {
      GillIntegrator gillIntegrator0 = new GillIntegrator(0.0);
      gillIntegrator0.addEventHandler((EventHandler) null, (-1.0), 0.0, (-1403));
      gillIntegrator0.getEventHandlers();
      assertEquals(2147483647, gillIntegrator0.getMaxEvaluations());
      assertEquals(Double.NaN, gillIntegrator0.getCurrentStepStart(), 0.01D);
      assertEquals(Double.NaN, gillIntegrator0.getCurrentSignedStepsize(), 0.01D);
  }

  @Test
  public void test11()  throws Throwable  {
      GillIntegrator gillIntegrator0 = new GillIntegrator(676.052512391);
      gillIntegrator0.setMaxEvaluations(1135);
      assertEquals(1135, gillIntegrator0.getMaxEvaluations());
  }
}

--------

**Comment by gofraser** [comment]
EvoSuite does not incrementally build test suites, it uses a genetic algorithm to evolve them. If you change the search budget, this changes the result. See http://www.evosuite.org/wp-content/papercite-data/pdf/tse12_evosuite.pdf if you want to know how it works. It's not a bug, it's a feature...

**Comment by mausotog** [comment]
Thank you

**Comment by monperrus** [comment]
#48 may help here:

> However, note that if you set a time limit as stopping condition, you will not get exactly the same result as time can be influenced by other processes running on the same machine. If you want exactly the same test suite, you'd probably need -Dstopping_condition=MaxStatements -Dsearch_budget=500000
