### ISSUE TITLE
evosuite stops test case generation after several hours

### ISSUE THREAD

**Issue by Akrabor** [EvoSuite/evosuite#6]
Hi,
as mentioned evosuite stops working from time to time when generating tests for a relatively big project (~4000 classes). There is no error message, it just gets stuck at "starting evolution". I changed some settings in the properties file to give it more computing time. The same setup works fine with other projects though (up to 3000 classes). At the moment I have to log which packages are covered and restart tcg for the rest of them, which works for a while but is a little inconvenient of course. Do you have any suggestions?

**Comment by arcuri82** [comment]
To be of help, I need some more info :) 

How are you running EvoSuite? From executable jar from command line? If yes, with which input? Are you running with Maven plugin? From IntelliJ? How do you know that it "stop working"? Does it hang or crash? Which operating system are you using? etc.

**Comment by Akrabor** [comment]
sure, sorry for that :) 

Setup is: 
ubuntu 14.04, 
java 1.8 32 bit 
ant 1.9.3
evosuite 1.0.1

I call run the jar from an ant script:
```
<target name="generate-tests" depends="compile">
          <java jar="${evosuite.dir}/evosuite-1.0.1.jar" fork="true">
                  <arg value="-target"/>
                  <arg value="${build.main.dir}" />
          </java>
</target>
```

Apparently it hangs, derived from the fact that I let it run over night and see the next morning it did not generate any new tests for the last several hours.

**Comment by arcuri82** [comment]
You can try to redirect the standout of EvoSuite to some log files and see if there is any ERROR/WARN there. Eg, it could just be that it runs out of memory and, if that is the case, you can increase it with the "-mem" option

**Comment by Akrabor** [comment]
This is a good idea, thanks.
I already increased the memory with
ctg_memory=5000 in the evosuite.properties file, but maybe this is still not enough or the logs will give me another hint.

**Comment by arcuri82** [comment]
5000MB?  but you wrote "java 1.8 32 bit"... if you are using a 32 bit machine, no surprise if it crash after going above 2GB... :)

**Comment by Akrabor** [comment]
um.... sorry. this was stupid. I switched to 32 bit because of some library incompatibilities and forgot to apply that to the setup.

**Comment by arcuri82** [comment]
at any rate ctg_memory only applies to CTG mode (which is not the default), which does not seem the case from how you are running it from Ant. Inputs passed by process parameters are validated (and so you would get an exception if you try to set ctg_memory outside the CTG mode), but not the ones from evosuite.properties

**Comment by Akrabor** [comment]
Ah okay. 
Is there a more detailed list of possible parameters available somewhere? Or could you give some hints how to improve a standard call like above in order to get a suite with good coverage? Like, which timeouts/resource limits could be extended etc. The computation time is not the problem, the quality of the output is more interesting.

To give you some context, I work at this project: https://bitbucket.org/jensdietrich/xcorpus. It consists of a large cluster of open source projects (~100), each of them in need of a test suite as comprehensive as possible.

**Comment by arcuri82** [comment]
look at http://www.evosuite.org/documentation/commandline/

in particular, you might want to play with "-mem" (eg 2000mb) and "-Dsearch_budget" (300 seconds)

**Comment by Akrabor** [comment]
alright, thanks for the tip - especially for the search budget option, this is what I was looking for.
