### ISSUE TITLE
Fatal crash on main EvoSuite process

### ISSUE THREAD

**Issue by yevsh** [EvoSuite/evosuite#64]
Getting error:

[INFO] [MASTER] 09:34:09.369 [main] WARN  ProjectAnalyzer - Cannot initialize class: xxxxxxxxxxxxxxxx.zzzzzzzzzzz
[INFO]  CRM Build : 9.3.PB0.HFB85
[INFO]  CRM BuildTime : 11242016_183303
[INFO] java.lang.UnsatisfiedLinkError: no JDispLoad63 in java.library.path
.
.
.
[INFO] There may not be enough copies of the library for the class loaders
[INFO] that need it. Check your system settings, and make sure that there are
[INFO] enough copies of JDispLoad for the class loaders that need them.
[INFO] You can make up to 63 copies of the library - 16 are provided by default.
[INFO] [MASTER] 09:34:09.979 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1481096049976. Configuration id : null
[INFO] java.lang.UnsatisfiedLinkError: xxxxxx.xxxxxx.create(Ljava/lang/String;)J

What can be the issue?
Is it possible to exclude   specific class from generation? (using maven)

**Comment by gofraser** [comment]
Your class xxx.zzz is executing code in the static initialiser that depends on a native library JDispLoad63, and it can't find that. Can you try setting the path where this library can be found using the "-libraryPath /foo/bar" command line parameter of EvoSuite?

**Comment by yevsh** [comment]
I am using mavem, so all dependencies should be already there... or am I wrong?

**Comment by yevsh** [comment]
**Update,** 
it's not related to this class... ( I removed everything from that class and rerun) 

and still getting:


[INFO] java.lang.UnsatisfiedLinkError: no JDispLoad63 in java.library.path
[INFO]  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
[INFO]  at java.lang.Runtime.loadLibrary0(Runtime.java:870)
[INFO]  at java.lang.System.loadLibrary(System.java:1122)
[INFO]  at com.clarify.cbo.KJniDisp.<clinit>(KJniDisp.java:1030)
[INFO]  at com.clarify.cbo.Application.<init>(Application.java:83)

**Comment by gofraser** [comment]
Maven handles jar dependencies, I don't think it handles native library dependencies, and I can't find anything relevant in the Maven API. If you know any way to determine what the java.library.path should be set to for a given Maven project, it would be easy to integrate that in the Maven plugin.

The error in com.clarify.cbo.KJniDisp is the same problem - the static constructor is trying to load the same native library. I am not sure it's easily possible to exclude this, as according to your stack trace the class is not explicitly loaded by EvoSuite, but by some other dependency (com.clarify.cbo.Application). I assume excluding the library this is contained in is not an option?

**Comment by yevsh** [comment]
Nope, it's not possible.

**Comment by gofraser** [comment]
Well, we could skip the class if it leads to this error - but I'm not sure what would be the implications of doing this. Could you maybe create a minimal example Maven project with this native library dependency so I could try?

**Comment by yevsh** [comment]
Well it's part of huge project, I am not even sure where is the source of that lib....

**Comment by gofraser** [comment]
Well, that makes it difficult to do anything here.

I wonder if the Maven project actually puts the JDispLoad63 native library on the classpath, and it's just a matter of EvoSuite not detecting that? Could you please show me the output of:

   mvn dependency:build-classpath

If you can't show me that, can you please at least tell me if there's a JDispLoad63.dll, JDispLoad63.so, JDispLoad63.dylib (or JDispLoad63 dot anything really, or anything else that's not a jar file) on the class path?

**Comment by yevsh** [comment]
Bingo.

there is a zip file in classpath, this zip contains JDispLoad.dll

**Comment by gofraser** [comment]
Unfortunately putting a zip file on the java.library.path does not suffice to get Java find the native libraries inside the zip file (I just tried this on a small example). Is there a directory the zip file is extracted to by Maven during build/test?

**Comment by yevsh** [comment]
yes it's extracted to target\native\database-conf.

And in use by a
maven-surefire-plugin

**Comment by yevsh** [comment]
anyway My code uses this java lib, that in it;s turn loads the dll....
So I guess there is nothing that we can do.

**Comment by gofraser** [comment]
We could make the maven plugin set the java.library.path to the right directory in principle, but I'd need to understand where to get that information from. If you can produce an example maven project with the dependency that causes the problem, then I could investigate this - without that, it becomes a guessing game.

**Comment by yevsh** [comment]
I will try to do provide that , thanks.

**Comment by yevsh** [comment]
For now , we can close this issue as it's too much effort to reproduce for investigation.
So for this project manual tests will be created.
