### ISSUE TITLE
How does evosuite compute coverage criteria?

### ISSUE THREAD

**Issue by moar82** [EvoSuite/evosuite#68]
Hello, as far as I know EVOSUITE  applies a genetic algorithm  to
evolve a set of test cases that maximizes certain coverage criteria.  In the current version, Evosuite allows three type of criteria, that is branch, weakmutation and strongmutation.
  I wonder if you could give me some reference or point me to the code where Evosuite computes the coverage criteria, and the fitness function.

Thank you.

**Comment by gofraser** [comment]
The branch coverage fitness function is probably best explained in this article: http://www.evosuite.org/wp-content/papercite-data/pdf/tse12_evosuite.pdf

The mutation fitness function is probably best explained in this article:
http://www.evosuite.org/wp-content/papercite-data/pdf/emse14_mutation.pdf

By default, EvoSuite uses a combination of 8 fitness functions (line coverage, branch coverage, weak mutation testing, direct call branch coverage, output coverage, method coverage, method-no-exception coverage, exception coverage). See: http://www.evosuite.org/wp-content/papercite-data/pdf/ssbse15_multi.pdf

To see how to write new fitness functions check out the tutorial: http://www.evosuite.org/documentation/tutorial-part-4/

Finally, to see how the existing fitness functions are implemented, check the `org.evosuite.coverage` package in the client module. For each criterion, there is a *SuiteFitness class which measures the fitness of a whole test suite, a *TestFitness class which represents one specific coverage goal, and a *Factory which generates all individual goals (these individual goals are e.g. used during minimisation).
