### ISSUE TITLE
Does EvoSuite supports Mock in the Test Cases?

### ISSUE THREAD

**Issue by deepeshforjava** [EvoSuite/evosuite#69]
I could not see anywhere it is using Mock framework to generate the test cases and used Stub etc.

Could somebody please let me know if it can use mocking frameworks in generation or we explicitely have to modify the test cases as per our needs. I could not see the Evosuite option in Eclipse so tried generating from command line.

Thanks !

**Comment by gofraser** [comment]
EvoSuite uses its own set of mock classes to replace non-deterministic and IO related calls (see classes in the org.evosuite.runtime.mock package). You can also enable the use of Mockito using -Dp_functional_mocking=<probability of using mock classes>, for example 0.8. EvoSuite will first try to achieve coverage without mocks, but after a certain percentage of the search budget (specified by -Dp_functional_mocking=<...>, default 0.5) it will try using Mockito mocks. It will also use Mockito to instantiate interfaces for which there are no concrete classes. The Eclipse plugin does not provide a possibility to change this behaviour currently.
