### ISSUE TITLE
Sometimes the generated tests are not written to the test directory!

### ISSUE THREAD

**Issue by Mozhan** [EvoSuite/evosuite#70]
Hi,

In some cases the generated tests may not be compiled which then prevents them from being written to the test directory – handled in JUnitAnalyzer. removeTestsThatDoNotCompile(tests).

**Issue**
Sometimes this happens because in `Scaffolding.java`, in `generateBeforeClass`, a call is made to `setSystemProperties` while this method might not have been generated if `Properties.REPLACE_CALLS` returns false (please see generateSetSystemProperties).

**Fix suggestion:** 
In `generateBeforeClass`, an additional check block could be defined for both `Properties.REPLACE_CALLS` and ` Properties.RESET_STATIC_FIELDS`, in which the call to `setSystemProperties` is made.

Kindly,
Mozhan

**Comment by gofraser** [comment]
Thanks, this is now fixed.
