### ISSUE TITLE
No defined classpath for target project 

### ISSUE THREAD

**Issue by ajmersaini** [EvoSuite/evosuite#72]
Dear all, I am new to evosuite and maven i was trying it for fisrt time and got this message 

C:\Tutorial_Stack>java -jar evosuite-1.0.3.jar
* EvoSuite 1.0.3
# **No defined classpath for the target project. From command line you can set it with the -projectCP option**

please help
C:\Tutorial_Stack>

**Comment by sinaa** [comment]
I presume you're following http://www.evosuite.org/documentation/tutorial-part-1/ .

The line on `java -jar evosuite-1.0.3.jar` is just saying how the tool can be run.

Please continue along with the tutorial, and follow the next steps.

**Comment by ajmersaini** [comment]
yes exactly i am following the same..please assist

**Comment by sinaa** [comment]
As I said earlier, please continue along with the tutorial. Notice that the tutorial mentions:

> we haven’t told EvoSuite what to do yet.

The message you are getting is _as expected_.

**Comment by gofraser** [comment]
Just follow the next steps in the tutorial - you will need to set the target class (-class fully.qualified.ClassName) and class path (-projectCP some.jar:other.jar:some/directory).
