### ISSUE TITLE
not able to generate test cases  though its working 

### ISSUE THREAD

**Issue by ajmersaini** [EvoSuite/evosuite#73]
I ran the following command following guidelines on http://www.evosuite.org/documentation/tutorial-part-1/  

it say JAVA compiler not found at the end, though i am able to run java in the same directory ie Tutorial_stack

Please assist.

C:\Tutorial_Stack>java -jar evosuite-1.0.3.jar -class tutorial.Stack -projectCP target/classes
* EvoSuite 1.0.3
* Going to generate test cases for class: tutorial.Stack
* Starting client
* Connecting to master process on port 2305
* Analyzing classpath:
  - target/classes
* Finished analyzing classpath
* Generating tests for class tutorial.Stack
* Test criteria:
  - Line Coverage
  - Branch Coverage
  - Exception
  - Mutation testing (weak)
  - Method-Output Coverage
  - Top-Level Method Coverage
  - No-Exception Top-Level Method Coverage
  - Context Branch Coverage
* Setting up search algorithm for whole suite generation
* Total number of test goals:
  - Line 11
  - Branch 7
[Progress:>                             0%] [Cov:>                                  0%]  - Exception 0
  - MutationFactory 50
  - Output 4
  - Method 4
  - MethodNoException 4
  - CBranchFitnessFactory 7
* Using seed 1487164864615
* Starting evolution
[Progress:==============================100%] [Cov:==================================>99%]
* Search finished after 61s and 661 generations, 165506 statements, best individual has fitness: 1.8333333333333333
* Minimizing test suite
* Going to analyze the coverage criteria
* Coverage analysis for criterion LINE
* Coverage of criterion LINE: 100%
* Total number of goals: 11
* Number of covered goals: 11
* Coverage analysis for criterion BRANCH
* Coverage of criterion BRANCH: 100%
* Total number of goals: 7
* Number of covered goals: 7
* Coverage analysis for criterion EXCEPTION
* Coverage of criterion EXCEPTION: 100%
* Total number of goals: 2
* Number of covered goals: 2
* Coverage analysis for criterion WEAKMUTATION
* Coverage of criterion WEAKMUTATION: 94%
* Total number of goals: 50
* Number of covered goals: 47
* Coverage analysis for criterion OUTPUT
* Coverage of criterion OUTPUT: 100%
* Total number of goals: 4
* Number of covered goals: 4
* Coverage analysis for criterion METHOD
* Coverage of criterion METHOD: 100%
* Total number of goals: 4
* Number of covered goals: 4
* Coverage analysis for criterion METHODNOEXCEPTION
* Coverage of criterion METHODNOEXCEPTION: 100%
* Total number of goals: 4
* Number of covered goals: 4
* Coverage analysis for criterion CBRANCH
* Coverage of criterion CBRANCH: 100%
* Total number of goals: 7
* Number of covered goals: 7
* Generated 6 tests with total length 29
* Resulting test suite's coverage: 99% (average coverage for all fitness functions)
* Generating assertions
* Resulting test suite's mutation score: 66%
* Compiling and checking tests
[MASTER] 18:52:09.910 [logback-2] ERROR TestSuiteGenerator - No Java compiler is available. Make sure to run EvoSuite with the JDK and not the JRE.You can try to setup the JAVA_HOME system variable to point to it, as well as to make sure that the PATH variable points to the JDK before any JRE.
[MASTER] 18:52:09.913 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: tutorial.Stack with seed 1487164864615. Configuration id : null
java.lang.RuntimeException: No Java compiler is available. Make sure to run EvoSuite with the JDK and not the JRE.You can try to setup the JAVA_HOME system variable to point to it, as well as to make sure that the PATH variable points to the JDK before any JRE.
        at org.evosuite.TestSuiteGenerator.compileAndCheckTests(TestSuiteGenerator.java:354) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.TestSuiteGenerator.postProcessTests(TestSuiteGenerator.java:332) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:148) ~[evosuite-1.0.3.jar:1.0.3]
        at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) ~[evosuite-1.0.3.jar:1.0.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_121]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]
* Computation finished

**Comment by ajmersaini** [comment]
my java_home is set to C:\Program Files\Java\jdk1.8.0_121
and path to    C:\Program Files\Java\jdk1.8.0_121;C:\maven\bin;%JAVA_HOME%\bin;C:\apache-maven-3.3.9\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\Peehu\Desktop\research\jmetal\jmetalhome

**Comment by sinaa** [comment]
Can you try to add the full jdk bin path to the PATH? `C:\Program Files\Java\jdk1.8.0_121\bin`

If it doesn't work afterwards, please paste what this command returns in cmd: `echo %PATH%`
