### ISSUE TITLE
mvn package is failed with error

### ISSUE THREAD

**Issue by gouthamkunduru** [EvoSuite/evosuite#76]
Hello Andrea and Gordon,

I faced the below errors while building the evosuite. I am doing a research project on EVOSUITE. Major intension is to replace the GA algorithm with CFO algorithm to check the behavior, But got this error at initial stages itself

>mvn package

[INFO] EvoSuite ........................................... SUCCESS [  7.729 s]
[INFO] evosuite-runtime ................................... SUCCESS [01:10 min]
[INFO] evosuite-client .................................... SUCCESS [04:14 min]
[INFO] evosuite-master .................................... FAILURE [01:49 min]
[INFO] evosuite-plugins ................................... SKIPPED
[INFO] Maven Plugin for EvoSuite .......................... SKIPPED
[INFO] evosuite-maven-plugin-test ......................... SKIPPED
[INFO] build-support-test ................................. SKIPPED
[INFO] evosuite-standalone-runtime ........................ SKIPPED
[INFO] evosuite-shaded .................................... SKIPPED
[INFO] evosuite-generated ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:26 min
[INFO] Finished at: 2017-02-17T12:41:47-05:00
[INFO] Final Memory: 20M/187M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (default) on project evosuite-master: Error creating shaded jar: Error in ASM processing class org/evosuite/runtime/agent/AgentLoader.class: String index out of range: 2 -> [Help 1]

Please let me know how to resolve this issue. I am trying to do this in eclipse please let me know how to add –DskipTests in eclipse.

Regards,
Goutham K

**Comment by gofraser** [comment]
See e.g. http://stackoverflow.com/questions/7252431/giving-arguments-to-maven-resources-goal-from-eclipse for how to specify properties for maven build goals in Eclipse.

My guess would be that you are getting the error when you are trying to build from Eclipse using M2Eclipse? There seem to be some issues with that plugin (e.g., http://stackoverflow.com/questions/37942689/maven-shade-plugin-reports-error-creating-shaded-jar-target-classes-is-a-d or http://stackoverflow.com/questions/23986331/maven-shading-error-access-is-denied/31330682#31330682). Can you try building on the command line if the problem also occurs there?

**Comment by gouthamkunduru** [comment]
I tried building from the command line (in windows environment) using mvn package command i got the same error. I am attaching the screenshot
![error](https://cloud.githubusercontent.com/assets/19714046/23081331/5c3397ce-f522-11e6-9b5b-5d43d2a13913.JPG)

**Comment by gofraser** [comment]
What version of Java are you using?

**Comment by gouthamkunduru** [comment]
i am using java 1.8
![capture](https://cloud.githubusercontent.com/assets/19714046/23081938/1f22a0e8-f525-11e6-8799-582b2035f5d8.JPG)

**Comment by gofraser** [comment]
And, just to make sure, you did try "mvn clean" before calling mvn package?

**Comment by gouthamkunduru** [comment]
i triggered "mvn clean" before calling "mvn package" and build is successful.
i have a question here what the steps that i should folllow?
1.mvn compile
2.mvn clean
3.mvn package
do i need to follow the above 3 steps?
Thanks.

**Comment by gofraser** [comment]
Great to hear it worked. I suggest you read the Maven documentation (https://maven.apache.org/guides/) or some Maven tutorials (e.g. https://www.tutorialspoint.com/maven/). mvn package will first call "compile" so you don't need to call compile explicitly. Calling mvn clean before you do package is probably a good idea, depending on what you changed since the last time you compiled.
