### ISSUE TITLE
one typo in the guide docs.

### ISSUE THREAD

**Issue by zhangzheyuk** [EvoSuite/evosuite#78]
http://www.evosuite.org/documentation/tutorial-part-1/ 

export CLASSPATH=target/classes:evosuite-runtime-1.0.3.jar:evosuite-tests:target/**depdendency**/junit-4.12.jar:target/dependency/hamcrest-core-1.3.jar

**Comment by sinaa** [comment]
Thank you for reporting this. It has been corrected.
