### ISSUE TITLE
how to set external mutants pool?

### ISSUE THREAD

**Issue by claudejin** [EvoSuite/evosuite#79]
Hi,
I'm setting an experiment using EvoSuite and Major.

I want to make test suites on mutation criteria, but want EvoSuite to use the mutants pool generated by Major. How can I put the pool as input to EvoSuite?
If it is possible, please give me some guides.
Otherwise, can I extract the mutants information and the mutation kill table of the generated test suite from EvoSuite?

Thank you.

**Comment by gofraser** [comment]
It is currently not possible to use mutants generated by an external mutation tool; EvoSuite has its own set of mutation operators which it uses for the mutation criteria.

There's also no explicit feature to create a kill map of tests and mutants. You could try enabling test comments (-Dtest_comments=true), which will (should...) give you a list of mutants killed by each test as a code comment. You could also use "-Doutput_variables=MutationCoverageBitString -Danalysis_criteria=mutation" which will give you a bit string indicating which mutants are killed (mutants represented by 1 are killed, 0 alive), but this doesn't tell you which test killed which mutant.

I am not sure what exactly you are trying to achieve, but why not generate some tests first, and then independently use an external mutation tool like Major to create a killmap of tests and Major mutants?

**Comment by claudejin** [comment]
I just wanted to know where I should modify to produce a kill map of tests and mutants. Eventually, I want to produce a fitness value map of tests and mutants. With the information you told me, now I can produce a kill map and a fitness value map, modifying the CoverageCriteriaAnalyzer class.

Thanks!

**Comment by gofraser** [comment]
Sounds like this is resolved; closing this issue. If there are still problems, please re-open.
