### ISSUE TITLE
Can't run via commandline in Win10

### ISSUE THREAD

**Issue by marklapasa** [EvoSuite/evosuite#8]
Using Windows 10:

![image](https://cloud.githubusercontent.com/assets/4932453/11734715/cb22282c-9f87-11e5-98f9-1acefa599a97.png)

Here's the version of java I am using

![image](https://cloud.githubusercontent.com/assets/4932453/11734733/e2ee7140-9f87-11e5-90be-4f7c59ded7aa.png)

**Comment by sinaa** [comment]
EvoSuite runs on Java 1.8. I believe we need to make it more clear on the documentation.

So, installing JDK 1.8 and putting it on the PATH would resolve the issue.

**Comment by marklapasa** [comment]
![image](https://cloud.githubusercontent.com/assets/4932453/11734874/04120520-9f89-11e5-9caa-52c7c1b64902.png)

Yup! Thx
