### ISSUE TITLE
this issue can't be resolved now? Thanks

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#83]
[MASTER] 10:59:11.574 [logback-2] ERROR ClassStateSupport - Class oracle.jdbc.driver.OracleDriver was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.

**Comment by sinaa** [comment]
As mentioned in #84 , please submit a new issue https://github.com/EvoSuite/evosuite/issues/new with the necessary steps to reproduce, and we can have a look.
