### ISSUE TITLE
when I want to generate test suit for controller, it didn't generate any test case.But not for all controllers. 

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#84]
I use command line. Did I make something wrong?

**Comment by IndyPaula** [comment]
LDily, you are using the version Evosuite1.0.3, if the kind of attributes of methods are complex objects, i thinks that the tool will have difficulty in to create cases of test to this objects.

**Comment by sinaa** [comment]
It is near impossible for us to help with this question without having some context on the application you are testing, an example of the program code, the command line arguments you used to execute Evosuite, your classpath values, etc.

We have added an issue template to help with better structuring your issues. If you are still facing an issue, please submit a new issue https://github.com/EvoSuite/evosuite/issues/new with the necessary steps to reproduce, and we can have a look.
