### ISSUE TITLE
Trying to get a basic command-line example working but no results

### ISSUE THREAD

**Issue by marklapasa** [EvoSuite/evosuite#9]
In an Android project, I have a very super basic POJO that looks like this:

![image](https://cloud.githubusercontent.com/assets/4932453/11735950/6bd48f50-9f95-11e5-9dbb-fdedcc38662f.png)

Android does not deal with .class files, it deals with .class files converted into DEX format. This is the directory where the .class files are staged before this final conversion step.

![image](https://cloud.githubusercontent.com/assets/4932453/11735985/046fa01a-9f96-11e5-972a-729193f01d73.png)

But to simplify for the purposes of getting a basic test case going, I've deleted all the Android files and left the Bookstore POJO by itself.

![image](https://cloud.githubusercontent.com/assets/4932453/11735997/338920ba-9f96-11e5-9783-c9793f74130d.png)

So in the command-line, I try to perform the following:

![image](https://cloud.githubusercontent.com/assets/4932453/11736004/61626186-9f96-11e5-909f-491dcbb44736.png)

But nothing gets created and I am left with this errors

![image](https://cloud.githubusercontent.com/assets/4932453/11736043/127bb5c6-9f97-11e5-971b-c74a395a4f03.png)

Here is the log.txt from trying to create Unit Test for Bookstore.java

[log.txt](https://github.com/EvoSuite/evosuite/files/59036/log.txt)

What is it that I am doing wrong? I can't seem to find anything that was generated.

**Comment by arcuri82** [comment]
Hi,
  this seems like the same issue as in https://github.com/EvoSuite/evosuite/issues/2

it should be fixed in the current 1.0.2-SNAPSHOT

**Comment by marklapasa** [comment]
So two things:

1) In 1.0.1, I've explicitly set the tools jar location and that is giving the same "No Java compiler avail are you running the JDK":

![image](https://cloud.githubusercontent.com/assets/4932453/11747992/12f5854c-9ff4-11e5-894f-69fab3cbf886.png)

![image](https://cloud.githubusercontent.com/assets/4932453/11748035/4f9fb986-9ff4-11e5-8ab1-da78fdae93d7.png)


2) How do I get hold of 1.0.2-SNAPSHOT jar? I am an Intell-J/Android Studio user who uses gradle/git. I am having a hard time trying to hunt down the binary on http://www.evosuite.org/m2/org/evosuite/

If I read the .pom file correctly, it should be located here - http://www.evosuite.org/m2/org/evosuite/evosuite/ under the 1.0.2-SNAPSHOT directory but that does not seem to exist here.

**Comment by arcuri82** [comment]
regarding (2), the documentation was indeed confusing. I updated it in http://www.evosuite.org/downloads/ by stating:

"If you compile (e.g., “mvn package”) the latest snapshot from the Git repository, then the executable will be in the “master/target” folder with name “evosuite-master-<version>.jar”."

**Comment by arcuri82** [comment]
regarding (1), now that I look at it, it seems you have a missing "="  between "-Dtools_jar_location" and its location. At any rate, we should throw an exception in this case, instead of silently ignore such setting

**Comment by arcuri82** [comment]
1.0.2 is now released, where the reported issue is (should be) fixed. See http://www.evosuite.org/downloads/

cheers

Andrea
