### ISSUE TITLE
Problem to build the Evosuite-1.0.4

### ISSUE THREAD

**Issue by IndyPaula** [EvoSuite/evosuite#90]
I'm trying to use the Evosuite 1.0.4 version, I cloned from git,  but present errors. Now, it's throwing this error:

[ERROR] Failed to execute goal on project evosuite-runtime: Could not resolve dependencies for project org.evosuite:evosuite-runtime:jar:1.0.4: Could not find artifact com.sun:tools:jar:1.0.0 at specified path C:\Program Files\Java\jre1.8.0_51..\lib\tools.jar -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :evosuite-runtime

**Comment by sinaa** [comment]
You need to use JDK1.8 rather than JRE.
