### ISSUE TITLE
I have a question about unit test.

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#91]
such as an example of Triangle.
public int type(double a,double b,double c){  
		int result = 0;    
		boolean b11 = a + b > c;   
		boolean b12 = a + c > b;   
		boolean b13 = b + c > a;   
		if(b11 && b12 && b13){    
			if(a == b && b == c){     
				result = 1;     
				}else if(a == b || b == c || a == c){       
					result = 2;    
					}else{      
						result = 3;    
						}   }else{    
							result = -1;
							}
		return result; 
}
if it is a equilateral triangle ,I want to return 1. But if I write 2 wrongly, and the test case generated by evosuite is "assertEquals(2,(4.4.4));" and passed. So it can't find the problem of the code. How can evosuite find this kind of error of the code? 
Thank you.

**Comment by sinaa** [comment]
Evosuite only generates tests based on the _current_ behaviour of the program. It is not a "bug finding" tool. You can however use the generated tests to find regression bugs:

If you generate it on the correct version and it produces `assertEquals(1,(4.4.4));`, then if you change it to 2 in the program and re-run the test, the previous assertion will fail.

**Comment by LDily** [comment]
I don't know if I understand right. 
as you say, evosuite generates tests based on the current behaviour of the program,so all the test cases generated by evosuite will be passed ? It can't find the bug of the current source code?
I re-run the test cases when the source code changed ,then it will find the bug of the source code?
Thanks.

**Comment by sinaa** [comment]
Correct. For the current version (the version you generated tests for), it's on _you_ to decide whether the tests are reflecting your expected behaviour of the program.

**Comment by LDily** [comment]
Thank you very much!
