### ISSUE TITLE
Error when running evosuite

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#93]
Hello, I want to know can I solve the errors through some ways which I got when running evosuite on the premise of my proper use of evosuite such as "ERROR ClientNodeImpl - Cannot inform master of change of state". When I checked source code of the evosuite , I found it's a "RemoteException" you caught and output.
source code:
try {
			masterNode.evosuite_informChangeOfStateInClient(clientRmiIdentifier, state,information);
		} catch (RemoteException e) {
			logger.error("Cannot inform master of change of state", e);
		}
Thank you very much.

**Comment by sinaa** [comment]
Not all errors shown by evosuite are critical. In this case, either evosuite successfully generated tests in the end, or an issue happened earlier. 

Again, without you answering the items requested in the "New Issue" page, there isn't much else we can help with.
