### ISSUE TITLE
I found a problem When I generated test case for an little example 

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#94]
test code:
package com.glen.he;
public class ComplexCalculation {
    public int Division(int a,int b){ 
    	try {
        return (a/b);     }
    	catch (ArithmeticException e){
    		return -1;	
    	}
    }
}
Generated test case by evosuite:
@Test(timeout = 4000)
  public void testDivisionThrowsArithmeticException()  throws Throwable  {
      ComplexCalculation complexCalculation0 = new ComplexCalculation();
      // Undeclared exception!
      try { 
        complexCalculation0.Division(0, 0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.glen.he.ComplexCalculation", e);
      }
  }
It was failed when I run this test case .
However when I didn't catch exception in my source code:
package com.glen.he;
public class ComplexCalculation {
    public int Division(int a,int b){ 
        return (a/b);   		
    	}
}
The test case generated by evosuite was the same , but It was successed when I run this test case .

The test case passed When the source code exits hidden danger ,however when I catch exception in my source code ,the test case failed.

**Comment by sinaa** [comment]
Just to see if I understand this correctly, I executed Evosuite on your class.
With the version with the exception, the following test suite was generated:
```
  @Test
  public void test0()  throws Throwable  {
      test.Test test0 = new test.Test();
      int int0 = test0.Division(2335, 2063);
      assertEquals(1, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      test.Test test0 = new test.Test();
      int int0 = test0.Division((-245), 3080);
      assertEquals(0, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      test.Test test0 = new test.Test();
      int int0 = test0.Division(2063, 0);
      assertEquals((-1), int0);
  }
````
The tests pass on the version they were created on without any problems.

I then generated tests for the second version (without the catch block), and it produced the following test suite:
```
  @Test
  public void test0()  throws Throwable  {
      test.Test test0 = new test.Test();
      int int0 = test0.Division(1, 2151);
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      test.Test test0 = new test.Test();
      int int0 = test0.Division((-2494), 2151);
      assertEquals((-1), int0);
  }

  @Test
  public void test2()  throws Throwable  {
      test.Test test0 = new test.Test();
      int int0 = test0.Division(2448, 1);
      assertEquals(2448, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      test.Test test0 = new test.Test();
      // Undeclared exception!
      try { 
        test0.Division(0, 0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         assertThrownBy("test.Test", e);
      }
  }
```

Everything seems to be as expected.

**Comment by LDily** [comment]
Thank you . I think the test3 for the second version (without the catch block) should fail in order to find the problem of the source code but it passes. Am I wrong?

**Comment by sinaa** [comment]
The test is correctly reflecting the program's behaviour. See my answer in #91
