### ISSUE TITLE
Can Evosuite generates useful tests for classes which use database?

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#95]
When I use Evosuite to generate tests for program with springMVC, It almost generates no test cases for prefix Dao/Service/Controller. Does it relates to database or SpringFrameWork?
Thank you !

**Comment by gofraser** [comment]
See http://www.evosuite.org/wp-content/papercite-data/pdf/ssbse16_jee.pdf for examples on which JEE features EvoSuite supports. In particular, there is only very limited support to initialise databases with useful values. If there are specific classes where you think EvoSuite should be generating tests feel free to submit a more concrete issue about them.
