### ISSUE TITLE
Clients have not finished yet, although a timeout occurred.

### ISSUE THREAD

**Issue by zhangzheyuk** [EvoSuite/evosuite#96]
### Context
WIN7-X64.
evosuite commond line.
use evosuite to generate test cases for an OSGI project.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

1. just run the command.
2.
3.

### EvoSuite Arguments
java -jar E:\unit\evosuite-1.0.3.jar -target xxxx\bin -DCP_file_path="E:\unit\dirlist"

### Current Result

![image](https://cloud.githubusercontent.com/assets/2291316/24188340/f2ad43e0-0f1b-11e7-9113-7a324d333ec3.png)

 
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

### Additional info
*Please add any information of interest here below*

**Comment by gofraser** [comment]
Does this occasionally happen, or always?
Does this also happen if you use 1.0.4?
Does it always happen at the same time?

**Comment by gofraser** [comment]
Without further information, I don't think there is a specific bug here. It might be that your specific class runs into plenty of timeouts, in which case it might be useful to try changing some of the timeouts, e.g. by using -Dextra_timeout=180 

I'm closing the bug report; let me know if the problem persists.
