### ISSUE TITLE
Erro to generate a suite of tests

### ISSUE THREAD

**Issue by IndyPaula** [EvoSuite/evosuite#97]
How do I generate a suite whose design structure is al in packages? For example: Inside of the "bin" has others packages with the ".class"

The command used was: **java -jar evosuite-1.0.4.jar -generateSuite  bin/.class**
The erro:

[MASTER] 11:10:49.018 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1490191849014. Configuration id : null
java.lang.IllegalArgumentException: There is one unrecognized input: [bin/.class]
Recall, '-Dx=v' assignments should have no space, i.e. '-Dx= v' and '-Dx = v' are wrong
        at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:148) ~[evosuite-1.0.4.jar:1.0.4]
        at org.evosuite.EvoSuite.main(EvoSuite.java:301) ~[evosuite-1.0.4.jar:1.0.4]

Promptly, thank you for the return.

**Comment by sinaa** [comment]
First, please read the tutorial carefully as that should already answer many of your questions. http://www.evosuite.org/documentation/tutorial-part-1/

the argument to generate tests for classes in a particular location is through -projectCP .

So if you have your compiled program in bin, you provide: `-generateSuite -projectCP "bin"`

But you then need to also specify which class you want to test with `-class my.pkg.MyClass`
You can also use the `-target` option to generate tests for all classes.

All of these are in the tutorials. Our wiki might be a good reference to all available material: https://github.com/EvoSuite/evosuite/wiki

Finally, github issues are for bugs in Evosuite. Please use http://stackoverflow.com/ with tag #evosuite if you have problems/questions using the tool.
